import { boatResultBodies, defineClearLocale, entries, likeResults } from './clearLocaleFactory'

const seq = (prefix: string, count: number) => Array.from({ length: count }, (_, i) => prefix + String(i + 1).padStart(2, '0'))
const body = ['chest_tight','heart_racing','stomach_uncomfortable','restless','tired','sleepless','want_to_cry','none','other'] as const
const triggers = ['no_reply','attitude_changed','social_media','argument','missing_them','waiting_response','overthinking','other'] as const
const emotions = ['missing','anxious','sad','hurt','angry','jealous','afraid','lost','confused','hopeful'] as const
const observations = ['initiates_contact','makes_time','keeps_promises','listens','mutual_effort','words_match_actions'] as const
const needs = ['reassurance','understanding','respect','company','space','clarity','boundaries','rest','return_to_life','unknown'] as const
const actions = ['put_phone_down','stop_checking_social','shower_or_rest','take_a_walk','continue_own_plan','talk_to_trusted_person','reply_when_calm','decide_tomorrow','write_diary','custom'] as const
const patterns = ['rumination','message_dependency','over_interpretation','detective','self_sacrifice'] as const
const brainQuestions = patterns.flatMap((pattern) => seq(pattern + '_', 5))
const likeQuestions = ['real_person_three_real_traits','real_person_without_romantic_expectation','real_person_present_vs_future_version','habit_expect_regular_contact','habit_absence_feels_like_missing_routine','habit_missing_the_routine','fear_of_loss_hardest_part','fear_of_loss_person_vs_feeling','fear_of_loss_avoiding_discomfort','imagined_relationship_future_more_than_reality','imagined_relationship_future_fills_present_gap','imagined_relationship_reality_description'] as const
const likeAnswers = ['yes','some','not_really','not_sure','probably_yes','probably_no','mostly_present','both','mostly_future','often','sometimes','rarely','somewhat','no','maybe','mostly_person','mostly_feeling'] as const
const likeOptions = ['lose_this_person','lose_daily_companionship','lose_feeling_cared_for','be_alone','investment_feels_wasted','no_result','uncertainty','other'] as const

const en: Record<string, string> = {
  'clear.home':'Back to Clarity','clear.empty':'No clarity records yet. Start with the tool that fits this moment.','clear.history.title':'Recent clarity records','clear.history.view':'View result','clear.history.delete':'Delete record','clear.history.deleteTitle':'Delete this clarity record?','clear.history.deleteBody':'This cannot be undone. Star-heart points already awarded will stay.','clear.history.deleteWithStar':'This record already has a clarity star. Confirming deletes only the record and keeps the star.','clear.history.deleteStarToo':'Delete this clarity star too','clear.history.clearRecord':'Organize my feelings','clear.history.loveBoat':'Infatuation Guide','clear.history.loveBrain':'Love-pattern check','clear.history.likeOrHabit':'Like or habit?',
  'clear.common.previous':'Previous','clear.common.next':'Next','clear.common.continueLater':'Continue later','clear.common.continue':'Resume','clear.common.draftProgress':'Resume · {current} / {total}','clear.common.restart':'Start over','clear.common.restartTitle':'Start over?','clear.common.restartBody':'Your unfinished answers will be cleared.','clear.common.progress':'{current} / {total}','clear.common.overview':'Question overview','clear.common.saveStar':'Save as a clarity star','clear.common.savedStar':'Saved as a clarity star','clear.common.finishAndReturn':'Finish and return home','clear.common.savedDraft':'Your answers are saved on this device as you go.','clear.common.error':'Unable to save right now. Check the required fields and try again.','clear.common.result':'Your result',
  'clear.star.clear_record':'I finished organizing my feelings and cared for myself in this moment.','clear.star.love_boat_code':'I noticed how much I had invested and looked at what was actually happening.','clear.star.love_brain_assessment':'I noticed the patterns that have been affecting me lately.','clear.star.like_or_habit':'I slowly separated liking, habit, fear of loss, and expectation.',
  'clear.organize.intro':'Slowly separate what happened, your thoughts, your feelings, and your next step.','clear.organize.step1':'What happened?','clear.organize.step1Help':'Choose a situation or write something—at least one is required.','clear.organize.triggerText':'If you want, briefly write down what just happened.','clear.organize.step2':'Separate the pieces','clear.organize.facts':'What I know for sure','clear.organize.factsPlaceholder':'For example: I sent a message last night and they have not replied yet.','clear.organize.interpretation':'What my mind is telling me','clear.organize.interpretationPlaceholder':'For example: Maybe they do not want to talk to me anymore?','clear.organize.unknown':'What I do not know yet','clear.organize.unknownPlaceholder':'For example: Why they have not replied.','clear.organize.step3':'How do I feel right now?','clear.organize.intensity':'How strong is this feeling right now?','clear.organize.body':'What do I notice in my body? (optional)','clear.organize.step4':'Pause before guessing what they feel','clear.organize.step4Help':'These are interactions you have observed so far; you may skip this.','clear.organize.step5':'What do I truly need right now?','clear.organize.needs':'What I need','clear.organize.action':'What am I willing to do for myself now?','clear.organize.customAction':'Write my own next step','clear.organize.step6':'What did I notice this time?','clear.organize.finish':'Finish this reflection','clear.organize.closing':'You do not need an answer about this relationship right now. Start by caring for yourself in this moment.','clear.organize.completed':'Reflection complete. Star-heart +5.','clear.organize.answer.yes':'Yes','clear.organize.answer.no':'No','clear.organize.answer.unknown':'Not sure yet',
  'clear.boat.intro':'This is not about measuring how much you love someone. It compares how far your feelings have gone with what has actually happened.','clear.boat.start':'Take a look','clear.boat.sectionA':'A | How invested am I?','clear.boat.sectionB':'B | How do they actually respond?','clear.boat.unknownHelp':'Not knowing is not a negative answer and is excluded from the response ratio.','clear.boat.answer.0':'Almost never','clear.boat.answer.1':'Occasionally','clear.boat.answer.2':'Sometimes','clear.boat.answer.3':'Often','clear.boat.response.2':'Yes','clear.boat.response.1':'Sometimes','clear.boat.response.0':'No','clear.boat.response.unknown':'I do not know yet','clear.boat.finish':'Finish this Infatuation Guide','clear.boat.completed':'This Infatuation Guide is now in your history.','clear.boat.scoreA':'My investment: {score} / 36','clear.boat.result.insufficient':'There is not enough observable interaction yet. You do not need to define the relationship now.','clear.boat.result.body':'Do not rush to guess what they feel or blame yourself for liking them. Compare your investment with what is actually happening.',
  'clear.brain.intro':'This is not about how “love-brained” you are. It helps you notice where you are most likely to lose sight of yourself when you really like someone.','clear.brain.duration':'25 questions | about 4–5 minutes','clear.brain.start':'Take a look','clear.brain.finish':'Finish this check','clear.brain.completed':'This check is now in your history.','clear.brain.low':'You are still keeping your own rhythm','clear.brain.resultIntro':'Lately, this is where you may be affected most easily','clear.brain.primary':'Most noticeable pattern right now','clear.brain.secondary':'Also appears often','clear.brain.tie':'These patterns are equally noticeable right now',
  'clear.like.intro':'What is hardest to let go of: this person, or how this relationship makes me feel?','clear.like.start':'Take your time','clear.like.section.real_person':'Do I like who they really are?','clear.like.section.habit':'Am I used to having them around?','clear.like.section.fear_of_loss':'Am I afraid of losing this?','clear.like.section.imagined_relationship':'Do I like reality, or the future I imagine?','clear.like.prompt.real_person':'What I appreciate about them…','clear.like.prompt.habit':'What I am most used to…','clear.like.prompt.fear_of_loss':'If this relationship did not continue, the hardest part would be…','clear.like.prompt.imagined_relationship':'If I only look at what has happened, I would describe this relationship as…','clear.like.other':'Anything else I want to add','clear.like.preview':'See my reflection result','clear.like.finish':'Finish this reflection','clear.like.completed':'This reflection is now in your history.','clear.like.validation':'Complete the required choices on all four cards. If you choose Other, add the details too.','clear.like.closing':'You do not need to name the feeling yet. First notice what is hardest to let go of.',
}

Object.assign(en,
  entries('clear.organize.body.', body, ['Tight chest','Racing heart','Upset stomach','Restless','Very tired','Unable to sleep','Wanting to cry','No noticeable sensation','Other']),
  entries('clear.organize.trigger.', triggers, ['They did not reply','Their attitude seems different','I saw their social media or updates','We had an unpleasant interaction','I suddenly miss them a lot','I am waiting for their response','I started overthinking','Other']),
  entries('clear.organize.emotion.', emotions, ['Missing them','Uneasy','Sad','Hurt','Angry','Jealous','Afraid','Disappointed','Confused','Hopeful']),
  entries('clear.organize.observation.', observations, ['They initiate contact','They make time to be with me','They usually keep their promises','They listen when I express my feelings','I am not always the only one making an effort','Their words and actions mostly match']),
  entries('clear.organize.need.', needs, ['Reassurance','To be understood','Respect','Company','Some space of my own','Clarity','To recognize my boundaries','Rest','To bring my attention back to life','I do not know yet']),
  entries('clear.organize.action.', actions, ['Put my phone down for a while','Stop checking their updates for now','Take a shower or rest','Go for a walk','Continue with my original plan','Talk to someone I trust','Reply when I feel calmer','Decide tomorrow','Write in today’s diary','Write my own action']),
  entries('clear.boat.level.', ['investment_low','investment_mild','investment_high','investment_very_high','response_insufficient_observation','response_low','response_mixed','response_good','response_high'], ['My attention is still with me','I am starting to feel affected','My attention often circles around them','This relationship has taken a lot of my energy lately','I need more time to observe','There are few visible responses so far','There are some responses and some uncertainty','I can see quite a few concrete responses','The interaction is mostly mutual so far']),
  entries('clear.boat.result.', ['low_low','low_mixed','low_good','low_high','mild_low','mild_mixed','mild_good','mild_high','high_low','high_mixed','high_good','high_high','very_high_low','very_high_mixed','very_high_good','very_high_high'], ['Still observing','Getting closer slowly','Responses, with room for myself','Getting closer at a steady pace','My feelings are moving faster','Pulled by ambiguity','Feelings with real responses','Both are moving closer','My feelings are ahead','My investment is ahead of the answers','Deeply interested, with responses','Very moved—remember myself too','My feelings are ahead of the relationship','Highly invested, but answers lag behind','Many responses, but my mind is crowded','Mutual responses, with room for myself']),
  entries('clear.boat.insufficientTitle.', ['investment_low','investment_mild','investment_high','investment_very_high'], ['No need to define it yet','My feelings are moving closer, with little information','My feelings are close; let reality catch up','Many thoughts, but too little is known']),
  entries('clear.boat.q.', seq('a', 12), ['I repeatedly check whether they replied to my message.','When they do not reply for a long time, it is hard to focus on my own tasks.','When they reply, my mood immediately improves a lot.','I often replay our conversations or time together in my mind.','I keep guessing what a word, emoji, or read receipt means.','I cannot help checking their social media, updates, or online status.','I often want proof that they care about me or like me.','If they become a little distant, I easily wonder whether I did something wrong.','I have postponed my own plans while waiting for their response.','Before the interaction has gone very far, I often imagine a distant future together.','Even when nothing new has happened, they keep coming to mind.','Recently, this person or relationship has occupied a lot of my attention and feelings.']),
  entries('clear.boat.q.', seq('b', 10), ['They initiate contact too, rather than always waiting for me.','They make time to spend with me.','They usually follow through on what they promise.','They listen when I express my feelings or thoughts.','They remember things I told them that matter to me.','When communication is needed, they usually do not disappear without explanation.','Their actions mostly match what they say.','I am not always the only person maintaining this interaction.','I mostly know where I stand in the relationship right now.','When we interact, I usually do not need to keep guessing what they mean.']),
  entries('clear.brain.pattern.', patterns, ['Thought-loop pattern','Message-dependent pattern','Over-interpretation pattern','Clue-checking pattern','Self-sacrificing pattern']),
  entries('clear.brain.q.', brainQuestions, [
    'After a conversation, I often replay what we said several times.','When an interaction feels slightly off, I may keep wondering whether I did something wrong.','Even after something is over, I repeatedly think about the scene or feeling.','I know more thinking will not give me an answer, but it is still hard to stop.','While doing other things, my mind suddenly circles back to this relationship.',
    'I automatically check repeatedly for a message from them.','When they take a long time to reply, my mood is easily affected.','Seeing their message or notification can shift my mood sharply.','Waiting for their message sometimes makes it hard to focus on what I was doing.','I pay close attention to changes in reply speed, length, or tone.',
    'I sometimes wonder for a long time whether an ordinary remark has another meaning.','I closely analyze their emoji, tone, or sentence endings.','If they seem a little distant, I quickly start guessing what happened.','I extend a small interaction into many possibilities in my mind.','Without clear evidence, I often imagine what a behavior might mean.',
    'I check their social media to learn what they have been doing.','I sometimes notice when they are online, whose posts they like, or whom they interact with.','When something feels off, I cannot help looking for more clues.','To understand their situation, I have looked at more content than I intended.','Even when nothing is new, I sometimes check their updates again.',
    'I have changed my plans to accommodate them.','Even when I feel uncomfortable or do not want to, I sometimes put their needs first.','I worry that refusing or disagreeing may make them move farther away.','I sometimes put their feelings ahead of my own.','To maintain the relationship, I have held back things I really wanted to say.',
  ]),
  entries('clear.like.q.', likeQuestions, [
    'Can I name at least three things I genuinely appreciate that happened in reality, not in my imagination?','Without romantic ambiguity or the hope of dating, would I still enjoy spending time with this person?','Do I like who they are now, or who I hope they may become?','Do I expect a message or interaction from them at a fixed time every day?','Without their messages or presence, would life feel as if a regular part were missing?','Is part of what I miss the feeling that used to be there every day?','If this relationship did not continue, what would be hardest for me?','Would it be harder to lose this person, or the feeling of company and being cared about?','Have I avoided admitting that some interactions make me uncomfortable because I fear losing them?','Do I spend more time imagining the future than actually being together?','Do I use “maybe someday” to fill in what is absent now?','If I only consider what has happened—not what I hope for—how would I describe the relationship now?',
  ]),
  entries('clear.like.answer.', likeAnswers, ['Yes','Somewhat','Not really','Not sure yet','Probably yes','Probably not','Mostly who they are now','Both','Mostly who I hope they become','Often','Sometimes','Rarely','A little','No','Maybe','Mostly losing this person','Mostly losing company or the feeling of being cared about']),
  entries('clear.like.option.', likeOptions, ['Losing this person','Losing daily companionship','Losing the feeling of being cared about','Being alone again','Feeling that my investment was wasted','Not accepting that it ended without a result','I do not know yet','Other']),
  entries('clear.like.module.', ['real_person.title','real_person.body','habit.title','habit.body','fear_of_loss.title','fear_of_loss.body','imagined_relationship.title','imagined_relationship.body'], ['I like the person I actually know','Part of what you notice is this person as they really are now.','Their presence has become part of my routine','Regular interactions can also become part of what is hard to let go of.','Fear of loss has a place here too','Fear of loss can sometimes make a feeling harder to release.','Some expectations may be ahead of reality','Some hopes may already be ahead of what has actually happened.']),
)

const brainCopy = [
  'Your mind may keep trying to solve everything. Ask yourself: is there any new information right now?',
  'You may be waiting for a reassuring signal. Put the phone away briefly and finish one thing for yourself.',
  'When the answer is unclear, you may fill in the blanks. Separate what you know from what you are guessing.',
  'You may be seeking certainty through more information. Before checking again, ask whether anything is actually new.',
  'You may care deeply about the relationship and place your needs last. Before agreeing, ask what you want too.',
]
Object.assign(en, entries('clear.brain.copy.', patterns, brainCopy), entries('clear.brain.copy.', patterns.map((key) => key + '.v1'), brainCopy), {
  'clear.brain.copy.low_overall.v1':'Relationships can still matter to you, but these thoughts and behaviors do not currently occupy your life very often. You can like someone while keeping plenty of attention for yourself.',
  'clear.brain.copy.tie.v1':'More than one pattern is equally noticeable right now. They can appear together; the full data remains recorded, and you do not need to force a single label.',
})

Object.assign(en, entries('clear.like.', seq('q', 12), likeQuestions.map((key) => en['clear.like.q.' + key])))
Object.assign(en, boatResultBodies(
  ['Your attention is still largely with your own life.','Your feelings are beginning to move closer.','You have invested a great deal of attention and hope.','This relationship is taking up a very large share of your energy.'],
  ['There are few concrete responses so far.','There are some responses, but several things remain unclear.','You can see many concrete responses.','The interaction appears mostly mutual so far.'],
  ['Let time and visible actions bring more information.','You can stay open to your feelings while keeping your own pace.','Keep looking at actions and making room for your own life.'],
))

Object.assign(en, likeResults(
  ['Some of your feelings are clearly about who this person really is.','Their presence has become part of your routine.','Fear of loss may need the most attention right now.','Some expectations seem to be ahead of reality.','Your feelings seem to include both liking and habit.','You may genuinely like them and also fear losing them.','You may genuinely like them while carrying hopes about the future.','Part of what is hard to release may be habit and fear of loss.','Habit may have become linked with hopes for the future.','Some hopes may also be linked with fear of loss.','Your feelings may include liking, habit, and some fear of loss.','You may like who they are, be used to their presence, and hold hopes for the future.','You may like them and fear losing them, making the future feel especially important.','What is hard to release may include habit, fear of loss, and future hopes.','You do not need to decide what this feeling means yet.'],
  ['You notice real interactions and qualities you appreciate now, not only who you hope they may become.','Missing regular messages, company, or a familiar rhythm is understandable. Notice what remains after the routine changes.','Fear of loss does not mean you do not like them. When fear grows large, your own feelings can become harder to hear.','Hoping for a future is natural. Put what has not happened back in the unknown so you can see what exists now.','You may appreciate this person and also be used to their presence. Both can be true without cancelling each other.','Liking someone and fearing loss can coexist. Notice if fear makes it hard to acknowledge discomfort.','Some hopes may be a step ahead of the relationship. Separate what happened from what you hope will happen.','When someone becomes part of everyday life, their absence can feel unsettling. This gives you another part to notice.','Regular interaction can link familiar feelings with hopes for what comes next. Separating them can make the present clearer.','When you hope for an outcome, imagined futures can gain extra weight. Put what has not happened back in the unknown.','You may like this person, be used to their presence, and find loss more painful because of both. These parts do not cancel one another.','All three can be present. Separate what has happened from what you hope for rather than choosing which is real.','Liking and fear of loss can make the outcome feel urgent. Return attention to the interaction that exists now.','When someone shapes your routine and carries many hopes, letting go can feel difficult. There is more than one part to notice.','Some feelings take time to separate. Not knowing yet does not mean you must force an answer between liking and habit.'],
  ['Without any guarantee of a relationship outcome, do I still like this person as they are now?','If I build a new rhythm in my life, how would I think about this person?','If I knew this could not reduce my worth, how would I see the relationship now?','If I only look at what has happened, how would I describe us now?','Without regular daily interaction, would I still like this person as they are now?','If I did not need to fear loss, how would I view our current interactions?','If I only look at what is actually happening now, do I still like this way of relating?','Am I most afraid of losing this person, or the feeling I had every day?','If the future does not unfold as imagined, would I still want this interaction now?','If I stop filling in the future, what do I actually know now?','Without habit or fear of loss, how would I see this person now?','If the future stayed like the present, would I still like this way of relating?','Without a guarantee about the future, would I still choose to like this real person?','Without habit, fear, and future imagination, what real feelings for this person remain?','Without expecting them to change or fearing loss, do I still want to move closer to this person?'],
))

export const clearMilestone4MessagesEn = defineClearLocale('en', en)
