import { adaptClearLocale } from './clearLocaleAdapt'
import { boatResultBodies, entries, likeResults } from './clearLocaleFactory'
const seq=(p:string,n:number)=>Array.from({length:n},(_,i)=>p+String(i+1).padStart(2,'0'))
const patterns=['rumination','message_dependency','over_interpretation','detective','self_sacrifice'] as const
const likeQ=['real_person_three_real_traits','real_person_without_romantic_expectation','real_person_present_vs_future_version','habit_expect_regular_contact','habit_absence_feels_like_missing_routine','habit_missing_the_routine','fear_of_loss_hardest_part','fear_of_loss_person_vs_feeling','fear_of_loss_avoiding_discomfort','imagined_relationship_future_more_than_reality','imagined_relationship_future_fills_present_gap','imagined_relationship_reality_description'] as const
const es:Record<string,string>={
'clear.home':'Volver a Claridad','clear.empty':'Aún no hay reflexiones. Empieza con la herramienta que mejor encaje con este momento.','clear.history.title':'Reflexiones recientes','clear.history.view':'Ver resultado','clear.history.delete':'Eliminar registro','clear.history.deleteTitle':'¿Eliminar esta reflexión?','clear.history.deleteBody':'No se puede deshacer. Los puntos de corazón estelar ya obtenidos se conservarán.','clear.history.deleteWithStar':'Este registro ya tiene una estrella de claridad. Al confirmar, solo se elimina el registro y se conserva la estrella.','clear.history.deleteStarToo':'Eliminar también esta estrella de claridad','clear.history.clearRecord':'Ordenar mis emociones','clear.history.loveBoat':'Guía de ilusión','clear.history.loveBrain':'Revisión de patrones afectivos','clear.history.likeOrHabit':'¿Me gusta o es costumbre?',
'clear.common.previous':'Anterior','clear.common.next':'Siguiente','clear.common.continueLater':'Continuar después','clear.common.continue':'Retomar','clear.common.draftProgress':'Retomar · {current} / {total}','clear.common.restart':'Empezar de nuevo','clear.common.restartTitle':'¿Empezar de nuevo?','clear.common.restartBody':'Se borrarán las respuestas sin completar.','clear.common.progress':'{current} / {total}','clear.common.overview':'Resumen de preguntas','clear.common.saveStar':'Guardar como estrella de claridad','clear.common.savedStar':'Guardado como estrella de claridad','clear.common.finishAndReturn':'Terminar y volver al inicio','clear.common.savedDraft':'Tus respuestas se guardan en este dispositivo mientras avanzas.','clear.common.error':'No se puede guardar ahora. Revisa los campos obligatorios e inténtalo de nuevo.','clear.common.result':'Tu resultado',
'clear.star.clear_record':'Ordené mis emociones y me cuidé en este momento.','clear.star.love_boat_code':'Observé cuánto había invertido y qué estaba ocurriendo realmente.','clear.star.love_brain_assessment':'Reconocí los patrones que últimamente me afectan con más facilidad.','clear.star.like_or_habit':'Separé poco a poco el gusto, la costumbre, el miedo a perder y las expectativas.',
'clear.organize.intro':'Separa poco a poco lo que ocurrió, lo que piensas, lo que sientes y tu próximo paso.','clear.organize.step1':'¿Qué ocurrió?','clear.organize.step1Help':'Elige una situación o escribe algo; al menos una opción es obligatoria.','clear.organize.triggerText':'Si quieres, anota brevemente lo que acaba de pasar.','clear.organize.step2':'Separar cada parte','clear.organize.facts':'Lo que sé con certeza','clear.organize.factsPlaceholder':'Ejemplo: envié un mensaje anoche y todavía no ha respondido.','clear.organize.interpretation':'Lo que mi mente está pensando','clear.organize.interpretationPlaceholder':'Ejemplo: ¿ya no quiere hablar conmigo?','clear.organize.unknown':'Lo que todavía no sé','clear.organize.unknownPlaceholder':'Ejemplo: por qué todavía no ha respondido.','clear.organize.step3':'¿Qué siento ahora?','clear.organize.intensity':'¿Qué intensidad tiene esta emoción ahora?','clear.organize.body':'¿Qué notas en el cuerpo? (opcional)','clear.organize.step4':'No adivinar aún lo que siente','clear.organize.step4Help':'Son interacciones que has observado hasta ahora; puedes omitirlo.','clear.organize.step5':'¿Qué necesito de verdad ahora?','clear.organize.needs':'Lo que necesito','clear.organize.action':'¿Qué puedo hacer ahora por mí?','clear.organize.customAction':'Escribir mi propio siguiente paso','clear.organize.step6':'¿Qué he visto esta vez?','clear.organize.finish':'Terminar esta reflexión','clear.organize.closing':'No necesitas saber ahora mismo la respuesta sobre esta relación. Empieza por cuidarte en este momento.','clear.organize.completed':'Reflexión completada. Corazón estelar +5.','clear.organize.answer.yes':'Sí','clear.organize.answer.no':'No','clear.organize.answer.unknown':'Aún no lo sé',
'clear.boat.intro':'No mide cuánto amas a alguien. Compara hasta dónde han avanzado tus sentimientos con lo que realmente ha ocurrido.','clear.boat.start':'Explorar','clear.boat.sectionA':'A | ¿Cuánto me he implicado?','clear.boat.sectionB':'B | ¿Cómo responde realmente?','clear.boat.unknownHelp':'«Aún no lo sé» no es una respuesta negativa y no entra en la proporción de respuestas.','clear.boat.answer.0':'Casi nunca','clear.boat.answer.1':'De vez en cuando','clear.boat.answer.2':'A veces','clear.boat.answer.3':'A menudo','clear.boat.response.2':'Sí','clear.boat.response.1':'A veces','clear.boat.response.0':'No','clear.boat.response.unknown':'Aún no lo sé','clear.boat.finish':'Terminar esta guía','clear.boat.completed':'Esta guía ya está en tu historial.','clear.boat.scoreA':'Mi implicación: {score} / 36','clear.boat.result.insufficient':'Todavía hay poca interacción observable. No hace falta definir la relación ahora.','clear.boat.result.body':'No te apresures a adivinar lo que siente ni a culparte por sentir interés. Compara tu implicación con lo que ocurre de verdad.',
'clear.brain.intro':'No mide si tienes «cerebro enamorado». Ayuda a ver dónde puedes perderte de vista cuando alguien te gusta mucho.','clear.brain.duration':'25 preguntas | unos 4–5 minutos','clear.brain.start':'Explorar','clear.brain.finish':'Terminar esta revisión','clear.brain.completed':'Esta revisión ya está en tu historial.','clear.brain.low':'Sigues conservando tu propio ritmo','clear.brain.resultIntro':'Últimamente, aquí es donde te afecta con más facilidad','clear.brain.primary':'Patrón más visible ahora','clear.brain.secondary':'También aparece a menudo','clear.brain.tie':'Estos patrones se ven igual de presentes ahora',
'clear.like.intro':'¿Qué me cuesta soltar de verdad: esta persona o lo que me hace sentir esta relación?','clear.like.start':'Mirarlo con calma','clear.like.section.real_person':'¿Me gusta la persona real?','clear.like.section.habit':'¿Me he acostumbrado a su presencia?','clear.like.section.fear_of_loss':'¿Tengo miedo de perder esta relación?','clear.like.section.imagined_relationship':'¿Me gusta la realidad o lo que imagino?','clear.like.prompt.real_person':'Lo que aprecio de esta persona…','clear.like.prompt.habit':'A lo que más me he acostumbrado…','clear.like.prompt.fear_of_loss':'Si esta relación no continuara, lo más difícil sería…','clear.like.prompt.imagined_relationship':'Si solo miro lo que ha ocurrido, describiría esta relación como…','clear.like.other':'Algo más que quiera añadir','clear.like.preview':'Ver el resultado','clear.like.finish':'Terminar esta reflexión','clear.like.completed':'Esta reflexión ya está en tu historial.','clear.like.validation':'Completa las opciones obligatorias de las cuatro tarjetas. Si eliges «Otro», añade también el contenido.','clear.like.closing':'No hace falta nombrar lo que sientes todavía. Primero distingue qué te cuesta soltar.',
}
Object.assign(es,
entries('clear.organize.body.',['chest_tight','heart_racing','stomach_uncomfortable','restless','tired','sleepless','want_to_cry','none','other'],['Opresión en el pecho','Corazón acelerado','Malestar de estómago','Inquietud','Mucho cansancio','No puedo dormir','Ganas de llorar','Sin sensación clara','Otro']),
entries('clear.organize.trigger.',['no_reply','attitude_changed','social_media','argument','missing_them','waiting_response','overthinking','other'],['No ha respondido','Su actitud parece distinta','Vi sus redes o novedades','Tuvimos un momento desagradable','De pronto le echo mucho de menos','Espero su respuesta','Empecé a darle demasiadas vueltas','Otro']),
entries('clear.organize.emotion.',['missing','anxious','sad','hurt','angry','jealous','afraid','lost','confused','hopeful'],['Añoranza','Inquietud','Tristeza','Dolor','Enfado','Celos','Miedo','Decepción','Confusión','Esperanza']),
entries('clear.organize.observation.',['initiates_contact','makes_time','keeps_promises','listens','mutual_effort','words_match_actions'],['También inicia el contacto','Busca tiempo para estar conmigo','Suele cumplir lo que promete','Escucha cuando expreso lo que siento','No soy quien siempre hace todo el esfuerzo','Sus palabras y acciones suelen coincidir']),
entries('clear.organize.need.',['reassurance','understanding','respect','company','space','clarity','boundaries','rest','return_to_life','unknown'],['Tranquilidad','Sentirme comprendido/a','Respeto','Compañía','Un poco de espacio propio','Claridad','Reconocer mis límites','Descansar','Volver a centrarme en mi vida','Aún no lo sé']),
entries('clear.organize.action.',['put_phone_down','stop_checking_social','shower_or_rest','take_a_walk','continue_own_plan','talk_to_trusted_person','reply_when_calm','decide_tomorrow','write_diary','custom'],['Dejar el teléfono un rato','No mirar sus redes por ahora','Ducharme o descansar','Dar un paseo','Seguir con mi plan','Hablar con alguien de confianza','Responder cuando esté en calma','Decidir mañana','Escribir en el diario de hoy','Escribir mi propia acción']),
entries('clear.boat.q.',seq('a',12),['Compruebo repetidamente si respondió a mi mensaje.','Si tarda mucho en responder, me cuesta concentrarme en lo mío.','Cuando responde, mi ánimo mejora mucho de inmediato.','Repaso a menudo nuestras conversaciones o momentos compartidos.','Intento adivinar qué significa una palabra, un emoji o el visto.','No puedo evitar mirar sus redes, novedades o estado en línea.','Busco confirmar si le importo o si le gusto.','Si se muestra algo distante, pienso enseguida que hice algo mal.','He aplazado mis planes mientras esperaba su respuesta.','Aunque la interacción aún no haya avanzado, imagino un futuro lejano.','Aunque no ocurra nada nuevo, sigo pensando en esa persona.','Últimamente, esta persona o relación ocupa mucha atención y emoción.']),
entries('clear.boat.q.',seq('b',10),['También inicia el contacto; no espera siempre a que lo haga yo.','Busca tiempo para estar conmigo.','Suele cumplir lo que promete.','Escucha cuando expreso mis sentimientos o ideas.','Recuerda cosas importantes que le he contado.','Cuando hay que hablar, no suele desaparecer sin explicación.','Sus acciones coinciden en general con sus palabras.','No soy la única persona que mantiene esta interacción.','Sé más o menos qué lugar ocupo ahora.','Al interactuar, no necesito adivinar continuamente qué quiere decir.']),
entries('clear.brain.pattern.',patterns,['Patrón de pensamientos repetitivos','Patrón dependiente de mensajes','Patrón de interpretación excesiva','Patrón de búsqueda de pistas','Patrón de sacrificio propio']),
entries('clear.brain.q.',patterns.flatMap((p)=>seq(p+'_',5)),['Tras una conversación, repaso varias veces lo que dijimos.','Si algo sale un poco mal, sigo pensando si hice algo incorrecto.','Aunque ya pasó, vuelvo a la escena o a la emoción.','Sé que pensar más no dará una respuesta, pero me cuesta parar.','Mientras hago otras cosas, mi mente vuelve a esta relación.','Miro repetidamente si hay un mensaje suyo sin darme cuenta.','Si tarda en responder, mi ánimo se ve afectado.','Un mensaje o aviso suyo puede cambiar mucho mi emoción.','Esperar su mensaje me dificulta concentrarme en lo que hacía.','Me fijo mucho en cambios de rapidez, longitud o tono.','Puedo pensar mucho si una frase normal tenía otro significado.','Analizo sus emojis, tono o finales de frase.','Si se muestra distante, empiezo a imaginar qué ocurrió.','A partir de una interacción pequeña imagino muchas posibilidades.','Sin pruebas claras, imagino qué puede significar una conducta.','Miro sus redes para saber qué hace últimamente.','A veces observo cuándo está en línea y con quién interactúa.','Si algo parece raro, busco más pistas.','He visto más contenido del que pensaba para entender su situación.','Aunque no haya nada nuevo, vuelvo a mirar sus novedades.','He cambiado mis planes para adaptarme.','Aunque no me apetezca o me incomode, a veces priorizo lo que necesita.','Temo que rechazar o discrepar haga que se aleje.','A veces pongo su estado de ánimo antes que el mío.','He callado cosas que quería decir para mantener la relación.']),
entries('clear.like.q.',likeQ,['¿Puedo nombrar al menos tres cosas reales que aprecio, no imaginadas?','Sin ambigüedad romántica ni expectativa de salir, ¿seguiría disfrutando de su compañía?','¿Me gusta cómo es ahora o cómo espero que llegue a ser?','¿Espero un mensaje o interacción fija cada día?','Sin sus mensajes o presencia, ¿sentiría que falta una parte de mi rutina?','¿Una parte de lo que echo de menos es la sensación cotidiana que tenía?','Si la relación no continuara, ¿qué sería lo más difícil?','¿Costaría más perder a esta persona o perder la compañía y sentir que le importo a alguien?','¿Evito admitir incomodidades por miedo a perder la relación?','¿Paso más tiempo imaginando el futuro que compartiendo el presente?','¿Uso «quizá algún día» para llenar lo que hoy no existe?','Si solo miro lo ocurrido y no mis expectativas, ¿cómo describo la relación?']),
entries('clear.like.answer.',['yes','some','not_really','not_sure','probably_yes','probably_no','mostly_present','both','mostly_future','often','sometimes','rarely','somewhat','no','maybe','mostly_person','mostly_feeling'],['Sí','En parte','No mucho','Aún no lo sé','Probablemente sí','Probablemente no','Sobre todo cómo es ahora','Ambas cosas','Sobre todo cómo espero que sea','A menudo','A veces','Rara vez','Un poco','No','Quizá','Sobre todo perder a esta persona','Sobre todo perder la compañía o sentir que le importo a alguien'])
)
const copy=['Tu mente puede intentar resolverlo todo. Pregúntate si ahora hay información nueva.','Quizá esperas una señal que te tranquilice. Aleja el teléfono un momento y termina algo tuyo.','Cuando la respuesta no está clara, puedes llenar los huecos. Separa lo que sabes de lo que imaginas.','Quizá buscas seguridad reuniendo más información. Antes de volver a mirar, comprueba si hay algo nuevo.','Tal vez la relación te importa tanto que dejas tus necesidades al final. Antes de aceptar, pregúntate también qué quieres.']
Object.assign(es,entries('clear.brain.copy.',patterns,copy),entries('clear.brain.copy.',patterns.map((p)=>p+'.v1'),copy),{'clear.brain.copy.low_overall.v1':'La relación puede importarte, pero estos pensamientos y conductas no parecen ocupar tu vida con demasiada frecuencia. Puedes sentir interés por alguien y seguir reservando atención para ti.','clear.brain.copy.tie.v1':'Hay varios patrones igual de visibles. Pueden aparecer juntos; los datos se conservan completos y no necesitas elegir uno a la fuerza.'})
Object.assign(es,entries('clear.like.',seq('q',12),likeQ.map((k)=>es['clear.like.q.'+k])))
Object.assign(es,boatResultBodies(['Tu atención sigue estando en gran parte en tu propia vida.','Tus sentimientos empiezan a acercarse.','Has invertido mucha atención y expectativa.','Esta relación ocupa una parte muy grande de tu energía.'],['Por ahora hay pocas respuestas concretas.','Hay algunas respuestas y también incertidumbre.','Puedes ver bastantes respuestas concretas.','La interacción parece bastante recíproca.'],['Deja que el tiempo y las acciones visibles aporten información.','Puedes reconocer lo que sientes y conservar tu ritmo.','Sigue mirando las acciones y reserva espacio para tu propia vida.']))
const names=['interés por la persona real','costumbre','miedo a perder','expectativas de futuro'];const combos=[[0],[1],[2],[3],[0,1],[0,2],[0,3],[1,2],[1,3],[2,3],[0,1,2],[0,1,3],[0,2,3],[1,2,3],[]]
Object.assign(es,likeResults(combos.map((c)=>c.length?'En lo que sientes aparecen '+c.map((i)=>names[i]).join(', ')+'.':'No necesitas decidir todavía qué significa lo que sientes.'),combos.map((c)=>c.length?'Estas partes pueden coexistir. Sin negar ninguna, separa poco a poco lo que ocurrió de lo que esperas.':'Algunas emociones necesitan tiempo para aclararse. Lo que aún no sabes puede quedarse sin respuesta por ahora.'),combos.map(()=>'Si aparto por un momento las expectativas y el miedo, ¿qué siento por esta persona y esta relación ahora?')))
Object.assign(es,
 entries('clear.boat.level.',['investment_low','investment_mild','investment_high','investment_very_high','response_insufficient_observation','response_low','response_mixed','response_good','response_high'],['Mi atención sigue conmigo','Empiezo a sentirme afectado/a','Mi atención gira a menudo alrededor de esa persona','Esta relación ocupa mucha energía últimamente','Necesito más tiempo para observar','Hay pocas respuestas visibles','Hay respuestas y también incertidumbre','Veo bastantes respuestas concretas','La interacción es bastante recíproca']),
 entries('clear.boat.result.',['low_low','low_mixed','low_good','low_high','mild_low','mild_mixed','mild_good','mild_high','high_low','high_mixed','high_good','high_high','very_high_low','very_high_mixed','very_high_good','very_high_high'],['Todavía observando','Acercamiento gradual','Respuestas y espacio propio','Acercamiento con calma','Mis sentimientos avanzan más rápido','La ambigüedad me mueve','Sentimientos con respuestas reales','Ambas partes se acercan','Mis sentimientos van por delante','Mi implicación va por delante de las respuestas','Interés profundo con respuestas','Mucha ilusión sin olvidarme','Mis sentimientos van delante de la relación','Mucha implicación, respuestas pendientes','Muchas respuestas, mente muy ocupada','Reciprocidad con espacio para mí']),
 entries('clear.boat.insufficientTitle.',['investment_low','investment_mild','investment_high','investment_very_high'],['No hace falta definirlo todavía','Mis sentimientos se acercan, pero hay poca información','Mis sentimientos están cerca; que la realidad alcance','Muchos pensamientos y aún poca información']),
 entries('clear.like.option.',['lose_this_person','lose_daily_companionship','lose_feeling_cared_for','be_alone','investment_feels_wasted','no_result','uncertainty','other'],['Perder a esta persona','Perder la compañía cotidiana','Perder la sensación de importarle a alguien','Volver a estar solo/a','Sentir que mi inversión fue en vano','No aceptar que terminó sin resultado','Aún no lo sé','Otro']),
 entries('clear.like.module.',['real_person.title','real_person.body','habit.title','habit.body','fear_of_loss.title','fear_of_loss.body','imagined_relationship.title','imagined_relationship.body'],['Me gusta la persona que conozco de verdad','Parte de lo que ves pertenece a quien esta persona es ahora.','Su presencia forma parte de mi rutina','Las interacciones regulares también pueden ser difíciles de soltar.','El miedo a perder también ocupa un lugar','El miedo a perder puede hacer que un sentimiento cueste más soltarlo.','Algunas expectativas pueden ir delante de la realidad','Algunas esperanzas pueden haber avanzado más que lo que ha ocurrido.'])
)
export const clearMilestone4MessagesEs=adaptClearLocale('es',es)
