import { adaptClearLocale } from './clearLocaleAdapt'
import { boatResultBodies, entries, likeResults } from './clearLocaleFactory'
const seq=(p:string,n:number)=>Array.from({length:n},(_,i)=>p+String(i+1).padStart(2,'0'))
const patterns=['rumination','message_dependency','over_interpretation','detective','self_sacrifice'] as const
const likeQ=['real_person_three_real_traits','real_person_without_romantic_expectation','real_person_present_vs_future_version','habit_expect_regular_contact','habit_absence_feels_like_missing_routine','habit_missing_the_routine','fear_of_loss_hardest_part','fear_of_loss_person_vs_feeling','fear_of_loss_avoiding_discomfort','imagined_relationship_future_more_than_reality','imagined_relationship_future_fills_present_gap','imagined_relationship_reality_description'] as const
const fr:Record<string,string>={
'clear.home':'Retour à Clarté','clear.empty':'Aucune réflexion pour le moment. Commencez par l’outil adapté à cet instant.','clear.history.title':'Réflexions récentes','clear.history.view':'Voir le résultat','clear.history.delete':'Supprimer','clear.history.deleteTitle':'Supprimer cette réflexion ?','clear.history.deleteBody':'Cette action est irréversible. Les points Cœur étoilé déjà obtenus restent acquis.','clear.history.deleteWithStar':'Ce résultat possède déjà une étoile de clarté. La confirmation supprime seulement le résultat et conserve l’étoile.','clear.history.deleteStarToo':'Supprimer aussi cette étoile de clarté','clear.history.clearRecord':'Trier mes émotions','clear.history.loveBoat':'Guide de l’emballement','clear.history.loveBrain':'Bilan des schémas affectifs','clear.history.likeOrHabit':'Attirance ou habitude ?',
'clear.common.previous':'Précédent','clear.common.next':'Suivant','clear.common.continueLater':'Continuer plus tard','clear.common.continue':'Reprendre','clear.common.draftProgress':'Reprendre · {current} / {total}','clear.common.restart':'Recommencer','clear.common.restartTitle':'Recommencer ?','clear.common.restartBody':'Les réponses inachevées seront effacées.','clear.common.progress':'{current} / {total}','clear.common.overview':'Vue d’ensemble','clear.common.saveStar':'Enregistrer comme étoile de clarté','clear.common.savedStar':'Étoile de clarté enregistrée','clear.common.finishAndReturn':'Terminer et revenir à l’accueil','clear.common.savedDraft':'Vos réponses sont enregistrées sur cet appareil au fur et à mesure.','clear.common.error':'Enregistrement impossible. Vérifiez les champs obligatoires et réessayez.','clear.common.result':'Votre résultat',
'clear.star.clear_record':'J’ai trié mes émotions et pris soin de moi dans cet instant.','clear.star.love_boat_code':'J’ai observé mon investissement et ce qui se passait réellement.','clear.star.love_brain_assessment':'J’ai repéré les schémas qui me touchent plus facilement ces derniers temps.','clear.star.like_or_habit':'J’ai distingué peu à peu attirance, habitude, peur de perdre et attentes.',
'clear.organize.intro':'Séparez doucement ce qui s’est passé, vos pensées, vos émotions et la prochaine étape.','clear.organize.step1':'Que s’est-il passé ?','clear.organize.step1Help':'Choisissez une situation ou écrivez quelque chose ; au moins un des deux est requis.','clear.organize.triggerText':'Si vous le souhaitez, notez brièvement ce qui vient de se passer.','clear.organize.step2':'Séparer les éléments','clear.organize.facts':'Ce que je sais avec certitude','clear.organize.factsPlaceholder':'Exemple : j’ai envoyé un message hier soir et je n’ai pas encore reçu de réponse.','clear.organize.interpretation':'Ce que mon esprit me raconte','clear.organize.interpretationPlaceholder':'Exemple : peut-être que cette personne ne veut plus me parler ?','clear.organize.unknown':'Ce que je ne sais pas encore','clear.organize.unknownPlaceholder':'Exemple : pourquoi je n’ai pas encore reçu de réponse.','clear.organize.step3':'Que ressens-je maintenant ?','clear.organize.intensity':'Quelle est l’intensité de cette émotion ?','clear.organize.body':'Que ressentez-vous dans votre corps ? (facultatif)','clear.organize.step4':'Ne pas deviner ses sentiments','clear.organize.step4Help':'Voici les interactions observées jusqu’ici ; vous pouvez passer cette étape.','clear.organize.step5':'De quoi ai-je vraiment besoin maintenant ?','clear.organize.needs':'Ce dont j’ai besoin','clear.organize.action':'Que puis-je faire pour moi maintenant ?','clear.organize.customAction':'Écrire ma propre prochaine étape','clear.organize.step6':'Qu’ai-je remarqué cette fois ?','clear.organize.finish':'Terminer cette réflexion','clear.organize.closing':'Vous n’avez pas besoin de connaître tout de suite la réponse sur cette relation. Commencez par prendre soin de vous maintenant.','clear.organize.completed':'Réflexion terminée. Cœur étoilé +5.','clear.organize.answer.yes':'Oui','clear.organize.answer.no':'Non','clear.organize.answer.unknown':'Je ne sais pas encore',
'clear.boat.intro':'Il ne s’agit pas de mesurer combien vous aimez quelqu’un, mais de comparer l’avancée de vos sentiments à ce qui s’est réellement passé.','clear.boat.start':'Explorer','clear.boat.sectionA':'A | Jusqu’où suis-je investi·e ?','clear.boat.sectionB':'B | Comment cette personne répond-elle concrètement ?','clear.boat.unknownHelp':'« Je ne sais pas encore » n’est pas une réponse négative et n’entre pas dans le ratio.','clear.boat.answer.0':'Presque jamais','clear.boat.answer.1':'Rarement','clear.boat.answer.2':'Parfois','clear.boat.answer.3':'Souvent','clear.boat.response.2':'Oui','clear.boat.response.1':'Parfois','clear.boat.response.0':'Non','clear.boat.response.unknown':'Je ne sais pas encore','clear.boat.finish':'Terminer ce guide','clear.boat.completed':'Ce guide figure maintenant dans votre historique.','clear.boat.scoreA':'Mon investissement : {score} / 36','clear.boat.result.insufficient':'Il y a encore peu d’interactions observables. Inutile de définir la relation maintenant.','clear.boat.result.body':'Ne vous pressez pas de deviner ses sentiments ni de vous reprocher votre attirance. Comparez votre investissement à ce qui se passe réellement.',
'clear.brain.intro':'Ce bilan ne mesure pas si vous êtes « accro à l’amour ». Il aide à voir où vous risquez de vous oublier quand quelqu’un vous plaît beaucoup.','clear.brain.duration':'25 questions | environ 4 à 5 minutes','clear.brain.start':'Explorer','clear.brain.finish':'Terminer ce bilan','clear.brain.completed':'Ce bilan figure maintenant dans votre historique.','clear.brain.low':'Vous conservez votre propre rythme','clear.brain.resultIntro':'Dernièrement, voici ce qui vous touche le plus facilement','clear.brain.primary':'Schéma le plus visible actuellement','clear.brain.secondary':'Également fréquent','clear.brain.tie':'Ces schémas sont aussi visibles les uns que les autres',
'clear.like.intro':'Qu’est-ce qui est vraiment difficile à lâcher : cette personne ou ce que cette relation me fait ressentir ?','clear.like.start':'Prendre le temps de regarder','clear.like.section.real_person':'Cette personne réelle me plaît-elle ?','clear.like.section.habit':'Suis-je habitué·e à sa présence ?','clear.like.section.fear_of_loss':'Ai-je peur de perdre cette relation ?','clear.like.section.imagined_relationship':'Ce qui me plaît est-il réel ou imaginé ?','clear.like.prompt.real_person':'Ce que j’apprécie chez cette personne…','clear.like.prompt.habit':'Ce à quoi je suis le plus habitué·e…','clear.like.prompt.fear_of_loss':'Si cette relation ne continuait pas, le plus difficile serait…','clear.like.prompt.imagined_relationship':'Si je regarde seulement ce qui s’est passé, je décrirais cette relation ainsi…','clear.like.other':'Autre chose à ajouter','clear.like.preview':'Voir le résultat','clear.like.finish':'Terminer cette réflexion','clear.like.completed':'Cette réflexion figure maintenant dans votre historique.','clear.like.validation':'Complétez les choix obligatoires des quatre cartes. Si vous choisissez « Autre », précisez aussi votre réponse.','clear.like.closing':'Inutile de nommer ce sentiment tout de suite. Commencez par distinguer ce qui est difficile à lâcher.',
}
Object.assign(fr,
entries('clear.organize.body.',['chest_tight','heart_racing','stomach_uncomfortable','restless','tired','sleepless','want_to_cry','none','other'],['Poitrine serrée','Cœur qui bat vite','Malaise à l’estomac','Agitation','Grande fatigue','Impossible de dormir','Envie de pleurer','Aucune sensation nette','Autre']),
entries('clear.organize.trigger.',['no_reply','attitude_changed','social_media','argument','missing_them','waiting_response','overthinking','other'],['Pas de réponse','Son attitude semble différente','J’ai vu ses réseaux ou publications','Nous avons eu un échange désagréable','Cette personne me manque soudain beaucoup','J’attends sa réponse','Je me mets à trop réfléchir','Autre']),
entries('clear.organize.emotion.',['missing','anxious','sad','hurt','angry','jealous','afraid','lost','confused','hopeful'],['Manque','Inquiétude','Tristesse','Blessure','Colère','Jalousie','Peur','Déception','Confusion','Espoir']),
entries('clear.organize.observation.',['initiates_contact','makes_time','keeps_promises','listens','mutual_effort','words_match_actions'],['Cette personne prend aussi contact','Elle trouve du temps pour moi','Elle tient généralement ses promesses','Elle m’écoute quand j’exprime mes émotions','Je ne suis pas toujours la seule personne à faire des efforts','Ses paroles et ses actes concordent globalement']),
entries('clear.organize.need.',['reassurance','understanding','respect','company','space','clarity','boundaries','rest','return_to_life','unknown'],['Être rassuré·e','Être compris·e','Respect','Présence','Un peu d’espace pour moi','Clarté','Reconnaître mes limites','Repos','Ramener mon attention à ma vie','Je ne sais pas encore']),
entries('clear.organize.action.',['put_phone_down','stop_checking_social','shower_or_rest','take_a_walk','continue_own_plan','talk_to_trusted_person','reply_when_calm','decide_tomorrow','write_diary','custom'],['Poser mon téléphone un moment','Ne plus consulter ses publications pour l’instant','Prendre une douche ou me reposer','Faire une promenade','Continuer ce que j’avais prévu','Parler à une personne de confiance','Répondre une fois apaisé·e','Décider demain','Écrire dans le journal du jour','Écrire ma propre action']),
entries('clear.boat.q.',seq('a',12),['Je vérifie plusieurs fois si cette personne a répondu.','Sans réponse pendant longtemps, j’ai du mal à me concentrer sur mes activités.','Quand elle répond, mon humeur s’améliore immédiatement.','Je repasse souvent nos conversations ou nos moments ensemble.','J’essaie de deviner le sens d’un mot, d’un emoji ou d’un message lu.','Je ne peux pas m’empêcher de consulter ses réseaux, publications ou statut en ligne.','Je cherche à savoir si je compte ou si je lui plais.','Si cette personne devient un peu distante, je pense avoir fait quelque chose de mal.','J’ai déjà reporté mes projets en attendant une réponse.','Alors que la relation est encore peu avancée, j’imagine souvent un futur lointain.','Même sans nouvel événement, cette personne reste dans mes pensées.','Dernièrement, cette personne ou cette relation occupe beaucoup mon attention et mes émotions.']),
entries('clear.boat.q.',seq('b',10),['Cette personne prend aussi contact au lieu d’attendre toujours que je le fasse.','Elle trouve du temps pour être avec moi.','Elle tient généralement ses promesses.','Elle m’écoute quand j’exprime mes émotions ou idées.','Elle se souvient des choses importantes que je lui ai dites.','Quand il faut parler, elle ne disparaît généralement pas sans raison.','Ses actes correspondent globalement à ses paroles.','Je ne suis pas la seule personne à entretenir cet échange.','Je sais globalement où j’en suis dans la relation actuelle.','Lors de nos échanges, je n’ai pas à deviner sans cesse ce qu’elle veut dire.']),
entries('clear.brain.pattern.',patterns,['Schéma de pensées en boucle','Schéma de dépendance aux messages','Schéma de surinterprétation','Schéma de recherche d’indices','Schéma de sacrifice de soi']),
entries('clear.brain.q.',patterns.flatMap((p)=>seq(p+'_',5)),['Après une conversation, je repasse plusieurs fois ce que nous avons dit.','Si un échange se passe un peu mal, je me demande longtemps si j’ai fait une erreur.','Même après coup, je repense souvent à la scène ou à l’émotion.','Je sais que réfléchir davantage ne donnera pas de réponse, mais j’ai du mal à arrêter.','Pendant une autre activité, mes pensées reviennent soudain à cette relation.','Je vérifie machinalement et plusieurs fois si cette personne m’a écrit.','Quand la réponse tarde, mon humeur est facilement affectée.','Un message ou une notification de sa part peut changer fortement mon humeur.','Attendre son message m’empêche parfois de me concentrer.','Je remarque particulièrement les changements de vitesse, longueur ou ton des réponses.','Je peux chercher longtemps un autre sens à une phrase ordinaire.','J’analyse ses emojis, son ton ou ses fins de phrase.','Si cette personne semble distante, je commence à imaginer ce qui se passe.','À partir d’un petit échange, j’imagine de nombreuses possibilités.','Sans preuve claire, j’imagine souvent ce qu’un comportement signifie.','Je consulte ses réseaux pour savoir ce qu’elle fait récemment.','Je remarque parfois ses heures de connexion et ses interactions.','Si quelque chose paraît étrange, je cherche davantage d’indices.','Pour comprendre sa situation, j’ai déjà regardé plus de contenu que prévu.','Même sans nouveauté, je consulte parfois encore ses publications.','J’ai déjà modifié mes projets pour m’adapter.','Même mal à l’aise ou sans envie, je fais parfois passer ses besoins avant les miens.','Je crains qu’un refus ou un désaccord éloigne cette personne.','Je fais parfois passer son humeur avant mes propres émotions.','Pour préserver la relation, j’ai déjà retenu des choses que je voulais dire.']),
entries('clear.like.q.',likeQ,['Puis-je nommer au moins trois qualités réelles que j’apprécie, et non imaginées ?','Sans ambiguïté romantique ni espoir de relation, aimerais-je toujours passer du temps avec cette personne ?','Est-ce la personne actuelle qui me plaît, ou celle que j’espère qu’elle deviendra ?','Est-ce que j’attends un message ou un échange régulier chaque jour ?','Sans ses messages ou sa présence, aurais-je l’impression qu’un élément régulier manque ?','Une partie de ce qui me manque est-elle la sensation familière de chaque jour ?','Si cette relation ne continuait pas, qu’est-ce qui serait le plus difficile ?','Serait-il plus difficile de perdre cette personne ou de perdre la présence et le sentiment de compter ?','Ai-je évité d’admettre certains malaises par peur de perdre la relation ?','Est-ce que j’imagine davantage l’avenir que je ne vis de moments réels ?','Est-ce que j’utilise « peut-être plus tard » pour combler ce qui manque maintenant ?','En regardant seulement ce qui s’est passé, sans mes attentes, comment décrirais-je la relation ?']),
entries('clear.like.answer.',['yes','some','not_really','not_sure','probably_yes','probably_no','mostly_present','both','mostly_future','often','sometimes','rarely','somewhat','no','maybe','mostly_person','mostly_feeling'],['Oui','Un peu','Pas vraiment','Je ne sais pas encore','Probablement oui','Probablement non','Surtout la personne actuelle','Les deux','Surtout la personne que j’espère','Souvent','Parfois','Rarement','Un peu','Non','Peut-être','Surtout perdre cette personne','Surtout perdre la présence ou le sentiment de compter'])
)
const copy=['Votre esprit essaie peut-être de tout résoudre. Demandez-vous s’il existe une information nouvelle maintenant.','Vous attendez peut-être un signe rassurant. Éloignez le téléphone un instant et terminez quelque chose pour vous.','Quand la réponse est floue, vous pouvez combler les blancs. Séparez ce que vous savez de ce que vous imaginez.','Vous cherchez peut-être de la certitude avec plus d’informations. Avant de vérifier, demandez-vous s’il y a vraiment du nouveau.','Cette relation compte peut-être beaucoup, au point de reléguer vos besoins. Avant d’accepter, demandez-vous aussi ce que vous voulez.']
Object.assign(fr,entries('clear.brain.copy.',patterns,copy),entries('clear.brain.copy.',patterns.map((p)=>p+'.v1'),copy),{'clear.brain.copy.low_overall.v1':'La relation peut compter pour vous, mais ces pensées et comportements ne semblent pas occuper souvent votre vie actuellement. Quelqu’un peut vous plaire tout en gardant de l’attention pour vous.','clear.brain.copy.tie.v1':'Plusieurs schémas sont également visibles. Ils peuvent apparaître ensemble ; toutes les données restent enregistrées et vous n’avez pas à n’en choisir qu’un.'})
Object.assign(fr,entries('clear.like.',seq('q',12),likeQ.map((k)=>fr['clear.like.q.'+k])))
Object.assign(fr,boatResultBodies(['Votre attention reste largement tournée vers votre propre vie.','Vos sentiments commencent à se rapprocher.','Vous avez investi beaucoup d’attention et d’attentes.','Cette relation occupe une très grande part de votre énergie.'],['Il y a encore peu de réponses concrètes.','Il existe quelques réponses et plusieurs incertitudes.','Vous observez de nombreuses réponses concrètes.','L’interaction semble globalement réciproque.'],['Laissez le temps et les actes visibles apporter plus d’informations.','Vous pouvez accueillir vos sentiments tout en gardant votre rythme.','Continuez à regarder les actes et gardez de la place pour votre vie.']))
const names=['attirance pour la personne réelle','habitude','peur de perdre','attentes pour l’avenir'];const combos=[[0],[1],[2],[3],[0,1],[0,2],[0,3],[1,2],[1,3],[2,3],[0,1,2],[0,1,3],[0,2,3],[1,2,3],[]]
Object.assign(fr,likeResults(combos.map((c)=>c.length?'Vos sentiments montrent '+c.map((i)=>names[i]).join(', ')+'.':'Vous n’avez pas besoin de décider tout de suite ce que signifie ce sentiment.'),combos.map((c)=>c.length?'Ces éléments peuvent coexister. Sans en nier aucun, séparez doucement ce qui s’est passé de ce que vous espérez.':'Certaines émotions demandent du temps pour se clarifier. Ce que vous ignorez peut rester inconnu pour l’instant.'),combos.map(()=>'Si je mets un instant de côté les attentes et la peur, que ressens-je maintenant pour cette personne et cette relation ?')))
Object.assign(fr,
 entries('clear.boat.level.',['investment_low','investment_mild','investment_high','investment_very_high','response_insufficient_observation','response_low','response_mixed','response_good','response_high'],['Mon attention reste avec moi','Je commence à être touché·e','Mon attention revient souvent vers cette personne','Cette relation prend beaucoup d’énergie dernièrement','J’ai besoin de plus de temps pour observer','Il y a peu de réponses visibles','Il y a des réponses et de l’incertitude','Je vois de nombreuses réponses concrètes','L’interaction est globalement réciproque']),
 entries('clear.boat.result.',['low_low','low_mixed','low_good','low_high','mild_low','mild_mixed','mild_good','mild_high','high_low','high_mixed','high_good','high_high','very_high_low','very_high_mixed','very_high_good','very_high_high'],['Encore en observation','Se rapprocher doucement','Des réponses et de l’espace pour moi','Se rapprocher à un rythme stable','Mes sentiments avancent plus vite','L’ambiguïté me fait hésiter','Des sentiments et des réponses concrètes','Les deux se rapprochent','Mes sentiments ont de l’avance','Mon investissement devance les réponses','Une forte attirance avec des réponses','Très touché·e sans m’oublier','Mes sentiments devancent la relation','Très investi·e, réponses encore en retard','Beaucoup de réponses, esprit très occupé','Réciprocité et espace pour moi']),
 entries('clear.boat.insufficientTitle.',['investment_low','investment_mild','investment_high','investment_very_high'],['Inutile de définir maintenant','Mes sentiments se rapprochent, avec peu d’informations','Mes sentiments sont proches ; laissons la réalité suivre','Beaucoup de pensées et encore peu d’informations']),
 entries('clear.like.option.',['lose_this_person','lose_daily_companionship','lose_feeling_cared_for','be_alone','investment_feels_wasted','no_result','uncertainty','other'],['Perdre cette personne','Perdre la présence quotidienne','Perdre le sentiment de compter','Me retrouver seul·e','Avoir l’impression que mon investissement était vain','Ne pas accepter une fin sans résultat','Je ne sais pas encore','Autre']),
 entries('clear.like.module.',['real_person.title','real_person.body','habit.title','habit.body','fear_of_loss.title','fear_of_loss.body','imagined_relationship.title','imagined_relationship.body'],['La personne réelle me plaît','Une partie de ce que vous remarquez appartient à la personne telle qu’elle est maintenant.','Sa présence fait partie de mes habitudes','Les échanges réguliers peuvent aussi devenir difficiles à lâcher.','La peur de perdre a aussi sa place','La peur de perdre peut rendre un sentiment plus difficile à relâcher.','Certaines attentes devancent peut-être la réalité','Certains espoirs ont peut-être avancé au-delà de ce qui s’est réellement passé.'])
)
export const clearMilestone4MessagesFr=adaptClearLocale('fr',fr)
