import { adaptClearLocale } from './clearLocaleAdapt'
import { boatResultBodies, entries, likeResults } from './clearLocaleFactory'

const seq = (prefix: string, count: number) => Array.from({ length: count }, (_, i) => prefix + String(i + 1).padStart(2, '0'))
const patterns = ['rumination','message_dependency','over_interpretation','detective','self_sacrifice'] as const
const likeQuestions = ['real_person_three_real_traits','real_person_without_romantic_expectation','real_person_present_vs_future_version','habit_expect_regular_contact','habit_absence_feels_like_missing_routine','habit_missing_the_routine','fear_of_loss_hardest_part','fear_of_loss_person_vs_feeling','fear_of_loss_avoiding_discomfort','imagined_relationship_future_more_than_reality','imagined_relationship_future_fills_present_gap','imagined_relationship_reality_description'] as const
const ja: Record<string, string> = {
  'clear.home':'気づきのホームへ','clear.empty':'まだ気づきの記録はありません。今の自分に合うツールから始めましょう。','clear.history.title':'最近の気づきの記録','clear.history.view':'結果を見る','clear.history.delete':'記録を削除','clear.history.deleteTitle':'この記録を削除しますか？','clear.history.deleteBody':'削除すると元に戻せません。獲得済みのスターハート値はそのままです。','clear.history.deleteWithStar':'この記録には気づきの星があります。確認すると記録だけを削除し、星は残します。','clear.history.deleteStarToo':'気づきの星も削除する','clear.history.clearRecord':'気持ちを整理する','clear.history.loveBoat':'ときめきガイド','clear.history.loveBrain':'恋愛パターンチェック','clear.history.likeOrHabit':'好き？それとも習慣？',
  'clear.common.previous':'前へ','clear.common.next':'次へ','clear.common.continueLater':'あとで続ける','clear.common.continue':'前回の続き','clear.common.draftProgress':'前回の続き・{current} / {total}','clear.common.restart':'最初から','clear.common.restartTitle':'最初からやり直しますか？','clear.common.restartBody':'未完了の回答は消去されます。','clear.common.progress':'{current} / {total}','clear.common.overview':'質問一覧','clear.common.saveStar':'気づきの星として保存','clear.common.savedStar':'気づきの星に保存済み','clear.common.finishAndReturn':'完了してホームへ','clear.common.savedDraft':'回答はこの端末にその都度保存されています。','clear.common.error':'保存できませんでした。必須項目を確認して、もう一度お試しください。','clear.common.result':'今回の結果',
  'clear.star.clear_record':'気持ちを整理し、今の自分をいたわりました。','clear.star.love_boat_code':'自分の入れ込み具合と、実際のやり取りの両方を見つめました。','clear.star.love_brain_assessment':'最近、自分が影響を受けやすいパターンに気づきました。','clear.star.like_or_habit':'好意、習慣、失う怖さ、期待をゆっくり分けて見ました。',
  'clear.organize.intro':'起きたこと、考え、気持ち、次の一歩をゆっくり分けてみましょう。','clear.organize.step1':'何がありましたか？','clear.organize.step1Help':'状況を選ぶか文章を書くか、どちらか一つは入力してください。','clear.organize.triggerText':'よければ、今起きたことを短く書いてください。','clear.organize.step2':'出来事を分けて見る','clear.organize.facts':'確実に分かっていること','clear.organize.factsPlaceholder':'例：昨夜メッセージを送り、まだ返事がない。','clear.organize.interpretation':'頭に浮かんでいる考え','clear.organize.interpretationPlaceholder':'例：もう話したくないのかな？','clear.organize.unknown':'まだ分からないこと','clear.organize.unknownPlaceholder':'例：まだ返事がない理由。','clear.organize.step3':'今、どんな気持ち？','clear.organize.intensity':'この気持ちは今どのくらい強い？','clear.organize.body':'体にどんな感覚がありますか？（任意）','clear.organize.step4':'相手の気持ちを決めつけない','clear.organize.step4Help':'今までに観察できたやり取りです。飛ばしてもかまいません。','clear.organize.step5':'今、本当に必要なものは？','clear.organize.needs':'自分に必要なこと','clear.organize.action':'今、自分のために何をする？','clear.organize.customAction':'自分の次の一歩を書く','clear.organize.step6':'今回、何に気づいた？','clear.organize.finish':'今回の整理を完了','clear.organize.closing':'今すぐこの関係の答えを出さなくても大丈夫。まず今の自分をいたわりましょう。','clear.organize.completed':'整理が完了しました。スターハート値 +5。','clear.organize.answer.yes':'ある','clear.organize.answer.no':'ない','clear.organize.answer.unknown':'まだ分からない',
  'clear.boat.intro':'相手をどれほど愛しているかを測るものではありません。自分の気持ちの進み方と、現実のやり取りを見比べます。','clear.boat.start':'見てみる','clear.boat.sectionA':'A｜私はどのくらい夢中？','clear.boat.sectionB':'B｜相手は実際にどう応えている？','clear.boat.unknownHelp':'「まだ分からない」は否定ではなく、反応の割合にも含めません。','clear.boat.answer.0':'ほとんどない','clear.boat.answer.1':'たまに','clear.boat.answer.2':'ときどき','clear.boat.answer.3':'よくある','clear.boat.response.2':'ある','clear.boat.response.1':'ときどき','clear.boat.response.0':'ない','clear.boat.response.unknown':'まだ分からない','clear.boat.finish':'今回のときめきガイドを完了','clear.boat.completed':'今回の結果を履歴に保存しました。','clear.boat.scoreA':'自分の入れ込み具合：{score} / 36','clear.boat.result.insufficient':'観察できるやり取りがまだ十分ではありません。今すぐ関係を決めつけなくて大丈夫です。','clear.boat.result.body':'相手の気持ちを急いで推測せず、自分の好意も責めずに、投入した気持ちと実際のやり取りを見比べましょう。',
  'clear.brain.intro':'「恋愛脳」の強さを測るのではなく、誰かを強く好きなとき、自分を見失いやすい場面に気づくためのチェックです。','clear.brain.duration':'25問｜約4〜5分','clear.brain.start':'見てみる','clear.brain.finish':'今回のチェックを完了','clear.brain.completed':'今回のチェックを履歴に保存しました。','clear.brain.low':'自分のペースを保てています','clear.brain.resultIntro':'最近、影響を受けやすいところ','clear.brain.primary':'今もっとも目立つパターン','clear.brain.secondary':'一緒に現れやすいもの','clear.brain.tie':'今はこれらが同じくらい目立ちます',
  'clear.like.intro':'本当に手放しにくいのは、この人？それとも、この関係がくれる感覚？','clear.like.start':'ゆっくり見てみる','clear.like.section.real_person':'現実の相手を好き？','clear.like.section.habit':'相手がいることに慣れただけ？','clear.like.section.fear_of_loss':'失うことを怖がっている？','clear.like.section.imagined_relationship':'好きなのは現実？それとも想像？','clear.like.prompt.real_person':'相手の好きなところ…','clear.like.prompt.habit':'いちばん慣れていること…','clear.like.prompt.fear_of_loss':'この関係が続かなければ、いちばんつらいのは…','clear.like.prompt.imagined_relationship':'起きたことだけを見ると、この関係は…','clear.like.other':'ほかに書いておきたいこと','clear.like.preview':'整理結果を見る','clear.like.finish':'今回の整理を完了','clear.like.completed':'今回の整理を履歴に保存しました。','clear.like.validation':'4枚のカードの必須項目に回答してください。「その他」を選んだ場合は内容も入力してください。','clear.like.closing':'今すぐ気持ちに名前を付けなくて大丈夫。まず何を手放しにくいのか分けてみましょう。',
}

Object.assign(ja,
  entries('clear.organize.body.', ['chest_tight','heart_racing','stomach_uncomfortable','restless','tired','sleepless','want_to_cry','none','other'], ['胸が苦しい','動悸がする','胃が不快','落ち着かない','とても疲れている','眠れない','泣きたい','特に感じない','その他']),
  entries('clear.organize.trigger.', ['no_reply','attitude_changed','social_media','argument','missing_them','waiting_response','overthinking','other'], ['返事がない','態度が変わった気がする','SNSや投稿を見た','気まずいことがあった','急にとても会いたくなった','返事を待っている','考えすぎている','その他']),
  entries('clear.organize.emotion.', ['missing','anxious','sad','hurt','angry','jealous','afraid','lost','confused','hopeful'], ['会いたい','不安','悲しい','傷ついた','怒り','嫉妬','怖い','がっかり','混乱','期待']),
  entries('clear.organize.observation.', ['initiates_contact','makes_time','keeps_promises','listens','mutual_effort','words_match_actions'], ['相手からも連絡がある','一緒に過ごす時間を作る','約束したことをだいたい守る','気持ちを話すと聞いてくれる','自分だけが努力しているわけではない','言葉と行動がだいたい一致している']),
  entries('clear.organize.need.', ['reassurance','understanding','respect','company','space','clarity','boundaries','rest','return_to_life','unknown'], ['安心','理解してもらうこと','尊重','誰かと過ごすこと','自分のための少しの空間','はっきりさせること','自分の境界を確かめること','休むこと','生活に意識を戻すこと','まだ分からない']),
  entries('clear.organize.action.', ['put_phone_down','stop_checking_social','shower_or_rest','take_a_walk','continue_own_plan','talk_to_trusted_person','reply_when_calm','decide_tomorrow','write_diary','custom'], ['しばらくスマホを置く','しばらく投稿を見ない','シャワーを浴びる／休む','散歩する','元の予定を続ける','信頼できる人に話す','落ち着いてから返事する','明日決める','今日の日記に書く','自分で行動を書く']),
  entries('clear.boat.q.', seq('a',12), ['返事が来たか何度も確認する。','返事が長くないと自分のことに集中しにくい。','返事が来ると気分がすぐ大きく良くなる。','会話や一緒にいた場面を何度も思い返す。','言葉や絵文字、既読の意味を考え続ける。','SNS、投稿、オンライン状態をつい確認する。','大切にされているか、好かれているか確かめたくなる。','少し冷たくされると、自分が何か間違えたかと思う。','返事を待つために自分の予定を後回しにしたことがある。','まだ関係が進んでいないのに、遠い未来をよく想像する。','新しい出来事がなくても、相手のことが頭から離れない。','最近、この人や関係が多くの注意と感情を占めている。']),
  entries('clear.boat.q.', seq('b',10), ['いつも私からではなく、相手からも連絡がある。','一緒に過ごす時間を作ってくれる。','約束したことをだいたい守る。','気持ちや考えを話すと聞いてくれる。','私が話した大切なことを覚えている。','話し合いが必要なとき、理由なく消えない。','行動と言葉がだいたい一致している。','やり取りを保つのが私だけではない。','今の関係で自分がどこにいるか、だいたい分かる。','やり取りの意味をいつも推測しなくてよい。']),
  entries('clear.brain.pattern.', patterns, ['思考ループ型','メッセージ依存型','深読み型','手がかり探し型','自己犠牲型']),
  entries('clear.brain.q.', patterns.flatMap((p) => seq(p + '_',5)), ['会話のあと、話したことを何度も思い返す。','やり取りが少しうまくいかないと、自分が悪かったか考え続ける。','終わったことでも、その場面や感情を繰り返し思い出す。','考えても答えが出ないと分かっていても止めにくい。','別のことをしていても、急にこの関係へ考えが戻る。','相手からメッセージが来たか無意識に何度も確認する。','返事が遅いと気分が影響を受けやすい。','メッセージや通知を見ると感情が大きく変わる。','返事を待って、元のことに集中しにくいときがある。','返信の速さ、長さ、口調の変化が特に気になる。','普通の一言に別の意味があるか長く考える。','絵文字、口調、語尾を細かく分析する。','少し冷たくされると何があったか推測し始める。','小さなやり取りから多くの可能性を考える。','証拠がなくても、行動の意味を想像する。','最近の様子を知るためSNSを見る。','オンライン時間、いいね、交流相手に気づくことがある。','何か変だと感じると手がかりを探してしまう。','状況を知るため、予定より多くの投稿を見たことがある。','新しいことがなくても投稿をもう一度確認する。','相手に合わせて自分の予定を変えたことがある。','気が進まなくても相手の必要を先にすることがある。','断ったり違う意見を言うと離れていきそうで心配だ。','相手の気分を自分の感情より先に置くことがある。','関係を保つため、本当は言いたいことを我慢したことがある。']),
  entries('clear.like.q.', likeQuestions, ['想像ではなく、実際にあった好きな点を3つ以上言える？','曖昧さや交際への期待がなくても、この人と過ごしたい？','今の相手が好き？それとも将来こうなってほしい相手？','毎日決まったメッセージややり取りを期待する？','連絡や存在がなくなると、生活の一部が欠けたように感じる？','恋しいものの一部は、毎日あった感覚そのもの？','この関係が続かなければ、いちばんつらいのは何？','つらいのはこの人を失うこと？それとも誰かに気にかけられる感覚？','失うのが怖くて、不快なことを認められないことがある？','実際に一緒にいる時間より未来を想像する時間が多い？','「いつかは」と考えて、今ないものを補っている？','期待を外し、起きたことだけを見ると今の関係をどう表す？']),
  entries('clear.like.answer.', ['yes','some','not_really','not_sure','probably_yes','probably_no','mostly_present','both','mostly_future','often','sometimes','rarely','somewhat','no','maybe','mostly_person','mostly_feeling'], ['はい','少しある','あまりできない','まだ分からない','たぶんそう','たぶん違う','主に今の相手','両方','主に将来こうなってほしい相手','よくある','ときどき','ほとんどない','少し','ない','たぶん','主にこの人を失うこと','主に一緒にいることや気にかけられる感覚を失うこと']),
)

const brainCopy = ['頭の中で答えを出そうとし続けているのかもしれません。今、新しい情報があるかを確かめてみましょう。','安心できる合図を待っているのかもしれません。少しスマホを離し、自分のことを一つ終えましょう。','答えが曖昧なとき、空白を想像で埋めることがあります。分かっていることと推測を分けましょう。','情報を増やして確かさを得ようとしているのかもしれません。もう一度見る前に、新しい情報があるか考えましょう。','関係を大切にするあまり、自分の必要を後回しにしているのかもしれません。応じる前に自分の希望も確かめましょう。']
Object.assign(ja, entries('clear.brain.copy.', patterns, brainCopy), entries('clear.brain.copy.', patterns.map((p) => p + '.v1'), brainCopy), {
  'clear.brain.copy.low_overall.v1':'関係を気にしないわけではありませんが、今はこれらの考えや行動が生活を頻繁に占めてはいないようです。誰かを好きでも、自分に十分な注意を残せます。',
  'clear.brain.copy.tie.v1':'複数のパターンが同じくらい目立っています。一緒に現れることもあり、データはそのまま残ります。一つに決める必要はありません。',
})
Object.assign(ja, entries('clear.like.', seq('q',12), likeQuestions.map((k) => ja['clear.like.q.' + k])))
Object.assign(ja, boatResultBodies(['注意はまだ自分の生活に多く残っています。','気持ちが少しずつ相手へ向かっています。','多くの注意と期待を注いでいます。','この関係が心の大きな部分を占めています。'],['今見える具体的な反応は少なめです。','反応はありますが、分からないことも残っています。','具体的な反応がかなり見えています。','今のやり取りはおおむね双方向です。'],['時間と目に見える行動から情報を増やしましょう。','気持ちを大切にしながら、自分のペースも保てます。','行動を見つつ、自分の生活にも場所を残しましょう。']))
const moduleNames = ['現実の相手への好意','習慣','失う怖さ','未来への期待']
const combos = [[0],[1],[2],[3],[0,1],[0,2],[0,3],[1,2],[1,3],[2,3],[0,1,2],[0,1,3],[0,2,3],[1,2,3],[]]
Object.assign(ja, likeResults(combos.map((c) => c.length ? '今の気持ちには、' + c.map((i) => moduleNames[i]).join('、') + 'が見えます。' : '今すぐ気持ちの答えを決めなくて大丈夫です。'), combos.map((c) => c.length ? 'これらは同時に存在できます。どれかを否定せず、実際に起きたことと期待をゆっくり分けてみましょう。' : '気持ちを分けるには時間が必要なこともあります。分からないことは、まだ分からないままで大丈夫です。'), combos.map(() => '期待や怖さをいったん外すと、今の相手や関係をどう感じますか？')))
Object.assign(ja,
 entries('clear.boat.level.',['investment_low','investment_mild','investment_high','investment_very_high','response_insufficient_observation','response_low','response_mixed','response_good','response_high'],['気持ちはまだ自分に戻せている','少し影響を受け始めている','意識が相手をめぐることが多い','最近この関係に多くの気力を使っている','もう少し観察する時間が必要','今見える反応は少なめ','反応も不確かさもある','具体的な反応がかなり見える','今のやり取りはおおむね双方向']),
 entries('clear.boat.result.',['low_low','low_mixed','low_good','low_high','mild_low','mild_mixed','mild_good','mild_high','high_low','high_mixed','high_good','high_high','very_high_low','very_high_mixed','very_high_good','very_high_high'],['まだ観察中','ゆっくり近づく','反応も自分の余白もある','落ち着いて近づく','気持ちが先に進み始めた','曖昧さに揺れる','ときめきにも反応がある','お互いに近づいている','自分の気持ちが先行','答えより投入が先行','強い好意にも反応がある','ときめきながら自分も忘れない','気持ちが関係より先にいる','強く投入しているが答えはこれから','反応は多いが心がいっぱい','双方向でも自分の余白を']),
 entries('clear.boat.insufficientTitle.',['investment_low','investment_mild','investment_high','investment_very_high'],['まだ定義しなくて大丈夫','気持ちは近づいているが情報は少ない','気持ちは近い。現実が追いつくのを待つ','考えは多いが分かることはまだ少ない']),
 entries('clear.like.option.',['lose_this_person','lose_daily_companionship','lose_feeling_cared_for','be_alone','investment_feels_wasted','no_result','uncertainty','other'],['この人を失うこと','毎日のつながりを失うこと','気にかけられる感覚を失うこと','また一人になること','これまでの投入が無駄に思えること','結果がないまま終わること','まだ分からない','その他']),
 entries('clear.like.module.',['real_person.title','real_person.body','habit.title','habit.body','fear_of_loss.title','fear_of_loss.body','imagined_relationship.title','imagined_relationship.body'],['現実の相手に惹かれている','今の相手に実際に存在する部分を見ています。','生活の中で相手の存在が習慣になっている','決まったやり取りも手放しにくさの一部になり得ます。','失う怖さもここにある','失う怖さが気持ちをより手放しにくくすることがあります。','期待が現実より先を歩いているかもしれない','まだ起きていない期待が、今の現実より先に進んでいるかもしれません。'])
)

export const clearMilestone4MessagesJa = adaptClearLocale('ja', ja)
