import { adaptClearLocale } from './clearLocaleAdapt'
import { boatResultBodies, entries, likeResults } from './clearLocaleFactory'

const seq = (prefix: string, count: number) => Array.from({ length: count }, (_, i) => prefix + String(i + 1).padStart(2, '0'))
const patterns = ['rumination','message_dependency','over_interpretation','detective','self_sacrifice'] as const
const likeQ = ['real_person_three_real_traits','real_person_without_romantic_expectation','real_person_present_vs_future_version','habit_expect_regular_contact','habit_absence_feels_like_missing_routine','habit_missing_the_routine','fear_of_loss_hardest_part','fear_of_loss_person_vs_feeling','fear_of_loss_avoiding_discomfort','imagined_relationship_future_more_than_reality','imagined_relationship_future_fills_present_gap','imagined_relationship_reality_description'] as const
const ko: Record<string,string> = {
  'clear.home':'마음 정리 홈으로','clear.empty':'아직 마음 정리 기록이 없어요. 지금 나에게 맞는 도구부터 시작해 보세요.','clear.history.title':'최근 마음 정리 기록','clear.history.view':'결과 보기','clear.history.delete':'기록 삭제','clear.history.deleteTitle':'이 기록을 삭제할까요?','clear.history.deleteBody':'삭제하면 되돌릴 수 없어요. 이미 받은 별마음 값은 유지됩니다.','clear.history.deleteWithStar':'이 기록에는 마음 정리 별이 있어요. 확인하면 기록만 삭제하고 별은 남깁니다.','clear.history.deleteStarToo':'마음 정리 별도 삭제','clear.history.clearRecord':'마음 정리 시작하기','clear.history.loveBoat':'설렘 가이드','clear.history.loveBrain':'연애 패턴 점검','clear.history.likeOrHabit':'좋아함? 습관?',
  'clear.common.previous':'이전','clear.common.next':'다음','clear.common.continueLater':'나중에 계속','clear.common.continue':'이어서 하기','clear.common.draftProgress':'이어서 하기 · {current} / {total}','clear.common.restart':'처음부터','clear.common.restartTitle':'처음부터 다시 할까요?','clear.common.restartBody':'완료하지 않은 답변이 지워집니다.','clear.common.progress':'{current} / {total}','clear.common.overview':'문항 전체 보기','clear.common.saveStar':'마음 정리 별로 저장','clear.common.savedStar':'마음 정리 별로 저장됨','clear.common.finishAndReturn':'완료하고 홈으로','clear.common.savedDraft':'답변은 이 기기에 바로 저장되고 있어요.','clear.common.error':'저장할 수 없어요. 필수 항목을 확인한 뒤 다시 시도해 주세요.','clear.common.result':'이번 결과',
  'clear.star.clear_record':'마음을 정리하고 지금의 나를 먼저 돌보았어요.','clear.star.love_boat_code':'내가 쏟은 마음과 실제로 일어난 상호작용을 함께 보았어요.','clear.star.love_brain_assessment':'최근 나를 쉽게 흔드는 패턴을 알아차렸어요.','clear.star.like_or_habit':'좋아함, 습관, 잃을까 봐 두려운 마음, 기대를 천천히 나누어 보았어요.',
  'clear.organize.intro':'일어난 일, 생각, 감정, 다음 행동을 천천히 나누어 보세요.','clear.organize.step1':'무슨 일이 있었나요?','clear.organize.step1Help':'상황을 고르거나 글을 쓰는 것 중 하나는 필요해요.','clear.organize.triggerText':'괜찮다면 방금 있었던 일을 간단히 적어 보세요.','clear.organize.step2':'일을 나누어 보기','clear.organize.facts':'확실히 아는 것','clear.organize.factsPlaceholder':'예: 어젯밤 메시지를 보냈고 아직 답이 없다.','clear.organize.interpretation':'내 머릿속의 생각','clear.organize.interpretationPlaceholder':'예: 더는 나와 이야기하고 싶지 않은 걸까?','clear.organize.unknown':'아직 모르는 것','clear.organize.unknownPlaceholder':'예: 아직 답하지 않은 이유.','clear.organize.step3':'지금 나는 어떤 기분인가요?','clear.organize.intensity':'이 감정은 지금 얼마나 강한가요?','clear.organize.body':'몸에서는 무엇이 느껴지나요? (선택)','clear.organize.step4':'상대의 마음을 미리 단정하지 않기','clear.organize.step4Help':'지금까지 관찰한 상호작용이에요. 건너뛰어도 됩니다.','clear.organize.step5':'지금 내가 정말 필요한 것은 무엇인가요?','clear.organize.needs':'내게 필요한 것','clear.organize.action':'지금 나를 위해 무엇을 할 수 있을까요?','clear.organize.customAction':'나만의 다음 행동 쓰기','clear.organize.step6':'이번에 무엇을 알아차렸나요?','clear.organize.finish':'이번 정리 완료','clear.organize.closing':'지금 당장 이 관계의 답을 알 필요는 없어요. 먼저 지금의 나를 돌봐 주세요.','clear.organize.completed':'마음 정리가 완료됐어요. 별마음 값 +5.','clear.organize.answer.yes':'있음','clear.organize.answer.no':'없음','clear.organize.answer.unknown':'아직 잘 모르겠음',
  'clear.boat.intro':'얼마나 사랑하는지를 재는 것이 아니에요. 내 마음이 얼마나 앞서 있는지와 현실의 상호작용을 함께 봅니다.','clear.boat.start':'살펴보기','clear.boat.sectionA':'A｜나는 얼마나 빠져 있나요?','clear.boat.sectionB':'B｜상대는 실제로 어떻게 반응하나요?','clear.boat.unknownHelp':'“아직 모름”은 부정 답변이 아니며 반응 비율에도 포함하지 않아요.','clear.boat.answer.0':'거의 없음','clear.boat.answer.1':'가끔','clear.boat.answer.2':'때때로','clear.boat.answer.3':'자주','clear.boat.response.2':'있음','clear.boat.response.1':'때때로','clear.boat.response.0':'없음','clear.boat.response.unknown':'아직 모름','clear.boat.finish':'이번 설렘 가이드 완료','clear.boat.completed':'이번 설렘 가이드를 기록에 저장했어요.','clear.boat.scoreA':'나의 몰입: {score} / 36','clear.boat.result.insufficient':'아직 관찰할 수 있는 상호작용이 충분하지 않아요. 관계를 서둘러 단정하지 않아도 됩니다.','clear.boat.result.body':'상대의 마음을 서둘러 추측하거나 내 좋아하는 마음을 탓하지 말고, 나의 몰입과 실제 상호작용을 함께 보세요.',
  'clear.brain.intro':'얼마나 “연애에 빠졌는지”를 재는 것이 아니라, 누군가를 많이 좋아할 때 어디에서 나를 놓치기 쉬운지 살펴보는 점검입니다.','clear.brain.duration':'25문항｜약 4~5분','clear.brain.start':'살펴보기','clear.brain.finish':'이번 점검 완료','clear.brain.completed':'이번 점검을 기록에 저장했어요.','clear.brain.low':'나만의 리듬을 지키고 있어요','clear.brain.resultIntro':'최근 내가 쉽게 흔들리는 부분','clear.brain.primary':'지금 가장 두드러지는 패턴','clear.brain.secondary':'함께 자주 나타나는 패턴','clear.brain.tie':'지금은 이 패턴들이 비슷하게 두드러져요',
  'clear.like.intro':'내가 정말 놓기 어려운 것은 이 사람일까요, 아니면 이 관계가 주는 느낌일까요?','clear.like.start':'천천히 살펴보기','clear.like.section.real_person':'나는 실제의 이 사람을 좋아하나요?','clear.like.section.habit':'이 사람이 있는 데 익숙해진 걸까요?','clear.like.section.fear_of_loss':'잃는 것이 두려운 걸까요?','clear.like.section.imagined_relationship':'내가 좋아하는 건 현실일까요, 상상일까요?','clear.like.prompt.real_person':'내가 이 사람에게서 좋아하는 점…','clear.like.prompt.habit':'내가 가장 익숙해진 것은…','clear.like.prompt.fear_of_loss':'이 관계가 이어지지 않는다면 가장 힘든 것은…','clear.like.prompt.imagined_relationship':'실제로 일어난 일만 보면 이 관계는…','clear.like.other':'더 적고 싶은 내용','clear.like.preview':'정리 결과 보기','clear.like.finish':'이번 정리 완료','clear.like.completed':'이번 정리를 기록에 저장했어요.','clear.like.validation':'네 카드의 필수 선택을 모두 완료해 주세요. “기타”를 골랐다면 내용도 적어 주세요.','clear.like.closing':'감정에 서둘러 이름 붙이지 않아도 돼요. 지금 무엇을 놓기 어려운지 먼저 나누어 보세요.',
}
Object.assign(ko,
 entries('clear.organize.body.',['chest_tight','heart_racing','stomach_uncomfortable','restless','tired','sleepless','want_to_cry','none','other'],['가슴이 답답함','심장이 빨리 뜀','속이 불편함','가만히 있기 어려움','많이 피곤함','잠이 오지 않음','울고 싶음','뚜렷한 느낌 없음','기타']),
 entries('clear.organize.trigger.',['no_reply','attitude_changed','social_media','argument','missing_them','waiting_response','overthinking','other'],['답장이 없음','태도가 달라진 것 같음','SNS나 게시물을 봄','불편한 일이 있었음','갑자기 많이 보고 싶어짐','답을 기다리는 중','생각이 너무 많아짐','기타']),
 entries('clear.organize.emotion.',['missing','anxious','sad','hurt','angry','jealous','afraid','lost','confused','hopeful'],['그리움','불안','슬픔','서운함','화남','질투','두려움','실망','혼란','기대']),
 entries('clear.organize.observation.',['initiates_contact','makes_time','keeps_promises','listens','mutual_effort','words_match_actions'],['상대도 먼저 연락함','함께할 시간을 냄','약속을 대체로 지킴','내 감정을 말할 때 들어 줌','나만 노력하는 것은 아님','말과 행동이 대체로 일치함']),
 entries('clear.organize.need.',['reassurance','understanding','respect','company','space','clarity','boundaries','rest','return_to_life','unknown'],['안심','이해받기','존중','함께 있어 줄 사람','나만의 공간','명확하게 알기','내 경계 확인하기','휴식','일상으로 시선 돌리기','아직 모름']),
 entries('clear.organize.action.',['put_phone_down','stop_checking_social','shower_or_rest','take_a_walk','continue_own_plan','talk_to_trusted_person','reply_when_calm','decide_tomorrow','write_diary','custom'],['잠시 휴대폰 내려놓기','당분간 게시물 확인하지 않기','씻거나 쉬기','산책하기','원래 계획 계속하기','믿는 사람과 이야기하기','진정된 뒤 답하기','내일 결정하기','오늘 일기에 쓰기','나만의 행동 쓰기']),
 entries('clear.boat.q.',seq('a',12),['답장이 왔는지 반복해서 확인한다.','답이 오래 없으면 내 일에 집중하기 어렵다.','답장이 오면 기분이 바로 크게 좋아진다.','대화나 함께한 장면을 머릿속에서 자주 되돌린다.','말 한마디, 이모지, 읽음 표시의 뜻을 계속 추측한다.','SNS, 게시물, 접속 상태를 자꾸 확인한다.','나를 신경 쓰는지, 좋아하는지 확인하고 싶다.','조금 차가워지면 내가 잘못했는지 의심한다.','답을 기다리느라 내 계획을 미룬 적이 있다.','관계가 아직 멀리 가지 않았는데 먼 미래를 자주 상상한다.','새로운 일이 없어도 계속 그 사람이 생각난다.','최근 이 사람이나 관계가 내 관심과 감정을 많이 차지한다.']),
 entries('clear.boat.q.',seq('b',10),['항상 내가 먼저 하지 않아도 상대가 먼저 연락한다.','나와 함께할 시간을 마련한다.','약속한 일을 대체로 지킨다.','내 감정이나 생각을 말할 때 들어 준다.','내가 말한 중요한 것을 기억한다.','대화가 필요할 때 이유 없이 사라지지 않는다.','행동과 말이 대체로 일치한다.','이 상호작용을 유지하는 사람이 나뿐은 아니다.','현재 관계에서 내 위치를 대체로 안다.','상대의 뜻을 계속 추측하지 않아도 된다.']),
 entries('clear.brain.pattern.',patterns,['생각 반복 패턴','메시지 의존 패턴','과도한 해석 패턴','단서 확인 패턴','자기희생 패턴']),
 entries('clear.brain.q.',patterns.flatMap((p)=>seq(p+'_',5)),['대화가 끝난 뒤 했던 말을 여러 번 되돌린다.','상호작용이 조금 어긋나면 내가 잘못했는지 계속 생각한다.','일이 끝난 뒤에도 당시 장면이나 감정을 반복해 떠올린다.','더 생각해도 답이 없다는 걸 알지만 멈추기 어렵다.','다른 일을 하다가도 생각이 이 관계로 돌아온다.','메시지가 왔는지 무의식적으로 반복 확인한다.','답장이 늦으면 기분이 쉽게 흔들린다.','메시지나 알림을 보면 감정이 크게 달라진다.','답을 기다리느라 하던 일에 집중하기 어렵다.','답장 속도, 길이, 말투의 변화가 특히 신경 쓰인다.','평범한 말에도 다른 뜻이 있는지 오래 생각한다.','이모지, 말투, 문장 끝을 자세히 분석한다.','조금 차가우면 무슨 일이 생겼는지 추측한다.','작은 상호작용에서 많은 가능성을 떠올린다.','분명한 근거가 없어도 행동의 의미를 상상한다.','최근 무엇을 하는지 알기 위해 SNS를 본다.','접속 시간, 좋아요, 누구와 소통하는지 살핀다.','이상하다고 느끼면 단서를 더 찾는다.','상황을 알기 위해 생각보다 많은 게시물을 본 적이 있다.','새로운 일이 없어도 게시물을 다시 확인한다.','상대에게 맞추려고 내 계획을 바꾼 적이 있다.','불편하거나 원하지 않아도 상대의 필요를 먼저 둘 때가 있다.','거절하거나 다른 의견을 말하면 멀어질까 걱정한다.','상대의 기분을 내 감정보다 먼저 둘 때가 있다.','관계를 유지하려고 하고 싶은 말을 참은 적이 있다.']),
 entries('clear.like.q.',likeQ,['상상이 아니라 실제로 있었던 좋아하는 점을 세 가지 이상 말할 수 있나요?','썸이나 교제 기대가 없어도 이 사람과 함께하는 것이 좋을까요?','지금의 모습을 좋아하나요, 앞으로 되길 바라는 모습을 좋아하나요?','매일 정해진 연락이나 상호작용을 기대하나요?','연락이나 존재가 없으면 일상의 한 부분이 빠진 것 같나요?','그리운 것의 일부는 매일 있던 느낌 자체인가요?','관계가 이어지지 않으면 무엇이 가장 힘들까요?','이 사람을 잃는 것과 함께함이나 관심받는 느낌을 잃는 것 중 무엇이 더 힘들까요?','잃을까 봐 불편한 상호작용을 인정하지 못한 적이 있나요?','실제로 함께하는 시간보다 미래를 상상하는 시간이 더 많은가요?','“언젠가는”이라는 생각으로 지금 없는 것을 채우나요?','기대를 빼고 일어난 일만 보면 지금 관계를 어떻게 표현할까요?']),
 entries('clear.like.answer.',['yes','some','not_really','not_sure','probably_yes','probably_no','mostly_present','both','mostly_future','often','sometimes','rarely','somewhat','no','maybe','mostly_person','mostly_feeling'],['예','조금 있음','별로 그렇지 않음','아직 잘 모르겠음','아마 그럴 것 같음','아마 아닐 것 같음','주로 지금의 모습','둘 다','주로 앞으로 바라는 모습','자주','때때로','거의 없음','조금','없음','어쩌면','주로 이 사람을 잃는 것','주로 함께함이나 관심받는 느낌을 잃는 것'])
)
const brainCopy=['머릿속에서 계속 답을 찾으려는 중일 수 있어요. 지금 새로운 정보가 있는지 물어보세요.','안심할 신호를 기다리는 중일 수 있어요. 잠시 휴대폰을 멀리 두고 내 일을 하나 끝내 보세요.','답이 불분명할 때 빈칸을 상상으로 채울 수 있어요. 아는 것과 추측을 나누어 보세요.','더 많은 정보로 확실함을 얻으려는 중일 수 있어요. 다시 보기 전에 새 정보가 있는지 확인하세요.','관계를 소중히 여겨 내 필요를 뒤로 미룰 수 있어요. 동의하기 전에 내가 원하는 것도 물어보세요.']
Object.assign(ko,entries('clear.brain.copy.',patterns,brainCopy),entries('clear.brain.copy.',patterns.map((p)=>p+'.v1'),brainCopy),{'clear.brain.copy.low_overall.v1':'관계를 신경 쓰지 않는다는 뜻은 아니지만, 지금은 이런 생각과 행동이 일상을 자주 차지하지 않아요. 누군가를 좋아하면서도 나에게 충분한 관심을 남길 수 있어요.','clear.brain.copy.tie.v1':'한 가지보다 여러 패턴이 비슷하게 나타나요. 함께 나타날 수 있으며 데이터는 그대로 남습니다. 하나만 억지로 고를 필요는 없어요.'})
Object.assign(ko,entries('clear.like.',seq('q',12),likeQ.map((k)=>ko['clear.like.q.'+k])))
Object.assign(ko,boatResultBodies(['관심이 아직 내 일상에 많이 남아 있어요.','마음이 조금씩 상대에게 향하고 있어요.','많은 관심과 기대를 쏟고 있어요.','이 관계가 마음의 큰 부분을 차지하고 있어요.'],['지금 보이는 구체적인 반응은 적어요.','반응은 있지만 모르는 부분도 남아 있어요.','구체적인 반응이 꽤 보여요.','현재 상호작용은 대체로 서로 주고받고 있어요.'],['시간과 눈에 보이는 행동으로 정보를 더 확인하세요.','내 감정을 인정하면서도 내 속도를 지킬 수 있어요.','행동을 보면서 내 일상에도 자리를 남겨 주세요.']))
const names=['실제 사람에 대한 호감','습관','잃을까 봐 두려운 마음','미래에 대한 기대']; const combos=[[0],[1],[2],[3],[0,1],[0,2],[0,3],[1,2],[1,3],[2,3],[0,1,2],[0,1,3],[0,2,3],[1,2,3],[]]
Object.assign(ko,likeResults(combos.map((c)=>c.length?'지금 감정에는 '+c.map((i)=>names[i]).join(', ')+'이 보여요.':'지금 당장 감정의 답을 정하지 않아도 돼요.'),combos.map((c)=>c.length?'이 감정들은 함께 있을 수 있어요. 어느 하나를 부정하지 말고 실제 일과 기대를 천천히 나누어 보세요.':'감정을 나누는 데 시간이 필요할 수 있어요. 아직 모르는 것은 모르는 채로 두어도 됩니다.'),combos.map(()=>'기대와 두려움을 잠시 내려놓으면 지금 이 사람과 관계를 어떻게 느끼나요?')))
Object.assign(ko,
 entries('clear.boat.level.',['investment_low','investment_mild','investment_high','investment_very_high','response_insufficient_observation','response_low','response_mixed','response_good','response_high'],['마음이 아직 내게 머물러 있어요','조금씩 영향을 받기 시작했어요','관심이 자주 상대를 맴돌아요','최근 이 관계에 많은 마음을 쓰고 있어요','조금 더 관찰할 시간이 필요해요','지금 보이는 반응은 적어요','반응도 있고 불확실함도 있어요','구체적인 반응이 꽤 보여요','현재 상호작용은 대체로 서로 오가요']),
 entries('clear.boat.result.',['low_low','low_mixed','low_good','low_high','mild_low','mild_mixed','mild_good','mild_high','high_low','high_mixed','high_good','high_high','very_high_low','very_high_mixed','very_high_good','very_high_high'],['아직 관찰 중','천천히 가까워짐','반응과 나만의 여유가 함께 있음','안정적으로 가까워짐','마음이 먼저 빨라짐','모호함에 흔들림','설렘과 실제 반응이 함께 있음','서로 가까워지는 중','내 마음이 앞서 있음','내 몰입이 답보다 빠름','깊은 호감과 반응이 함께 있음','많이 설레도 나를 잊지 않기','마음이 관계보다 앞서 있음','많이 몰입했지만 답은 아직','반응은 많지만 마음이 가득 참','서로 반응해도 내 자리 남기기']),
 entries('clear.boat.insufficientTitle.',['investment_low','investment_mild','investment_high','investment_very_high'],['아직 정의하지 않아도 돼요','마음은 가까워지지만 정보는 적어요','마음은 가까워졌어요. 현실을 더 지켜봐요','생각은 많지만 아는 것은 아직 적어요']),
 entries('clear.like.option.',['lose_this_person','lose_daily_companionship','lose_feeling_cared_for','be_alone','investment_feels_wasted','no_result','uncertainty','other'],['이 사람을 잃는 것','매일의 함께함을 잃는 것','관심받는 느낌을 잃는 것','다시 혼자가 되는 것','그동안의 노력이 헛되게 느껴지는 것','결과 없이 끝나는 것','아직 모름','기타']),
 entries('clear.like.module.',['real_person.title','real_person.body','habit.title','habit.body','fear_of_loss.title','fear_of_loss.body','imagined_relationship.title','imagined_relationship.body'],['실제의 이 사람에게 호감이 있어요','지금 실제로 존재하는 이 사람의 모습을 보고 있어요.','일상에서 상대의 존재가 습관이 되었어요','정기적인 상호작용도 놓기 어려운 이유가 될 수 있어요.','잃을까 봐 두려운 마음도 있어요','잃을까 봐 두려우면 감정을 더 놓기 어려울 수 있어요.','기대가 현실보다 앞서 있을 수 있어요','아직 일어나지 않은 기대가 현재 현실보다 앞서 있을 수 있어요.'])
)
export const clearMilestone4MessagesKo=adaptClearLocale('ko',ko)
