import type { Locale } from './messages'

export const exportTextMessages = {
  'zh-TW': {
    'export.title': '星星戀愛日記', 'export.subtitle': '文字資料匯出', 'export.date': '匯出日期：{date}', 'export.empty': '尚無資料', 'export.footer': '匯出完成', 'export.photoExcluded': '此檔案僅包含文字資料，不包含任何照片。', 'export.feedback.success': '文字資料已匯出。', 'export.feedback.shareSheetOpened': '已開啟分享選單，請選擇儲存或分享方式。', 'export.feedback.cancelled': '已取消匯出。', 'export.feedback.error': '匯出失敗，請稍後再試。', 'export.feedback.preparing': '準備匯出…',
    'export.profile': '基本資料', 'export.me': '我的暱稱', 'export.partner': '喜歡的人', 'export.birthday': '生日', 'export.score': '星心值', 'export.scoreTotal': '累積星心值：{total}', 'export.dates': '重要日子', 'export.diaries': '日記', 'export.moods': '心情紀錄', 'export.clear': '清醒紀錄', 'export.stars': '星星瓶', 'export.moodStars': '心情星星', 'export.clearStars': '清醒星星', 'export.heartPhrases': '七句心話', 'export.message': '想對你說', 'export.remembered': '我記得的你', 'export.moments': '我們的時刻',
    'export.label.title': '標題', 'export.label.date': '日期', 'export.label.type': '類型', 'export.label.description': '說明', 'export.label.content': '內容', 'export.label.mood': '心情', 'export.label.tool': '工具', 'export.label.summary': '摘要', 'export.label.result': '結果', 'export.label.acceptedAt': '接受時間', 'export.label.updatedAt': '更新時間', 'export.label.favorite': '收藏', 'export.favorite.yes': '是', 'export.favorite.no': '否', 'export.clear.completed': '已完成這次整理。',
  },
  en: {
    'export.title': 'Starry Love Diary', 'export.subtitle': 'Text data export', 'export.date': 'Export date: {date}', 'export.empty': 'No data yet', 'export.footer': 'Export complete', 'export.photoExcluded': 'This file contains text data only and does not include photos.', 'export.feedback.success': 'Text data exported.', 'export.feedback.shareSheetOpened': 'The share sheet is open. Choose how to save or share the file.', 'export.feedback.cancelled': 'Export cancelled.', 'export.feedback.error': 'Export failed. Please try again later.', 'export.feedback.preparing': 'Preparing export…',
    'export.profile': 'Basic profile', 'export.me': 'My nickname', 'export.partner': 'Person I like', 'export.birthday': 'Birthday', 'export.score': 'Starheart', 'export.scoreTotal': 'Total Starheart: {total}', 'export.dates': 'Important Dates', 'export.diaries': 'Diaries', 'export.moods': 'Mood records', 'export.clear': 'Clarity records', 'export.stars': 'Star Bottle', 'export.moodStars': 'Mood stars', 'export.clearStars': 'Clarity stars', 'export.heartPhrases': 'Heart phrases', 'export.message': 'What I want to tell you', 'export.remembered': 'What I remember about you', 'export.moments': 'Our moments',
    'export.label.title': 'Title', 'export.label.date': 'Date', 'export.label.type': 'Type', 'export.label.description': 'Description', 'export.label.content': 'Content', 'export.label.mood': 'Mood', 'export.label.tool': 'Tool', 'export.label.summary': 'Summary', 'export.label.result': 'Result', 'export.label.acceptedAt': 'Accepted at', 'export.label.updatedAt': 'Updated at', 'export.label.favorite': 'Favorite', 'export.favorite.yes': 'Yes', 'export.favorite.no': 'No', 'export.clear.completed': 'This reflection was completed.',
  },
  ja: {
    'export.title': '星星恋愛日記', 'export.subtitle': 'テキストデータの書き出し', 'export.date': '書き出し日：{date}', 'export.empty': 'まだ記録はありません', 'export.footer': '書き出し完了', 'export.photoExcluded': 'このファイルにはテキストデータのみが含まれ、写真は含まれません。', 'export.feedback.success': 'テキストデータを書き出しました。', 'export.feedback.shareSheetOpened': '共有シートを開きました。保存または共有方法を選んでください。', 'export.feedback.cancelled': '書き出しをキャンセルしました。', 'export.feedback.error': '書き出しに失敗しました。後でもう一度お試しください。', 'export.feedback.preparing': '書き出しを準備中…',
    'export.profile': '基本情報', 'export.me': '自分のニックネーム', 'export.partner': '気になる人', 'export.birthday': '誕生日', 'export.score': '星心値', 'export.scoreTotal': '累積星心値：{total}', 'export.dates': '大切な日', 'export.diaries': '日記', 'export.moods': '気分の記録', 'export.clear': '気持ち整理の記録', 'export.stars': '星のボトル', 'export.moodStars': '気分の星', 'export.clearStars': '気づきの星', 'export.heartPhrases': '心のことば', 'export.message': '伝えたいこと', 'export.remembered': 'あなたについて覚えていること', 'export.moments': 'ふたりの瞬間',
    'export.label.title': 'タイトル', 'export.label.date': '日付', 'export.label.type': '種類', 'export.label.description': '説明', 'export.label.content': '内容', 'export.label.mood': '気分', 'export.label.tool': 'ツール', 'export.label.summary': 'まとめ', 'export.label.result': '結果', 'export.label.acceptedAt': '受け入れた日時', 'export.label.updatedAt': '更新日時', 'export.label.favorite': 'お気に入り', 'export.favorite.yes': 'はい', 'export.favorite.no': 'いいえ', 'export.clear.completed': 'この整理を完了しました。',
  },
  ko: {
    'export.title': '별빛 연애 일기', 'export.subtitle': '텍스트 데이터 내보내기', 'export.date': '내보낸 날짜: {date}', 'export.empty': '아직 기록이 없어요', 'export.footer': '내보내기 완료', 'export.photoExcluded': '이 파일에는 텍스트 데이터만 포함되며 사진은 포함되지 않아요.', 'export.feedback.success': '텍스트 데이터를 내보냈어요.', 'export.feedback.shareSheetOpened': '공유 시트가 열렸어요. 저장하거나 공유할 방법을 선택해 주세요.', 'export.feedback.cancelled': '내보내기를 취소했어요.', 'export.feedback.error': '내보내기에 실패했어요. 잠시 후 다시 시도해 주세요.', 'export.feedback.preparing': '내보내기를 준비 중…',
    'export.profile': '기본 정보', 'export.me': '내 별명', 'export.partner': '좋아하는 사람', 'export.birthday': '생일', 'export.score': '별하트', 'export.scoreTotal': '누적 별하트: {total}', 'export.dates': '소중한 날', 'export.diaries': '일기', 'export.moods': '기분 기록', 'export.clear': '마음 정리 기록', 'export.stars': '별 병', 'export.moodStars': '기분 별', 'export.clearStars': '마음 정리 별', 'export.heartPhrases': '마음 한마디', 'export.message': '전하고 싶은 말', 'export.remembered': '당신에 대해 기억하는 것', 'export.moments': '우리의 순간',
    'export.label.title': '제목', 'export.label.date': '날짜', 'export.label.type': '종류', 'export.label.description': '설명', 'export.label.content': '내용', 'export.label.mood': '기분', 'export.label.tool': '도구', 'export.label.summary': '요약', 'export.label.result': '결과', 'export.label.acceptedAt': '받아들인 시간', 'export.label.updatedAt': '업데이트 시간', 'export.label.favorite': '즐겨찾기', 'export.favorite.yes': '예', 'export.favorite.no': '아니요', 'export.clear.completed': '이 마음 정리를 완료했어요.',
  },
  es: {
    'export.title': 'Diario de amor estrellado', 'export.subtitle': 'Exportación de datos de texto', 'export.date': 'Fecha de exportación: {date}', 'export.empty': 'Aún no hay datos', 'export.footer': 'Exportación completada', 'export.photoExcluded': 'Este archivo contiene solo datos de texto y no incluye fotos.', 'export.feedback.success': 'Datos de texto exportados.', 'export.feedback.shareSheetOpened': 'La hoja para compartir está abierta. Elige cómo guardar o compartir el archivo.', 'export.feedback.cancelled': 'Exportación cancelada.', 'export.feedback.error': 'No se pudo exportar. Inténtalo de nuevo más tarde.', 'export.feedback.preparing': 'Preparando la exportación…',
    'export.profile': 'Datos básicos', 'export.me': 'Mi apodo', 'export.partner': 'La persona que me gusta', 'export.birthday': 'Cumpleaños', 'export.score': 'Puntos de estrella', 'export.scoreTotal': 'Total de puntos de estrella: {total}', 'export.dates': 'Fechas importantes', 'export.diaries': 'Diarios', 'export.moods': 'Registros de ánimo', 'export.clear': 'Registros de claridad', 'export.stars': 'Frasco de estrellas', 'export.moodStars': 'Estrellas de ánimo', 'export.clearStars': 'Estrellas de claridad', 'export.heartPhrases': 'Frases del corazón', 'export.message': 'Lo que quiero decirte', 'export.remembered': 'Lo que recuerdo de ti', 'export.moments': 'Nuestros momentos',
    'export.label.title': 'Título', 'export.label.date': 'Fecha', 'export.label.type': 'Tipo', 'export.label.description': 'Descripción', 'export.label.content': 'Contenido', 'export.label.mood': 'Ánimo', 'export.label.tool': 'Herramienta', 'export.label.summary': 'Resumen', 'export.label.result': 'Resultado', 'export.label.acceptedAt': 'Aceptada el', 'export.label.updatedAt': 'Actualizada el', 'export.label.favorite': 'Favorita', 'export.favorite.yes': 'Sí', 'export.favorite.no': 'No', 'export.clear.completed': 'Esta reflexión se completó.',
  },
  fr: {
    'export.title': 'Journal d’amour étoilé', 'export.subtitle': 'Exportation des données texte', 'export.date': 'Date d’exportation : {date}', 'export.empty': 'Aucune donnée pour le moment', 'export.footer': 'Exportation terminée', 'export.photoExcluded': 'Ce fichier ne contient que des données texte et aucune photo.', 'export.feedback.success': 'Données texte exportées.', 'export.feedback.shareSheetOpened': 'La feuille de partage est ouverte. Choisissez comment enregistrer ou partager le fichier.', 'export.feedback.cancelled': 'Exportation annulée.', 'export.feedback.error': 'Échec de l’exportation. Réessayez plus tard.', 'export.feedback.preparing': 'Préparation de l’exportation…',
    'export.profile': 'Informations de base', 'export.me': 'Mon surnom', 'export.partner': 'La personne qui me plaît', 'export.birthday': 'Anniversaire', 'export.score': 'Points étoile', 'export.scoreTotal': 'Total des points étoile : {total}', 'export.dates': 'Dates importantes', 'export.diaries': 'Journal', 'export.moods': 'Notes d’humeur', 'export.clear': 'Notes de clarté', 'export.stars': 'Bocal d’étoiles', 'export.moodStars': 'Étoiles d’humeur', 'export.clearStars': 'Étoiles de clarté', 'export.heartPhrases': 'Phrases du cœur', 'export.message': 'Ce que je veux te dire', 'export.remembered': 'Ce dont je me souviens de toi', 'export.moments': 'Nos moments',
    'export.label.title': 'Titre', 'export.label.date': 'Date', 'export.label.type': 'Type', 'export.label.description': 'Description', 'export.label.content': 'Contenu', 'export.label.mood': 'Humeur', 'export.label.tool': 'Outil', 'export.label.summary': 'Résumé', 'export.label.result': 'Résultat', 'export.label.acceptedAt': 'Acceptée le', 'export.label.updatedAt': 'Mise à jour le', 'export.label.favorite': 'Favorite', 'export.favorite.yes': 'Oui', 'export.favorite.no': 'Non', 'export.clear.completed': 'Cette réflexion est terminée.',
  },
} as const satisfies Record<Locale, Record<string, string>>
