import type { Locale } from './messages'

type HeartTalkKey = 'identity' | 'pair' | 'invalid' | 'network' | 'service' | 'syncPending'

const messages: Record<Locale, Record<HeartTalkKey, string>> = {
  'zh-TW': { identity: '請先完成必要的帳號身分確認後，再建立心話邀約。', pair: '目前沒有有效的專屬配對，無法建立或讀取心話邀約。', invalid: '請確認題目、日期與時間後再試一次。', network: '目前無法連線，請確認網路後再試一次。', service: '心話服務暫時無法完成操作，請稍後再試。', syncPending: '邀約已建立，但目前無法同步最新畫面；請勿重複送出，稍後重新整理即可確認。' },
  en: { identity: 'Complete the required account identity check before creating a Heart Talk invitation.', pair: 'There is no active Pair to create or read Heart Talk invitations.', invalid: 'Check the prompt, date, and time, then try again.', network: 'We could not connect. Check your network and try again.', service: 'Heart Talk cannot complete this right now. Please try again later.', syncPending: 'The invitation was created, but the latest screen could not sync. Do not send it again; refresh later to confirm.' },
  ja: { identity: '心話の招待を作成する前に、必要なアカウント確認を完了してください。', pair: '有効なペアがないため、心話の招待を作成または確認できません。', invalid: '題目、日付、時間を確認してからもう一度お試しください。', network: '接続できませんでした。ネットワークを確認してもう一度お試しください。', service: '心話サービスは現在この操作を完了できません。しばらくしてからお試しください。', syncPending: '招待は作成されましたが、最新画面を同期できません。重複して送信せず、後でもう一度更新してください。' },
  ko: { identity: '마음 대화 초대를 만들기 전에 필요한 계정 확인을 완료해 주세요.', pair: '활성 페어가 없어 마음 대화 초대를 만들거나 읽을 수 없어요.', invalid: '주제, 날짜, 시간을 확인한 뒤 다시 시도해 주세요.', network: '연결할 수 없어요. 네트워크를 확인한 뒤 다시 시도해 주세요.', service: '마음 대화 서비스가 지금은 이 작업을 완료할 수 없어요. 잠시 후 다시 시도해 주세요.', syncPending: '초대는 만들어졌지만 최신 화면을 동기화하지 못했어요. 중복 전송하지 말고 나중에 새로고침해 확인해 주세요.' },
  es: { identity: 'Completa la verificación de identidad requerida antes de crear una invitación.', pair: 'No hay una pareja activa para crear o leer invitaciones de conversación.', invalid: 'Revisa el tema, la fecha y la hora antes de intentarlo de nuevo.', network: 'No se pudo conectar. Revisa tu red e inténtalo de nuevo.', service: 'La conversación no puede completar esta acción ahora. Inténtalo más tarde.', syncPending: 'La invitación se creó, pero no se pudo sincronizar la pantalla. No la envíes otra vez; actualiza más tarde para confirmarla.' },
  fr: { identity: 'Terminez la vérification d’identité requise avant de créer une invitation.', pair: 'Aucun duo actif ne permet de créer ou de lire des invitations.', invalid: 'Vérifiez le sujet, la date et l’heure avant de réessayer.', network: 'Connexion impossible. Vérifiez votre réseau et réessayez.', service: 'La conversation du cœur ne peut pas terminer cette action pour le moment. Réessayez plus tard.', syncPending: 'L’invitation a été créée, mais l’écran n’a pas pu se synchroniser. Ne l’envoyez pas à nouveau ; actualisez plus tard pour confirmer.' },
}

export const heartTalkMessages: Record<Locale, Record<`our.heartTalk.${HeartTalkKey}`, string>> = Object.fromEntries((Object.keys(messages) as Locale[]).map((locale) => [locale, Object.fromEntries(Object.entries(messages[locale]).map(([key, value]) => [`our.heartTalk.${key}`, value]))])) as Record<Locale, Record<`our.heartTalk.${HeartTalkKey}`, string>>
