import type { Locale } from './messages'

type HeartTalkCoreKey = 'identity' | 'pair' | 'invalid' | 'pastDate' | 'startPassed' | 'endBeforeStart' | 'network' | 'service' | 'syncPending' | 'pending' | 'pendingTitle' | 'pendingBody' | 'loadedLimit' | 'noActive'
type HeartTalkKey = HeartTalkCoreKey | 'expand' | 'collapse'

const messages: Record<Locale, Record<HeartTalkCoreKey, string>> = {
  'zh-TW': { identity: '請先完成必要的帳號身分確認後，再建立心話邀約。', pair: '目前沒有有效的專屬配對，無法建立或讀取心話邀約。', invalid: '請確認題目、日期與時間後再試一次。', pastDate: '不能選擇過去日期。', startPassed: '開始時間已過，請重新選擇日期或時間。', endBeforeStart: '結束時間必須晚於開始時間。', network: '目前無法連線，請確認網路後再試一次。', service: '心話服務暫時無法完成操作，請稍後再試。', syncPending: '邀約已建立，但目前無法同步最新畫面；請勿重複送出，稍後重新整理即可確認。', pending: '等待回覆', pendingTitle: '心話邀約等待回覆', pendingBody: '這筆邀約尚未約好，可等待對方回覆或取消。', loadedLimit: '目前只顯示已載入的 20 筆邀約；完整清單與分頁將在後續版本支援。', noActive: '目前沒有可查看的心話邀約。' },
  en: { identity: 'Complete the required account identity check before creating a Heart Talk invitation.', pair: 'There is no active Pair to create or read Heart Talk invitations.', invalid: 'Check the prompt, date, and time, then try again.', pastDate: 'Choose a date that has not passed.', startPassed: 'The start time has passed. Choose a new date or time.', endBeforeStart: 'The end time must be after the start time.', network: 'We could not connect. Check your network and try again.', service: 'Heart Talk cannot complete this right now. Please try again later.', syncPending: 'The invitation was created, but the latest screen could not sync. Do not send it again; refresh later to confirm.', pending: 'Awaiting a reply', pendingTitle: 'Heart Talk invitation awaiting a reply', pendingBody: 'This invitation is not scheduled yet. Wait for a reply or cancel it.', loadedLimit: 'Only the 20 invitations currently loaded are shown. A complete list and pagination will come in a later version.', noActive: 'There are no Heart Talk invitations to view right now.' },
  ja: { identity: '心話の招待を作成する前に、必要なアカウント確認を完了してください。', pair: '有効なペアがないため、心話の招待を作成または確認できません。', invalid: '題目、日付、時間を確認してからもう一度お試しください。', pastDate: '過去の日付は選べません。', startPassed: '開始時刻を過ぎています。日付または時刻を選び直してください。', endBeforeStart: '終了時刻は開始時刻より後にしてください。', network: '接続できませんでした。ネットワークを確認してもう一度お試しください。', service: '心話サービスは現在この操作を完了できません。しばらくしてからお試しください。', syncPending: '招待は作成されましたが、最新画面を同期できません。重複して送信せず、後でもう一度更新してください。', pending: '返事待ち', pendingTitle: '心話の招待は返事待ちです', pendingBody: 'この招待はまだ約束されていません。返事を待つか、取り消すことができます。', loadedLimit: '現在読み込まれている20件の招待のみを表示しています。完全な一覧とページ送りは今後のバージョンで対応します。', noActive: '現在確認できる心話の招待はありません。' },
  ko: { identity: '마음 대화 초대를 만들기 전에 필요한 계정 확인을 완료해 주세요.', pair: '활성 페어가 없어 마음 대화 초대를 만들거나 읽을 수 없어요.', invalid: '주제, 날짜, 시간을 확인한 뒤 다시 시도해 주세요.', pastDate: '지난 날짜는 선택할 수 없어요.', startPassed: '시작 시간이 지났어요. 날짜나 시간을 다시 선택해 주세요.', endBeforeStart: '종료 시간은 시작 시간보다 늦어야 해요.', network: '연결할 수 없어요. 네트워크를 확인한 뒤 다시 시도해 주세요.', service: '마음 대화 서비스가 지금은 이 작업을 완료할 수 없어요. 잠시 후 다시 시도해 주세요.', syncPending: '초대는 만들어졌지만 최신 화면을 동기화하지 못했어요. 중복 전송하지 말고 나중에 새로고침해 확인해 주세요.', pending: '응답 대기 중', pendingTitle: '마음 대화 초대가 응답을 기다리고 있어요', pendingBody: '이 초대는 아직 약속되지 않았어요. 응답을 기다리거나 취소할 수 있어요.', loadedLimit: '현재 불러온 20개의 초대만 표시합니다. 전체 목록과 페이지 나누기는 이후 버전에서 지원합니다.', noActive: '현재 확인할 수 있는 마음 대화 초대가 없어요.' },
  es: { identity: 'Completa la verificación de identidad requerida antes de crear una invitación.', pair: 'No hay una pareja activa para crear o leer invitaciones de conversación.', invalid: 'Revisa el tema, la fecha y la hora antes de intentarlo de nuevo.', pastDate: 'No puedes elegir una fecha pasada.', startPassed: 'La hora de inicio ya pasó. Elige otra fecha u hora.', endBeforeStart: 'La hora de finalización debe ser posterior a la de inicio.', network: 'No se pudo conectar. Revisa tu red e inténtalo de nuevo.', service: 'La conversación no puede completar esta acción ahora. Inténtalo más tarde.', syncPending: 'La invitación se creó, pero no se pudo sincronizar la pantalla. No la envíes otra vez; actualiza más tarde para confirmarla.', pending: 'Esperando respuesta', pendingTitle: 'La invitación espera una respuesta', pendingBody: 'Esta invitación aún no está acordada. Puedes esperar una respuesta o cancelarla.', loadedLimit: 'Solo se muestran las 20 invitaciones cargadas. La lista completa y la paginación llegarán en una versión posterior.', noActive: 'No hay invitaciones de conversación para ver ahora.' },
  fr: { identity: 'Terminez la vérification d’identité requise avant de créer une invitation.', pair: 'Aucun duo actif ne permet de créer ou de lire des invitations.', invalid: 'Vérifiez le sujet, la date et l’heure avant de réessayer.', pastDate: 'Vous ne pouvez pas choisir une date passée.', startPassed: 'L’heure de début est passée. Choisissez une autre date ou heure.', endBeforeStart: 'L’heure de fin doit être postérieure à l’heure de début.', network: 'Connexion impossible. Vérifiez votre réseau et réessayez.', service: 'La conversation du cœur ne peut pas terminer cette action pour le moment. Réessayez plus tard.', syncPending: 'L’invitation a été créée, mais l’écran n’a pas pu se synchroniser. Ne l’envoyez pas à nouveau ; actualisez plus tard pour confirmer.', pending: 'En attente de réponse', pendingTitle: 'L’invitation attend une réponse', pendingBody: 'Cette invitation n’est pas encore planifiée. Vous pouvez attendre une réponse ou l’annuler.', loadedLimit: 'Seules les 20 invitations actuellement chargées sont affichées. La liste complète et la pagination arriveront dans une version ultérieure.', noActive: 'Il n’y a aucune invitation de conversation à consulter pour le moment.' },
}

const disclosureMessages: Record<Locale, Pick<Record<HeartTalkKey, string>, 'expand' | 'collapse'>> = {
  'zh-TW': { expand: '展開詳情', collapse: '收合詳情' }, en: { expand: 'Show details', collapse: 'Hide details' },
  ja: { expand: '詳細を表示', collapse: '詳細を閉じる' }, ko: { expand: '세부 정보 보기', collapse: '세부 정보 닫기' },
  es: { expand: 'Ver detalles', collapse: 'Ocultar detalles' }, fr: { expand: 'Afficher les détails', collapse: 'Masquer les détails' },
}

export const heartTalkMessages: Record<Locale, Record<`our.heartTalk.${HeartTalkKey}`, string>> = Object.fromEntries((Object.keys(messages) as Locale[]).map((locale) => [locale, Object.fromEntries(Object.entries({ ...messages[locale], ...disclosureMessages[locale] }).map(([key, value]) => [`our.heartTalk.${key}`, value]))])) as Record<Locale, Record<`our.heartTalk.${HeartTalkKey}`, string>>
