export const heartRevealCycleMessages = {
  'zh-TW': {
    'heartRevealCycle.ready': '七句心話已完成', 'heartRevealCycle.choose': '選一句心話做成心意卡', 'heartRevealCycle.chooseTitle': '選擇一句心話', 'heartRevealCycle.chooseHint': '可從所有已留下的心話中選一句。', 'heartRevealCycle.confirmTitle': '確認心意', 'heartRevealCycle.back': '回上一步', 'heartRevealCycle.generate': '生成心意卡', 'heartRevealCycle.generated': '心意已準備好 ✨', 'heartRevealCycle.finish': '完成這份心意，開始下一輪', 'heartRevealCycle.resetTitle': '開始下一輪？', 'heartRevealCycle.resetBody': '目前這張照片的顯影會結束，你的七句心話都會保留。下一輪將重新從 0/7 開始。', 'heartRevealCycle.startNext': '開始下一輪', 'heartRevealCycle.nextStarted': '下一輪已開始', 'heartRevealCycle.setNextPhoto': '設定下一張照片', 'heartRevealCycle.writeNext': '寫下下一句心話', 'heartRevealCycle.shareError': '圖片分享失敗，請再試一次。', 'heartRevealCycle.shareUnsupported': '此裝置不支援直接分享圖片，已改為下載。', 'heartRevealCycle.textPlacement': '文字位置', 'heartRevealCycle.placement.top-left': '左上', 'heartRevealCycle.placement.top-center': '上中央', 'heartRevealCycle.placement.top-right': '右上', 'heartRevealCycle.placement.bottom-left': '左下', 'heartRevealCycle.placement.bottom-center': '下中央', 'heartRevealCycle.placement.bottom-right': '右下',
  },
  en: {
    'heartRevealCycle.ready': 'Seven heart notes are complete', 'heartRevealCycle.choose': 'Choose a heart note for a card', 'heartRevealCycle.chooseTitle': 'Choose a heart note', 'heartRevealCycle.chooseHint': 'Choose one from all the heart notes you have kept.', 'heartRevealCycle.confirmTitle': 'Confirm your note', 'heartRevealCycle.back': 'Go back', 'heartRevealCycle.generate': 'Create heart card', 'heartRevealCycle.generated': 'Your heart card is ready ✨', 'heartRevealCycle.finish': 'Finish this note and start the next cycle', 'heartRevealCycle.resetTitle': 'Start the next cycle?', 'heartRevealCycle.resetBody': 'This photo reveal will end, but all your heart notes will remain. The next cycle starts again at 0/7.', 'heartRevealCycle.startNext': 'Start next cycle', 'heartRevealCycle.nextStarted': 'The next cycle has started', 'heartRevealCycle.setNextPhoto': 'Set the next photo', 'heartRevealCycle.writeNext': 'Write the next heart note', 'heartRevealCycle.shareError': 'Could not share the image. Please try again.', 'heartRevealCycle.shareUnsupported': 'This device cannot share the image directly, so it was downloaded instead.', 'heartRevealCycle.textPlacement': 'Text position', 'heartRevealCycle.placement.top-left': 'Top left', 'heartRevealCycle.placement.top-center': 'Top center', 'heartRevealCycle.placement.top-right': 'Top right', 'heartRevealCycle.placement.bottom-left': 'Bottom left', 'heartRevealCycle.placement.bottom-center': 'Bottom center', 'heartRevealCycle.placement.bottom-right': 'Bottom right',
  },
  ja: {
    'heartRevealCycle.ready': '七つの心ことばがそろいました', 'heartRevealCycle.choose': '心ことばを一つ選んでカードにする', 'heartRevealCycle.chooseTitle': '心ことばを選ぶ', 'heartRevealCycle.chooseHint': 'これまで残したすべての心ことばから一つ選べます。', 'heartRevealCycle.confirmTitle': '気持ちを確認', 'heartRevealCycle.back': '戻る', 'heartRevealCycle.generate': 'カードを作る', 'heartRevealCycle.generated': '気持ちのカードができました ✨', 'heartRevealCycle.finish': 'この気持ちを完成して、次の回を始める', 'heartRevealCycle.resetTitle': '次の回を始めますか？', 'heartRevealCycle.resetBody': 'この写真の表示は終わりますが、七つの心ことばは残ります。次の回は 0/7 から始まります。', 'heartRevealCycle.startNext': '次の回を始める', 'heartRevealCycle.nextStarted': '次の回を始めました', 'heartRevealCycle.setNextPhoto': '次の写真を設定', 'heartRevealCycle.writeNext': '次の心ことばを書く', 'heartRevealCycle.shareError': '画像を共有できませんでした。もう一度お試しください。', 'heartRevealCycle.shareUnsupported': 'この端末では画像を直接共有できないため、ダウンロードしました。', 'heartRevealCycle.textPlacement': '文字の位置', 'heartRevealCycle.placement.top-left': '左上', 'heartRevealCycle.placement.top-center': '上中央', 'heartRevealCycle.placement.top-right': '右上', 'heartRevealCycle.placement.bottom-left': '左下', 'heartRevealCycle.placement.bottom-center': '下中央', 'heartRevealCycle.placement.bottom-right': '右下',
  },
  ko: {
    'heartRevealCycle.ready': '일곱 마음 한마디가 완성되었어요', 'heartRevealCycle.choose': '마음 한마디를 골라 카드로 만들기', 'heartRevealCycle.chooseTitle': '마음 한마디 고르기', 'heartRevealCycle.chooseHint': '지금까지 남긴 모든 마음 한마디에서 하나를 고를 수 있어요.', 'heartRevealCycle.confirmTitle': '마음 확인하기', 'heartRevealCycle.back': '이전으로', 'heartRevealCycle.generate': '마음 카드 만들기', 'heartRevealCycle.generated': '마음 카드가 준비되었어요 ✨', 'heartRevealCycle.finish': '이 마음을 마치고 다음 회차 시작하기', 'heartRevealCycle.resetTitle': '다음 회차를 시작할까요?', 'heartRevealCycle.resetBody': '현재 사진의 드러내기는 끝나지만, 일곱 마음 한마디는 그대로 남아요. 다음 회차는 0/7부터 시작해요.', 'heartRevealCycle.startNext': '다음 회차 시작하기', 'heartRevealCycle.nextStarted': '다음 회차를 시작했어요', 'heartRevealCycle.setNextPhoto': '다음 사진 설정하기', 'heartRevealCycle.writeNext': '다음 마음 한마디 쓰기', 'heartRevealCycle.shareError': '이미지를 공유하지 못했어요. 다시 시도해 주세요.', 'heartRevealCycle.shareUnsupported': '이 기기에서는 이미지를 바로 공유할 수 없어 다운로드했어요.', 'heartRevealCycle.textPlacement': '글자 위치', 'heartRevealCycle.placement.top-left': '왼쪽 위', 'heartRevealCycle.placement.top-center': '위 가운데', 'heartRevealCycle.placement.top-right': '오른쪽 위', 'heartRevealCycle.placement.bottom-left': '왼쪽 아래', 'heartRevealCycle.placement.bottom-center': '아래 가운데', 'heartRevealCycle.placement.bottom-right': '오른쪽 아래',
  },
  es: {
    'heartRevealCycle.ready': 'Las siete frases del corazón están completas', 'heartRevealCycle.choose': 'Elige una frase para hacer una tarjeta', 'heartRevealCycle.chooseTitle': 'Elige una frase del corazón', 'heartRevealCycle.chooseHint': 'Puedes elegir una de todas las frases que has guardado.', 'heartRevealCycle.confirmTitle': 'Confirma tu mensaje', 'heartRevealCycle.back': 'Volver', 'heartRevealCycle.generate': 'Crear tarjeta', 'heartRevealCycle.generated': 'Tu tarjeta está lista ✨', 'heartRevealCycle.finish': 'Terminar este mensaje y empezar el siguiente ciclo', 'heartRevealCycle.resetTitle': '¿Empezar el siguiente ciclo?', 'heartRevealCycle.resetBody': 'El revelado de esta foto terminará, pero todas tus frases se conservarán. El siguiente ciclo empezará de nuevo en 0/7.', 'heartRevealCycle.startNext': 'Empezar siguiente ciclo', 'heartRevealCycle.nextStarted': 'El siguiente ciclo ha comenzado', 'heartRevealCycle.setNextPhoto': 'Configurar la siguiente foto', 'heartRevealCycle.writeNext': 'Escribe la siguiente frase', 'heartRevealCycle.shareError': 'No se pudo compartir la imagen. Inténtalo de nuevo.', 'heartRevealCycle.shareUnsupported': 'Este dispositivo no permite compartir la imagen directamente; se descargó en su lugar.', 'heartRevealCycle.textPlacement': 'Posición del texto', 'heartRevealCycle.placement.top-left': 'Arriba izquierda', 'heartRevealCycle.placement.top-center': 'Arriba centro', 'heartRevealCycle.placement.top-right': 'Arriba derecha', 'heartRevealCycle.placement.bottom-left': 'Abajo izquierda', 'heartRevealCycle.placement.bottom-center': 'Abajo centro', 'heartRevealCycle.placement.bottom-right': 'Abajo derecha',
  },
  fr: {
    'heartRevealCycle.ready': 'Les sept phrases du cœur sont terminées', 'heartRevealCycle.choose': 'Choisir une phrase pour en faire une carte', 'heartRevealCycle.chooseTitle': 'Choisissez une phrase du cœur', 'heartRevealCycle.chooseHint': 'Vous pouvez en choisir une parmi toutes les phrases que vous avez gardées.', 'heartRevealCycle.confirmTitle': 'Confirmez votre message', 'heartRevealCycle.back': 'Retour', 'heartRevealCycle.generate': 'Créer la carte', 'heartRevealCycle.generated': 'Votre carte est prête ✨', 'heartRevealCycle.finish': 'Terminer ce message et commencer le cycle suivant', 'heartRevealCycle.resetTitle': 'Commencer le cycle suivant ?', 'heartRevealCycle.resetBody': 'La révélation de cette photo se terminera, mais toutes vos phrases seront conservées. Le cycle suivant repartira de 0/7.', 'heartRevealCycle.startNext': 'Commencer le cycle suivant', 'heartRevealCycle.nextStarted': 'Le cycle suivant a commencé', 'heartRevealCycle.setNextPhoto': 'Définir la photo suivante', 'heartRevealCycle.writeNext': 'Écrire la prochaine phrase', 'heartRevealCycle.shareError': 'Impossible de partager l’image. Réessayez.', 'heartRevealCycle.shareUnsupported': 'Cet appareil ne peut pas partager l’image directement ; elle a été téléchargée.', 'heartRevealCycle.textPlacement': 'Position du texte', 'heartRevealCycle.placement.top-left': 'En haut à gauche', 'heartRevealCycle.placement.top-center': 'En haut au centre', 'heartRevealCycle.placement.top-right': 'En haut à droite', 'heartRevealCycle.placement.bottom-left': 'En bas à gauche', 'heartRevealCycle.placement.bottom-center': 'En bas au centre', 'heartRevealCycle.placement.bottom-right': 'En bas à droite',
  },
} as const
