import type { Locale } from './messages'

export const importAppDataMessages = {
  'zh-TW': {
    'settings.diary.importAppData': '匯入 App 資料', 'importAppData.description': '匯入先前保存的 App 資料，不包含照片。', 'importAppData.chooseFile': '選擇資料檔', 'importAppData.checking': '正在檢查資料檔…', 'importAppData.confirmTitle': '匯入 App 資料？', 'importAppData.confirmBody': '將把選取檔案中的資料合併到目前 App。現有資料不會整批刪除；相同紀錄會保留較新的版本。照片不會被匯入。', 'importAppData.confirm': '開始匯入', 'importAppData.summary': '新增 {added} 筆、更新 {updated} 筆、略過 {skipped} 筆。', 'importAppData.success': 'App 資料已匯入。', 'importAppData.noChanges': '資料已檢查，沒有需要匯入的新內容。', 'importAppData.error.fileRead': '無法讀取資料檔。', 'importAppData.error.invalidJson': '這不是有效的 JSON 資料檔。', 'importAppData.error.invalidFormat': '這不是星星戀愛日記資料檔。', 'importAppData.error.unsupportedVersion': '這個資料檔版本尚不支援。', 'importAppData.error.newerSchema': '這個資料檔來自較新的 App 版本。', 'importAppData.error.invalidData': '資料格式錯誤，無法匯入。', 'importAppData.error.tooLarge': '資料檔過大，無法匯入。', 'importAppData.error.write': '匯入失敗，請稍後再試。',
  },
  en: {
    'settings.diary.importAppData': 'Import app data', 'importAppData.description': 'Import previously saved app data. Photos are not included.', 'importAppData.chooseFile': 'Choose data file', 'importAppData.checking': 'Checking the data file…', 'importAppData.confirmTitle': 'Import app data?', 'importAppData.confirmBody': 'The selected data will be merged into this app. Existing data will not be erased; for matching records, the newer version is kept. Photos are not imported.', 'importAppData.confirm': 'Start import', 'importAppData.summary': '{added} added, {updated} updated, {skipped} skipped.', 'importAppData.success': 'App data imported.', 'importAppData.noChanges': 'The data was checked. There is nothing new to import.', 'importAppData.error.fileRead': 'Could not read the data file.', 'importAppData.error.invalidJson': 'This is not a valid JSON data file.', 'importAppData.error.invalidFormat': 'This is not a Starry Love Diary data file.', 'importAppData.error.unsupportedVersion': 'This data file version is not supported yet.', 'importAppData.error.newerSchema': 'This data file comes from a newer app version.', 'importAppData.error.invalidData': 'The data format is invalid and cannot be imported.', 'importAppData.error.tooLarge': 'This data file is too large to import.', 'importAppData.error.write': 'Import failed. Please try again later.',
  },
  ja: {
    'settings.diary.importAppData': 'アプリデータを取り込む', 'importAppData.description': '以前保存したアプリデータを取り込みます。写真は含まれません。', 'importAppData.chooseFile': 'データファイルを選ぶ', 'importAppData.checking': 'データファイルを確認しています…', 'importAppData.confirmTitle': 'アプリデータを取り込みますか？', 'importAppData.confirmBody': '選択したデータをこのアプリに統合します。既存データは削除されず、同じ記録ではより新しい版を残します。写真は取り込みません。', 'importAppData.confirm': '取り込みを開始', 'importAppData.summary': '{added}件追加、{updated}件更新、{skipped}件スキップしました。', 'importAppData.success': 'アプリデータを取り込みました。', 'importAppData.noChanges': 'データを確認しましたが、取り込む新しい内容はありません。', 'importAppData.error.fileRead': 'データファイルを読み込めませんでした。', 'importAppData.error.invalidJson': '有効な JSON データファイルではありません。', 'importAppData.error.invalidFormat': '星星恋愛日記のデータファイルではありません。', 'importAppData.error.unsupportedVersion': 'このデータファイルのバージョンにはまだ対応していません。', 'importAppData.error.newerSchema': 'このデータファイルは新しいアプリ版で作成されています。', 'importAppData.error.invalidData': 'データ形式が正しくないため、取り込めません。', 'importAppData.error.tooLarge': 'データファイルが大きすぎるため、取り込めません。', 'importAppData.error.write': '取り込みに失敗しました。後でもう一度お試しください。',
  },
  ko: {
    'settings.diary.importAppData': '앱 데이터 가져오기', 'importAppData.description': '이전에 저장한 앱 데이터를 가져옵니다. 사진은 포함되지 않습니다.', 'importAppData.chooseFile': '데이터 파일 선택', 'importAppData.checking': '데이터 파일을 확인하고 있어요…', 'importAppData.confirmTitle': '앱 데이터를 가져올까요?', 'importAppData.confirmBody': '선택한 데이터를 이 앱에 병합합니다. 기존 데이터는 지워지지 않으며, 같은 기록은 더 최신 버전을 유지합니다. 사진은 가져오지 않습니다.', 'importAppData.confirm': '가져오기 시작', 'importAppData.summary': '{added}개 추가, {updated}개 업데이트, {skipped}개 건너뜀.', 'importAppData.success': '앱 데이터를 가져왔어요.', 'importAppData.noChanges': '데이터를 확인했지만 가져올 새 내용이 없어요.', 'importAppData.error.fileRead': '데이터 파일을 읽을 수 없어요.', 'importAppData.error.invalidJson': '유효한 JSON 데이터 파일이 아니에요.', 'importAppData.error.invalidFormat': '별빛 연애 일기의 데이터 파일이 아니에요.', 'importAppData.error.unsupportedVersion': '이 데이터 파일 버전은 아직 지원하지 않아요.', 'importAppData.error.newerSchema': '이 데이터 파일은 더 새로운 앱 버전에서 만들어졌어요.', 'importAppData.error.invalidData': '데이터 형식이 올바르지 않아 가져올 수 없어요.', 'importAppData.error.tooLarge': '데이터 파일이 너무 커서 가져올 수 없어요.', 'importAppData.error.write': '가져오기에 실패했어요. 잠시 후 다시 시도해 주세요.',
  },
  es: {
    'settings.diary.importAppData': 'Importar datos de la app', 'importAppData.description': 'Importa datos guardados anteriormente en la app. No incluye fotos.', 'importAppData.chooseFile': 'Elegir archivo de datos', 'importAppData.checking': 'Comprobando el archivo de datos…', 'importAppData.confirmTitle': '¿Importar datos de la app?', 'importAppData.confirmBody': 'Los datos seleccionados se combinarán con esta app. Los datos existentes no se borrarán; en los registros coincidentes se conservará la versión más reciente. Las fotos no se importan.', 'importAppData.confirm': 'Iniciar importación', 'importAppData.summary': '{added} añadidos, {updated} actualizados, {skipped} omitidos.', 'importAppData.success': 'Datos de la app importados.', 'importAppData.noChanges': 'Se comprobaron los datos. No hay contenido nuevo para importar.', 'importAppData.error.fileRead': 'No se pudo leer el archivo de datos.', 'importAppData.error.invalidJson': 'No es un archivo de datos JSON válido.', 'importAppData.error.invalidFormat': 'No es un archivo de datos de Starry Love Diary.', 'importAppData.error.unsupportedVersion': 'Esta versión del archivo de datos aún no es compatible.', 'importAppData.error.newerSchema': 'Este archivo de datos procede de una versión más reciente de la app.', 'importAppData.error.invalidData': 'El formato de datos no es válido y no se puede importar.', 'importAppData.error.tooLarge': 'Este archivo de datos es demasiado grande para importarlo.', 'importAppData.error.write': 'La importación falló. Inténtalo de nuevo más tarde.',
  },
  fr: {
    'settings.diary.importAppData': 'Importer les données de l’app', 'importAppData.description': 'Importe des données de l’app enregistrées auparavant. Les photos ne sont pas incluses.', 'importAppData.chooseFile': 'Choisir un fichier de données', 'importAppData.checking': 'Vérification du fichier de données…', 'importAppData.confirmTitle': 'Importer les données de l’app ?', 'importAppData.confirmBody': 'Les données sélectionnées seront fusionnées avec cette app. Les données existantes ne seront pas effacées ; pour les enregistrements correspondants, la version la plus récente est conservée. Les photos ne sont pas importées.', 'importAppData.confirm': 'Commencer l’importation', 'importAppData.summary': '{added} ajoutés, {updated} mis à jour, {skipped} ignorés.', 'importAppData.success': 'Données de l’app importées.', 'importAppData.noChanges': 'Les données ont été vérifiées. Aucun nouveau contenu à importer.', 'importAppData.error.fileRead': 'Impossible de lire le fichier de données.', 'importAppData.error.invalidJson': 'Ce fichier de données JSON n’est pas valide.', 'importAppData.error.invalidFormat': 'Ce n’est pas un fichier de données Starry Love Diary.', 'importAppData.error.unsupportedVersion': 'Cette version du fichier de données n’est pas encore prise en charge.', 'importAppData.error.newerSchema': 'Ce fichier de données provient d’une version plus récente de l’app.', 'importAppData.error.invalidData': 'Le format des données est invalide et ne peut pas être importé.', 'importAppData.error.tooLarge': 'Ce fichier de données est trop volumineux pour être importé.', 'importAppData.error.write': 'Échec de l’importation. Réessayez plus tard.',
  },
} as const satisfies Record<Locale, Record<string, string>>
