import type { Locale } from './messages'

const legacyImportAppDataMessages = {
  'zh-TW': {
    'settings.diary.importAppData': '匯入 App 資料', 'settings.diary.restoreAppData': '匯入 App 資料', 'settings.diary.mergeAppData': '合併 App 資料', 'restoreAppData.description': '從備份完整還原 App 資料。', 'restoreAppData.chooseFile': '選擇備份檔', 'restoreAppData.checking': '正在檢查備份檔…', 'restoreAppData.confirmTitle': '匯入 App 資料？', 'restoreAppData.confirmBody': '將以這份備份資料取代目前 App 中的資料。備份建立後新增或修改的資料可能會被覆蓋或移除。照片不包含在 App 資料備份中，目前手機的 App 設定會保留。建議先匯出目前資料作為備份。', 'restoreAppData.confirm': '確認匯入', 'restoreAppData.restoring': '正在還原…', 'restoreAppData.summary': '備份時間：{exportedAt}。日記 {diaries} 篇、心情 {moods} 筆、星星 {stars} 顆、重要日期 {dates} 筆、回憶 {moments} 筆、記得你卡片 {cards} 張。', 'restoreAppData.success': 'App 資料已還原完成。', 'restoreAppData.error': '資料還原失敗，請稍後再試。', 'importAppData.description': '將備份資料與目前 App 資料合併。', 'importAppData.chooseFile': '選擇資料檔', 'importAppData.checking': '正在檢查資料檔…', 'importAppData.confirmTitle': '合併 App 資料？', 'importAppData.confirmBody': '將備份資料與目前 App 資料合併。相同紀錄會保留較新的版本，目前已有的其他資料不會被整批刪除。照片不會被匯入。', 'importAppData.confirm': '開始合併', 'importAppData.summary': '新增 {added} 筆、更新 {updated} 筆、略過 {skipped} 筆。', 'importAppData.success': 'App 資料已合併。', 'importAppData.noChanges': '資料已檢查，沒有需要合併的新內容。', 'importAppData.error.fileRead': '無法讀取資料檔。', 'importAppData.error.invalidJson': '這不是有效的 JSON 資料檔。', 'importAppData.error.invalidFormat': '這不是星星戀愛日記資料檔。', 'importAppData.error.unsupportedVersion': '這個資料檔版本尚不支援。', 'importAppData.error.newerSchema': '這個資料檔來自較新的 App 版本。', 'importAppData.error.invalidData': '資料格式錯誤，無法匯入。', 'importAppData.error.tooLarge': '資料檔過大，無法匯入。', 'importAppData.error.write': '合併失敗，請稍後再試。',
  },
  en: {
    'settings.diary.restoreAppData': 'Restore from Backup', 'restoreAppData.description': 'Replace app data from a backup.', 'restoreAppData.chooseFile': 'Choose backup file', 'restoreAppData.checking': 'Checking the backup…', 'restoreAppData.confirmTitle': 'Restore from Backup?', 'restoreAppData.confirmBody': 'This will replace your current app data with the backup. Data added or changed after the backup will be lost. Photos are not included, and this device’s app settings will be kept. Export your current data first if you need a backup.', 'restoreAppData.confirm': 'Restore', 'restoreAppData.restoring': 'Restoring…', 'restoreAppData.summary': 'Backup: {exportedAt}. Diaries {diaries}, moods {moods}, stars {stars}, important dates {dates}, moments {moments}, cards {cards}.', 'restoreAppData.success': 'App data restored.', 'restoreAppData.error': 'Could not restore app data. Please try again.',
    'settings.diary.importAppData': 'Import app data', 'importAppData.description': 'Import previously saved app data. Photos are not included.', 'importAppData.chooseFile': 'Choose data file', 'importAppData.checking': 'Checking the data file…', 'importAppData.confirmTitle': 'Import app data?', 'importAppData.confirmBody': 'The selected data will be merged into this app. Existing data will not be erased; for matching records, the newer version is kept. Photos are not imported.', 'importAppData.confirm': 'Start import', 'importAppData.summary': '{added} added, {updated} updated, {skipped} skipped.', 'importAppData.success': 'App data imported.', 'importAppData.noChanges': 'The data was checked. There is nothing new to import.', 'importAppData.error.fileRead': 'Could not read the data file.', 'importAppData.error.invalidJson': 'This is not a valid JSON data file.', 'importAppData.error.invalidFormat': 'This is not a Starry Love Diary data file.', 'importAppData.error.unsupportedVersion': 'This data file version is not supported yet.', 'importAppData.error.newerSchema': 'This data file comes from a newer app version.', 'importAppData.error.invalidData': 'The data format is invalid and cannot be imported.', 'importAppData.error.tooLarge': 'This data file is too large to import.', 'importAppData.error.write': 'Import failed. Please try again later.',
  },
  ja: {
    'settings.diary.restoreAppData': 'アプリデータを復元', 'settings.diary.mergeAppData': 'アプリデータを統合', 'restoreAppData.description': 'バックアップからアプリデータを完全に復元します。', 'restoreAppData.chooseFile': 'バックアップを選ぶ', 'restoreAppData.checking': 'バックアップを確認しています…', 'restoreAppData.confirmTitle': 'アプリデータを復元しますか？', 'restoreAppData.confirmBody': 'このバックアップで現在のアプリデータを置き換えます。以降に追加・変更したデータは上書きまたは削除される場合があります。写真は含まれず、この端末の設定は保持されます。必要なら先に現在のデータを書き出してください。', 'restoreAppData.confirm': '復元する', 'restoreAppData.restoring': '復元中…', 'restoreAppData.summary': 'バックアップ：{exportedAt}。日記 {diaries}件、気分 {moods}件、星 {stars}個、重要な日 {dates}件、思い出 {moments}件、カード {cards}件。', 'restoreAppData.success': 'アプリデータを復元しました。', 'restoreAppData.error': 'アプリデータを復元できませんでした。',
    'settings.diary.importAppData': 'アプリデータを取り込む', 'importAppData.description': '以前保存したアプリデータを取り込みます。写真は含まれません。', 'importAppData.chooseFile': 'データファイルを選ぶ', 'importAppData.checking': 'データファイルを確認しています…', 'importAppData.confirmTitle': 'アプリデータを取り込みますか？', 'importAppData.confirmBody': '選択したデータをこのアプリに統合します。既存データは削除されず、同じ記録ではより新しい版を残します。写真は取り込みません。', 'importAppData.confirm': '取り込みを開始', 'importAppData.summary': '{added}件追加、{updated}件更新、{skipped}件スキップしました。', 'importAppData.success': 'アプリデータを取り込みました。', 'importAppData.noChanges': 'データを確認しましたが、取り込む新しい内容はありません。', 'importAppData.error.fileRead': 'データファイルを読み込めませんでした。', 'importAppData.error.invalidJson': '有効な JSON データファイルではありません。', 'importAppData.error.invalidFormat': '星星恋愛日記のデータファイルではありません。', 'importAppData.error.unsupportedVersion': 'このデータファイルのバージョンにはまだ対応していません。', 'importAppData.error.newerSchema': 'このデータファイルは新しいアプリ版で作成されています。', 'importAppData.error.invalidData': 'データ形式が正しくないため、取り込めません。', 'importAppData.error.tooLarge': 'データファイルが大きすぎるため、取り込めません。', 'importAppData.error.write': '取り込みに失敗しました。後でもう一度お試しください。',
  },
  ko: {
    'settings.diary.restoreAppData': '앱 데이터 복원', 'settings.diary.mergeAppData': '앱 데이터 병합', 'restoreAppData.description': '백업에서 앱 데이터를 완전히 복원합니다.', 'restoreAppData.chooseFile': '백업 파일 선택', 'restoreAppData.checking': '백업 파일을 확인하고 있어요…', 'restoreAppData.confirmTitle': '앱 데이터를 복원할까요?', 'restoreAppData.confirmBody': '이 백업으로 현재 앱 데이터를 대체합니다. 백업 이후 추가하거나 변경한 데이터는 덮어써지거나 삭제될 수 있습니다. 사진은 포함되지 않으며 이 기기의 앱 설정은 유지됩니다. 필요하면 먼저 현재 데이터를 내보내세요.', 'restoreAppData.confirm': '복원', 'restoreAppData.restoring': '복원 중…', 'restoreAppData.summary': '백업: {exportedAt}. 일기 {diaries}개, 기분 {moods}개, 별 {stars}개, 중요한 날 {dates}개, 추억 {moments}개, 카드 {cards}개.', 'restoreAppData.success': '앱 데이터를 복원했어요.', 'restoreAppData.error': '앱 데이터를 복원할 수 없어요.',
    'settings.diary.importAppData': '앱 데이터 가져오기', 'importAppData.description': '이전에 저장한 앱 데이터를 가져옵니다. 사진은 포함되지 않습니다.', 'importAppData.chooseFile': '데이터 파일 선택', 'importAppData.checking': '데이터 파일을 확인하고 있어요…', 'importAppData.confirmTitle': '앱 데이터를 가져올까요?', 'importAppData.confirmBody': '선택한 데이터를 이 앱에 병합합니다. 기존 데이터는 지워지지 않으며, 같은 기록은 더 최신 버전을 유지합니다. 사진은 가져오지 않습니다.', 'importAppData.confirm': '가져오기 시작', 'importAppData.summary': '{added}개 추가, {updated}개 업데이트, {skipped}개 건너뜀.', 'importAppData.success': '앱 데이터를 가져왔어요.', 'importAppData.noChanges': '데이터를 확인했지만 가져올 새 내용이 없어요.', 'importAppData.error.fileRead': '데이터 파일을 읽을 수 없어요.', 'importAppData.error.invalidJson': '유효한 JSON 데이터 파일이 아니에요.', 'importAppData.error.invalidFormat': '별빛 연애 일기의 데이터 파일이 아니에요.', 'importAppData.error.unsupportedVersion': '이 데이터 파일 버전은 아직 지원하지 않아요.', 'importAppData.error.newerSchema': '이 데이터 파일은 더 새로운 앱 버전에서 만들어졌어요.', 'importAppData.error.invalidData': '데이터 형식이 올바르지 않아 가져올 수 없어요.', 'importAppData.error.tooLarge': '데이터 파일이 너무 커서 가져올 수 없어요.', 'importAppData.error.write': '가져오기에 실패했어요. 잠시 후 다시 시도해 주세요.',
  },
  es: {
    'settings.diary.restoreAppData': 'Restaurar datos de la app', 'settings.diary.mergeAppData': 'Combinar datos de la app', 'restoreAppData.description': 'Restaura por completo los datos de la app desde una copia.', 'restoreAppData.chooseFile': 'Elegir copia de seguridad', 'restoreAppData.checking': 'Comprobando la copia…', 'restoreAppData.confirmTitle': '¿Restaurar datos de la app?', 'restoreAppData.confirmBody': 'Esta copia sustituirá los datos actuales de la app. Los datos añadidos o modificados después podrían sobrescribirse o eliminarse. Las fotos no están incluidas y se conservarán los ajustes de este dispositivo. Exporta primero tus datos actuales si necesitas una copia.', 'restoreAppData.confirm': 'Restaurar', 'restoreAppData.restoring': 'Restaurando…', 'restoreAppData.summary': 'Copia: {exportedAt}. Diarios {diaries}, estados de ánimo {moods}, estrellas {stars}, fechas importantes {dates}, recuerdos {moments}, tarjetas {cards}.', 'restoreAppData.success': 'Datos de la app restaurados.', 'restoreAppData.error': 'No se pudieron restaurar los datos de la app.',
    'settings.diary.importAppData': 'Importar datos de la app', 'importAppData.description': 'Importa datos guardados anteriormente en la app. No incluye fotos.', 'importAppData.chooseFile': 'Elegir archivo de datos', 'importAppData.checking': 'Comprobando el archivo de datos…', 'importAppData.confirmTitle': '¿Importar datos de la app?', 'importAppData.confirmBody': 'Los datos seleccionados se combinarán con esta app. Los datos existentes no se borrarán; en los registros coincidentes se conservará la versión más reciente. Las fotos no se importan.', 'importAppData.confirm': 'Iniciar importación', 'importAppData.summary': '{added} añadidos, {updated} actualizados, {skipped} omitidos.', 'importAppData.success': 'Datos de la app importados.', 'importAppData.noChanges': 'Se comprobaron los datos. No hay contenido nuevo para importar.', 'importAppData.error.fileRead': 'No se pudo leer el archivo de datos.', 'importAppData.error.invalidJson': 'No es un archivo de datos JSON válido.', 'importAppData.error.invalidFormat': 'No es un archivo de datos de Starry Love Diary.', 'importAppData.error.unsupportedVersion': 'Esta versión del archivo de datos aún no es compatible.', 'importAppData.error.newerSchema': 'Este archivo de datos procede de una versión más reciente de la app.', 'importAppData.error.invalidData': 'El formato de datos no es válido y no se puede importar.', 'importAppData.error.tooLarge': 'Este archivo de datos es demasiado grande para importarlo.', 'importAppData.error.write': 'La importación falló. Inténtalo de nuevo más tarde.',
  },
  fr: {
    'settings.diary.restoreAppData': 'Restaurer les données de l’app', 'settings.diary.mergeAppData': 'Fusionner les données de l’app', 'restoreAppData.description': 'Restaure entièrement les données de l’app depuis une sauvegarde.', 'restoreAppData.chooseFile': 'Choisir une sauvegarde', 'restoreAppData.checking': 'Vérification de la sauvegarde…', 'restoreAppData.confirmTitle': 'Restaurer les données de l’app ?', 'restoreAppData.confirmBody': 'Cette sauvegarde remplacera les données actuelles de l’app. Les données ajoutées ou modifiées après la sauvegarde peuvent être écrasées ou supprimées. Les photos ne sont pas incluses et les réglages de cet appareil seront conservés. Exportez d’abord vos données actuelles si nécessaire.', 'restoreAppData.confirm': 'Restaurer', 'restoreAppData.restoring': 'Restauration…', 'restoreAppData.summary': 'Sauvegarde : {exportedAt}. Journaux {diaries}, humeurs {moods}, étoiles {stars}, dates importantes {dates}, souvenirs {moments}, cartes {cards}.', 'restoreAppData.success': 'Données de l’app restaurées.', 'restoreAppData.error': 'Impossible de restaurer les données de l’app.',
    'settings.diary.importAppData': 'Importer les données de l’app', 'importAppData.description': 'Importe des données de l’app enregistrées auparavant. Les photos ne sont pas incluses.', 'importAppData.chooseFile': 'Choisir un fichier de données', 'importAppData.checking': 'Vérification du fichier de données…', 'importAppData.confirmTitle': 'Importer les données de l’app ?', 'importAppData.confirmBody': 'Les données sélectionnées seront fusionnées avec cette app. Les données existantes ne seront pas effacées ; pour les enregistrements correspondants, la version la plus récente est conservée. Les photos ne sont pas importées.', 'importAppData.confirm': 'Commencer l’importation', 'importAppData.summary': '{added} ajoutés, {updated} mis à jour, {skipped} ignorés.', 'importAppData.success': 'Données de l’app importées.', 'importAppData.noChanges': 'Les données ont été vérifiées. Aucun nouveau contenu à importer.', 'importAppData.error.fileRead': 'Impossible de lire le fichier de données.', 'importAppData.error.invalidJson': 'Ce fichier de données JSON n’est pas valide.', 'importAppData.error.invalidFormat': 'Ce n’est pas un fichier de données Starry Love Diary.', 'importAppData.error.unsupportedVersion': 'Cette version du fichier de données n’est pas encore prise en charge.', 'importAppData.error.newerSchema': 'Ce fichier de données provient d’une version plus récente de l’app.', 'importAppData.error.invalidData': 'Le format des données est invalide et ne peut pas être importé.', 'importAppData.error.tooLarge': 'Ce fichier de données est trop volumineux pour être importé.', 'importAppData.error.write': 'Échec de l’importation. Réessayez plus tard.',
  },
} as const satisfies Record<Locale, Record<string, string>>

function withoutRetiredMergeLabel<T extends Record<string, string>>({ ['settings.diary.mergeAppData']: retired, ...messages }: T) { void retired; return messages }

export const importAppDataMessages = {
  'zh-TW': { ...withoutRetiredMergeLabel(legacyImportAppDataMessages['zh-TW']), 'settings.diary.importAppData': '\u5f9e\u5099\u4efd\u9084\u539f', 'settings.diary.restoreAppData': '\u5f9e\u5099\u4efd\u9084\u539f', 'restoreAppData.description': '\u4ee5\u5099\u4efd\u5b8c\u6574\u53d6\u4ee3 App \u8cc7\u6599\u3002', 'restoreAppData.confirmTitle': '\u5f9e\u5099\u4efd\u9084\u539f\uff1f', 'restoreAppData.confirm': '\u78ba\u8a8d\u9084\u539f' },
  en: { ...withoutRetiredMergeLabel(legacyImportAppDataMessages.en), 'settings.diary.restoreAppData': 'Restore from Backup', 'restoreAppData.description': 'Replace app data from a backup.', 'restoreAppData.confirmTitle': 'Restore from Backup?', 'restoreAppData.confirmBody': 'This will replace your current app data with the backup. Data added or changed after the backup will be lost. Photos are not included, and this device’s app settings will be kept. Export your current data first if you need a backup.' },
  ja: { ...withoutRetiredMergeLabel(legacyImportAppDataMessages.ja), 'settings.diary.restoreAppData': '\u30d0\u30c3\u30af\u30a2\u30c3\u30d7\u304b\u3089\u5fa9\u5143' },
  ko: { ...withoutRetiredMergeLabel(legacyImportAppDataMessages.ko), 'settings.diary.restoreAppData': '\ubc31\uc5c5\uc5d0\uc11c \ubcf5\uc6d0' },
  es: { ...withoutRetiredMergeLabel(legacyImportAppDataMessages.es), 'settings.diary.restoreAppData': 'Restaurar desde copia' },
  fr: { ...withoutRetiredMergeLabel(legacyImportAppDataMessages.fr), 'settings.diary.restoreAppData': 'Restaurer depuis une sauvegarde' },
} as const satisfies Record<Locale, Record<string, string>>
