import type { Locale } from './messages'
export const memoryMomentPhotoMessages = {
  'zh-TW': { 'momentPhoto.add':'加入照片','momentPhoto.later':'照片可之後再加入','momentPhoto.change':'更換照片','momentPhoto.adjust':'調整照片','momentPhoto.remove':'移除照片','momentPhoto.removeTitle':'確定移除照片？','momentPhoto.removeBody':'只會移除這則時刻的照片，文字和日期會保留。','momentPhoto.importFailed':'照片匯入失敗，請再試一次。','momentPhoto.empty':'尚未加入照片','momentPhoto.alt':'我們的時刻照片','momentPhoto.save':'儲存這個時刻' },
  en: { 'momentPhoto.add':'Add photo','momentPhoto.later':'A photo can be added later','momentPhoto.change':'Replace photo','momentPhoto.adjust':'Adjust photo','momentPhoto.remove':'Remove photo','momentPhoto.removeTitle':'Remove this photo?','momentPhoto.removeBody':'Only this moment’s photo will be removed. Its text and date will stay.','momentPhoto.importFailed':'The photo could not be imported. Please try again.','momentPhoto.empty':'No photo added yet','momentPhoto.alt':'Our moment photo','momentPhoto.save':'Save this moment' },
  ja: { 'momentPhoto.add':'写真を追加','momentPhoto.later':'写真はあとから追加できます','momentPhoto.change':'写真を変更','momentPhoto.adjust':'写真を調整','momentPhoto.remove':'写真を削除','momentPhoto.removeTitle':'この写真を削除しますか？','momentPhoto.removeBody':'この時刻の写真だけを削除します。文章と日付は残ります。','momentPhoto.importFailed':'写真を読み込めませんでした。もう一度お試しください。','momentPhoto.empty':'写真はまだありません','momentPhoto.alt':'ふたりの時刻の写真','momentPhoto.save':'この時刻を保存' },
  ko: { 'momentPhoto.add':'사진 추가','momentPhoto.later':'사진은 나중에 추가할 수 있어요','momentPhoto.change':'사진 바꾸기','momentPhoto.adjust':'사진 조정','momentPhoto.remove':'사진 삭제','momentPhoto.removeTitle':'이 사진을 삭제할까요?','momentPhoto.removeBody':'이 순간의 사진만 삭제됩니다. 글과 날짜는 유지돼요.','momentPhoto.importFailed':'사진을 가져오지 못했어요. 다시 시도해 주세요.','momentPhoto.empty':'아직 사진이 없어요','momentPhoto.alt':'우리의 순간 사진','momentPhoto.save':'이 순간 저장' },
  es: { 'momentPhoto.add':'Añadir foto','momentPhoto.later':'Puedes añadir una foto más adelante','momentPhoto.change':'Cambiar foto','momentPhoto.adjust':'Ajustar foto','momentPhoto.remove':'Quitar foto','momentPhoto.removeTitle':'¿Quitar esta foto?','momentPhoto.removeBody':'Solo se quitará la foto de este momento. El texto y la fecha se conservarán.','momentPhoto.importFailed':'No se pudo importar la foto. Inténtalo de nuevo.','momentPhoto.empty':'Aún no hay foto','momentPhoto.alt':'Foto de nuestro momento','momentPhoto.save':'Guardar este momento' },
  fr: { 'momentPhoto.add':'Ajouter une photo','momentPhoto.later':'Vous pourrez ajouter une photo plus tard','momentPhoto.change':'Changer la photo','momentPhoto.adjust':'Ajuster la photo','momentPhoto.remove':'Retirer la photo','momentPhoto.removeTitle':'Retirer cette photo ?','momentPhoto.removeBody':'Seule la photo de ce moment sera retirée. Le texte et la date seront conservés.','momentPhoto.importFailed':'Impossible d’importer la photo. Réessayez.','momentPhoto.empty':'Aucune photo ajoutée','momentPhoto.alt':'Photo de notre moment','momentPhoto.save':'Enregistrer ce moment' },
} as const satisfies Record<Locale, Record<string,string>>
