import type { Locale } from './messages'
export const messageShareMessages = {
  'zh-TW': { 'our.message.empty':'有些話，想說的時候再寫下來。','our.message.write':'寫下想對對方說的話','our.message.emptyRequired':'內容不能是空白。','our.message.copied':'已複製，可以貼到你想分享的地方。','our.message.shareError':'分享失敗，請稍後再試。','our.message.shared':'已開啟分享。' },
  en: { 'our.message.empty':'It is okay if some words have not been spoken yet.','our.message.write':'Write what you want to say to them','our.message.emptyRequired':'The message cannot be blank.','our.message.copied':'Copied. You can paste it wherever you would like to share it.','our.message.shareError':'Sharing failed. Please try again later.','our.message.shared':'Sharing is open.' },
  ja: { 'our.message.empty':'まだ口にしていない言葉があっても大丈夫。','our.message.write':'相手に伝えたいことを書く','our.message.emptyRequired':'内容を空白にはできません。','our.message.copied':'コピーしました。共有したい場所に貼り付けられます。','our.message.shareError':'共有できませんでした。後でもう一度お試しください。','our.message.shared':'共有を開きました。' },
  ko: { 'our.message.empty':'아직 꺼내지 못한 말이 있어도 괜찮아요.','our.message.write':'상대에게 전하고 싶은 말을 적어 보세요','our.message.emptyRequired':'내용은 비워 둘 수 없어요.','our.message.copied':'복사했어요. 공유하고 싶은 곳에 붙여 넣을 수 있어요.','our.message.shareError':'공유하지 못했어요. 잠시 후 다시 시도해 주세요.','our.message.shared':'공유를 열었어요.' },
  es: { 'our.message.empty':'Está bien que algunas palabras aún no hayan salido.','our.message.write':'Escribe lo que quieres decirle a esa persona','our.message.emptyRequired':'El mensaje no puede estar vacío.','our.message.copied':'Copiado. Puedes pegarlo donde quieras compartirlo.','our.message.shareError':'No se pudo compartir. Inténtalo de nuevo más tarde.','our.message.shared':'Se abrió la opción de compartir.' },
  fr: { 'our.message.empty':'Ce n’est pas grave si certains mots ne sont pas encore sortis.','our.message.write':'Écrivez ce que vous voulez dire à cette personne','our.message.emptyRequired':'Le message ne peut pas être vide.','our.message.copied':'Copié. Vous pouvez le coller où vous souhaitez le partager.','our.message.shareError':'Le partage a échoué. Réessayez plus tard.','our.message.shared':'Le partage est ouvert.' },
} as const satisfies Record<Locale, Record<string,string>>
