import type { Locale } from './messages'

const zhTW = {
  'messageV1.prompt':'今天，有什麼想對他說？','messageV1.choose':'選擇一種心意','messageV1.content':'寫下想說的話','messageV1.save':'保存這份心意','messageV1.saved':'這份心意已留在我們的回憶裡。','messageV1.done':'完成','messageV1.card':'做成星光小卡','messageV1.history':'查看歷史總覽','messageV1.historyTitle':'想對你說 · {count} 則','messageV1.all':'全部','messageV1.month':'本月','messageV1.year':'本年','messageV1.empty':'這個範圍還沒有留下心意。','messageV1.note':'這些數字沒有好壞，只是記錄你曾經說過的心意。','messageV1.back':'返回寫一份心意','messageV1.edit':'編輯','messageV1.delete':'刪除','messageV1.deleteTitle':'刪除這份心意？','messageV1.deleteBody':'刪除後將無法從這個裝置復原。','messageV1.saveEdit':'保存修改','messageV1.full':'查看完整內容',
  'messageV1.type.miss_you':'今天有點想你','messageV1.type.thank_you':'今天謝謝你','messageV1.type.sorry':'對不起啦','messageV1.type.dont_be_mad':'不要生氣了嘛','messageV1.type.tell_you':'有一句話想告訴你','messageV1.type.invite_out':'想約你出去','messageV1.type.free_message':'我想說的話',
  'messageV1.hint.miss_you':'想他就寫吧，又沒叫你現在傳。🐈‍⬛','messageV1.hint.thank_you':'有些謝謝，說出來會比放在心裡更暖。','messageV1.hint.sorry':'道歉不用寫作文，真心比較重要。','messageV1.hint.dont_be_mad':'本黑喵先躲遠一點，你自己哄。🐈‍⬛','messageV1.hint.tell_you':'有些話，先寫下來就好。','messageV1.hint.invite_out':'勇敢一點，最壞還有本黑喵陪你。🐈‍⬛','messageV1.hint.free_message':'這裡沒有人改你的作文，想寫什麼就寫什麼。',
} as const
type Key = keyof typeof zhTW
type Catalog = Record<Key,string>
const common = (v: Partial<Catalog>) => ({...zhTW,...v}) as Catalog
export const messageToYouV1Messages: Record<Locale,Catalog> = {
  'zh-TW':zhTW,
  en:common({'messageV1.prompt':'What would you like to tell them today?','messageV1.choose':'Choose a feeling','messageV1.content':'Write what you want to say','messageV1.save':'Save this message','messageV1.saved':'This message is now part of your memories.','messageV1.done':'Done','messageV1.card':'Make a starlight card','messageV1.history':'View message history','messageV1.historyTitle':'Messages for You · {count}','messageV1.all':'All','messageV1.month':'This month','messageV1.year':'This year','messageV1.empty':'No messages in this range yet.','messageV1.note':'These numbers are not good or bad. They simply remember what you have wanted to say.','messageV1.back':'Write another message','messageV1.edit':'Edit','messageV1.delete':'Delete','messageV1.deleteTitle':'Delete this message?','messageV1.deleteBody':'It cannot be restored on this device.','messageV1.saveEdit':'Save changes','messageV1.full':'View full message','messageV1.type.miss_you':'Missing You Today','messageV1.type.thank_you':'Thank You Today','messageV1.type.sorry':'I’m Sorry','messageV1.type.dont_be_mad':'Please Don’t Be Mad','messageV1.type.tell_you':'Something I Want to Tell You','messageV1.type.invite_out':'Want to Go Out?','messageV1.type.free_message':'What I Want to Say','messageV1.hint.miss_you':'Write it down. You do not have to send it now. 🐈‍⬛','messageV1.hint.thank_you':'Some thanks feel warmer when they are put into words.','messageV1.hint.sorry':'An apology does not need to be an essay. Sincerity matters more.','messageV1.hint.dont_be_mad':'This black cat will step aside while you make up. 🐈‍⬛','messageV1.hint.tell_you':'Sometimes it is enough to write the words down first.','messageV1.hint.invite_out':'Be a little brave. This black cat is still here either way. 🐈‍⬛','messageV1.hint.free_message':'No one is grading your writing here. Say it your way.'}),
  ja:common({'messageV1.prompt':'今日は、何を伝えたい？','messageV1.choose':'気持ちを選ぶ','messageV1.content':'伝えたいことを書く','messageV1.save':'この気持ちを保存','messageV1.saved':'この気持ちを、ふたりの思い出に残しました。','messageV1.done':'完了','messageV1.card':'星明かりのカードを作る','messageV1.history':'履歴を見る','messageV1.historyTitle':'あなたに伝えたいこと · {count}件','messageV1.all':'すべて','messageV1.month':'今月','messageV1.year':'今年','messageV1.empty':'この期間の記録はまだありません。','messageV1.note':'数字に良し悪しはありません。伝えたいと思った気持ちの記録です。','messageV1.back':'新しい気持ちを書く','messageV1.edit':'編集','messageV1.delete':'削除','messageV1.deleteTitle':'この気持ちを削除しますか？','messageV1.deleteBody':'削除すると、この端末では元に戻せません。','messageV1.saveEdit':'変更を保存','messageV1.full':'全文を見る','messageV1.type.miss_you':'今日は少し会いたい','messageV1.type.thank_you':'今日はありがとう','messageV1.type.sorry':'ごめんね','messageV1.type.dont_be_mad':'怒らないでね','messageV1.type.tell_you':'伝えたいことがある','messageV1.type.invite_out':'一緒に出かけたい','messageV1.type.free_message':'私が伝えたいこと'}),
  ko:common({'messageV1.prompt':'오늘은 어떤 말을 전하고 싶나요?','messageV1.choose':'마음 고르기','messageV1.content':'하고 싶은 말 쓰기','messageV1.save':'이 마음 저장하기','messageV1.saved':'이 마음을 우리의 추억에 남겼어요.','messageV1.done':'완료','messageV1.card':'별빛 카드 만들기','messageV1.history':'지난 마음 보기','messageV1.historyTitle':'너에게 하고 싶은 말 · {count}개','messageV1.all':'전체','messageV1.month':'이번 달','messageV1.year':'올해','messageV1.empty':'이 기간에는 아직 남긴 마음이 없어요.','messageV1.note':'이 숫자에는 좋고 나쁨이 없어요. 전하고 싶었던 마음의 기록일 뿐이에요.','messageV1.back':'새 마음 쓰기','messageV1.edit':'수정','messageV1.delete':'삭제','messageV1.deleteTitle':'이 마음을 삭제할까요?','messageV1.deleteBody':'삭제하면 이 기기에서 복원할 수 없어요.','messageV1.saveEdit':'수정 저장','messageV1.full':'전체 내용 보기','messageV1.type.miss_you':'오늘 조금 보고 싶어','messageV1.type.thank_you':'오늘 고마워','messageV1.type.sorry':'미안해','messageV1.type.dont_be_mad':'화내지 말아 줘','messageV1.type.tell_you':'하고 싶은 말이 있어','messageV1.type.invite_out':'같이 나가고 싶어','messageV1.type.free_message':'내가 하고 싶은 말'}),
  es:common({'messageV1.prompt':'¿Qué te gustaría decirle hoy?','messageV1.choose':'Elige un sentimiento','messageV1.content':'Escribe lo que quieres decir','messageV1.save':'Guardar este sentimiento','messageV1.saved':'Este sentimiento ya forma parte de vuestros recuerdos.','messageV1.done':'Listo','messageV1.card':'Crear tarjeta de luz estelar','messageV1.history':'Ver historial','messageV1.historyTitle':'Lo que quiero decirte · {count}','messageV1.all':'Todo','messageV1.month':'Este mes','messageV1.year':'Este año','messageV1.empty':'Aún no hay mensajes en este periodo.','messageV1.note':'Estas cifras no son buenas ni malas; solo recuerdan lo que alguna vez quisiste decir.','messageV1.back':'Escribir otro mensaje','messageV1.edit':'Editar','messageV1.delete':'Eliminar','messageV1.deleteTitle':'¿Eliminar este mensaje?','messageV1.deleteBody':'No podrá recuperarse en este dispositivo.','messageV1.saveEdit':'Guardar cambios','messageV1.full':'Ver mensaje completo','messageV1.type.miss_you':'Hoy te echo de menos','messageV1.type.thank_you':'Gracias por hoy','messageV1.type.sorry':'Lo siento','messageV1.type.dont_be_mad':'No te enfades','messageV1.type.tell_you':'Quiero contarte algo','messageV1.type.invite_out':'Quiero invitarte a salir','messageV1.type.free_message':'Lo que quiero decir'}),
  fr:common({'messageV1.prompt':'Qu’aimeriez-vous lui dire aujourd’hui ?','messageV1.choose':'Choisir un sentiment','messageV1.content':'Écrivez ce que vous voulez dire','messageV1.save':'Enregistrer ce sentiment','messageV1.saved':'Ce sentiment fait maintenant partie de vos souvenirs.','messageV1.done':'Terminé','messageV1.card':'Créer une carte étoilée','messageV1.history':'Voir l’historique','messageV1.historyTitle':'Ce que je veux te dire · {count}','messageV1.all':'Tout','messageV1.month':'Ce mois-ci','messageV1.year':'Cette année','messageV1.empty':'Aucun message pour cette période.','messageV1.note':'Ces chiffres ne sont ni bons ni mauvais ; ils gardent simplement la trace de vos mots.','messageV1.back':'Écrire un autre message','messageV1.edit':'Modifier','messageV1.delete':'Supprimer','messageV1.deleteTitle':'Supprimer ce message ?','messageV1.deleteBody':'Il ne pourra pas être restauré sur cet appareil.','messageV1.saveEdit':'Enregistrer','messageV1.full':'Voir le message complet','messageV1.type.miss_you':'Tu me manques aujourd’hui','messageV1.type.thank_you':'Merci pour aujourd’hui','messageV1.type.sorry':'Je suis désolé·e','messageV1.type.dont_be_mad':'Ne sois pas en colère','messageV1.type.tell_you':'J’ai quelque chose à te dire','messageV1.type.invite_out':'J’aimerais t’inviter','messageV1.type.free_message':'Ce que je veux dire'}),
}
