import type { Locale } from './messages'

type Key = 'title' | 'create' | 'created' | 'copy' | 'share' | 'copied' | 'shareError' | 'shareTitle' | 'shareMessage' | 'input' | 'view' | 'accept' | 'later' | 'privacy' | 'paired' | 'refresh' | 'identity' | 'missing' | 'expired' | 'unavailable' | 'self' | 'already' | 'login' | 'protect' | 'error' | 'inviteBody' | 'expires' | 'invitePartnerTitle' | 'invitePartnerBody' | 'receivedTitle' | 'receivedBody' | 'loadingTitle' | 'loadingBody' | 'end' | 'endConfirmTitle' | 'endConfirmBody' | 'endCancel' | 'endConfirm' | 'ending'
type ShareKey = 'share' | 'copied' | 'shareError' | 'shareTitle' | 'shareMessage'

export const pairShareMessages: Record<Locale, Record<`pair.${ShareKey}`, string>> = {
  'zh-TW': {'pair.share':'分享邀請','pair.copied':'邀請內容已複製','pair.shareError':'邀請暫時無法分享或複製，請再試一次。','pair.shareTitle':'《星星戀愛日記》配對邀請','pair.shareMessage':'💕 我想邀請你和我一起走進《星星戀愛日記》的星空。\n\n打開《星星戀愛日記》後，進入：\n「我們 → 專屬配對 → 我收到邀請」\n\n再貼上下面的配對邀請識別碼：\n\n【配對邀請識別碼】\n{inviteId}\n\n✨ 完成後，我們就可以一起使用雙人功能。\n\n這是一組專屬邀請，請不要轉傳給其他人。'},
  en: {'pair.share':'Share invitation','pair.copied':'Invitation copied','pair.shareError':'We could not share or copy this invitation. Please try again.','pair.shareTitle':'Starry Love Diary Pair Invitation','pair.shareMessage':'💕 I would love to invite you into our Starry Love Diary sky.\n\nOpen Starry Love Diary, then go to:\n“Our → Your Pair → I received an invitation”\n\nPaste this Pair invitation ID:\n\n【Pair invitation ID】\n{inviteId}\n\n✨ Once it is complete, we can use the couple features together.\n\nThis invitation is personal. Please do not forward it to anyone else.'},
  ja: {'pair.share':'招待を共有','pair.copied':'招待内容をコピーしました','pair.shareError':'招待を共有またはコピーできませんでした。もう一度お試しください。','pair.shareTitle':'『星星恋愛日記』ペア招待','pair.shareMessage':'💕 『星星恋愛日記』の星空へ招待したいです。\n\n『星星恋愛日記』を開き、次へ進んでください：\n「私たち → ふたりのペア → 招待を受け取りました」\n\n次のペア招待IDを貼り付けます：\n\n【ペア招待ID】\n{inviteId}\n\n✨ 完了すると、ふたりで機能を使えるようになります。\n\nこの招待はあなた専用です。他の人へ転送しないでください。'},
  ko: {'pair.share':'초대 공유','pair.copied':'초대 내용을 복사했어요','pair.shareError':'지금 초대를 공유하거나 복사할 수 없어요. 다시 시도해 주세요.','pair.shareTitle':'별빛 연애 일기 페어 초대','pair.shareMessage':'💕 별빛 연애 일기의 별하늘로 초대하고 싶어요.\n\n별빛 연애 일기를 열고 다음으로 이동해 주세요:\n「우리 → 우리 페어 → 초대를 받았어요」\n\n아래 페어 초대 ID를 붙여 넣으세요:\n\n【페어 초대 ID】\n{inviteId}\n\n✨ 완료하면 함께 커플 기능을 사용할 수 있어요.\n\n이 초대는 개인 전용입니다. 다른 사람에게 전달하지 마세요.'},
  es: {'pair.share':'Compartir invitación','pair.copied':'Invitación copiada','pair.shareError':'No pudimos compartir ni copiar la invitación. Inténtalo de nuevo.','pair.shareTitle':'Invitación de pareja de Starry Love Diary','pair.shareMessage':'💕 Quiero invitarte a nuestro cielo de Starry Love Diary.\n\nAbre Starry Love Diary y ve a:\n«Nosotros → Pareja → Recibí una invitación»\n\nPega este identificador de invitación de pareja:\n\n【ID de invitación de pareja】\n{inviteId}\n\n✨ Cuando termines, podremos usar juntos las funciones de pareja.\n\nEsta invitación es personal. No la reenvíes a nadie más.'},
  fr: {'pair.share':'Partager l’invitation','pair.copied':'Invitation copiée','pair.shareError':'Impossible de partager ou copier cette invitation pour le moment. Réessayez.','pair.shareTitle':'Invitation Duo Starry Love Diary','pair.shareMessage':'💕 J’aimerais t’inviter dans notre ciel Starry Love Diary.\n\nOuvre Starry Love Diary, puis va dans :\n« Nous → Duo → J’ai reçu une invitation »\n\nColle cet identifiant d’invitation Duo :\n\n【Identifiant d’invitation Duo】\n{inviteId}\n\n✨ Une fois terminé, nous pourrons utiliser les fonctions à deux.\n\nCette invitation est personnelle. Ne la transfère à personne d’autre.'},
}
const basePairMessages: Record<Locale, Record<string, string>> = {
  'zh-TW': {'pair.title':'專屬配對','pair.create':'建立邀請','pair.created':'配對邀請已建立','pair.copy':'複製邀請','pair.share':'分享邀請','pair.copied':'邀請內容已複製','pair.shareError':'邀請暫時無法分享或複製，請再試一次。','pair.shareTitle':'《星星戀愛日記》配對邀請','pair.shareMessage':'💕 我想邀請你和我一起走進《星星戀愛日記》的星空。\n\n打開《星星戀愛日記》後，進入：\n「我們 → 專屬配對 → 我收到邀請」\n\n再貼上下面的配對邀請識別碼：\n\n【配對邀請識別碼】\n{inviteId}\n\n✨ 完成後，我們就可以一起使用雙人功能。\n\n這是一組專屬邀請，請不要轉傳給其他人。','pair.input':'輸入配對邀請識別碼','pair.view':'查看邀請','pair.accept':'接受配對','pair.later':'暫時不要','pair.privacy':'配對不會分享你的私人日記、清醒紀錄或其他個人內容。','pair.paired':'你們的專屬星空已經連在一起。','pair.refresh':'重新整理配對狀態','pair.identity':'請先完成帳號保護','pair.missing':'找不到這份邀請','pair.expired':'這份邀請已經過期','pair.unavailable':'這份邀請已經無法使用','pair.self':'不能接受自己建立的邀請','pair.already':'目前已經有一個配對，無法再建立新的配對。','pair.login':'請先完成登入','pair.protect':'建立或接受配對前，請先確認你的身分。','pair.error':'現在無法完成操作，請稍後再試。','pair.inviteBody':'有人邀請你一起建立專屬星空。','pair.expires':'邀請將在 24 小時後失效。','pair.invitePartnerTitle':'💌 邀請另一半','pair.invitePartnerBody':'建立一份專屬邀請，傳給對方。','pair.receivedTitle':'✨ 我收到邀請','pair.receivedBody':'貼上另一半傳給你的邀請。','pair.loadingTitle':'正在讀取配對狀態','pair.loadingBody':'正在確認你們的專屬星空。'},
  en: {'pair.title':'Your Pair','pair.create':'Create invitation','pair.created':'Pair invitation created','pair.copy':'Copy invitation ID','pair.input':'Enter invitation ID','pair.view':'View invitation','pair.accept':'Accept Pair','pair.later':'Not now','pair.privacy':'Pairing does not share your private diary, Clear records, or other personal content.','pair.paired':'Your shared starry sky is now connected.','pair.refresh':'Refresh pair status','pair.identity':'Protect your account first','pair.missing':'Invitation not found','pair.expired':'This invitation has expired','pair.unavailable':'This invitation is no longer available','pair.self':'You cannot accept your own invitation','pair.already':'You already have a Pair and cannot create another one.','pair.login':'Please sign in first','pair.protect':'Confirm your identity before creating or accepting a Pair.','pair.error':'We could not complete this right now. Please try again.','pair.inviteBody':'Someone has invited you to create a shared starry sky.','pair.expires':'This invitation expires in 24 hours.','pair.invitePartnerTitle':'💌 Invite your partner','pair.invitePartnerBody':'Create a personal invitation to send to them.','pair.receivedTitle':'✨ I received an invitation','pair.receivedBody':'Paste the invitation your partner sent you.','pair.loadingTitle':'Loading Pair status','pair.loadingBody':'We are confirming your shared starry sky.'},
  ja: {'pair.title':'ふたりのペア','pair.create':'招待を作成','pair.created':'ペア招待を作成しました','pair.copy':'招待IDをコピー','pair.input':'招待IDを入力','pair.view':'招待を見る','pair.accept':'ペアを承諾','pair.later':'今はしない','pair.privacy':'ペアリングで、個人の日記や心を整える記録などの個人内容が共有されることはありません。','pair.paired':'ふたりの星空がつながりました。','pair.refresh':'ペアの状態を更新','pair.identity':'先にアカウントを保護してください','pair.missing':'招待が見つかりません','pair.expired':'この招待は期限切れです','pair.unavailable':'この招待は利用できません','pair.self':'自分の招待は承諾できません','pair.already':'すでにペアがあるため、新しいペアは作成できません。','pair.login':'先にログインしてください','pair.protect':'ペアを作成または承諾する前に本人確認をしてください。','pair.error':'今は完了できません。もう一度お試しください。','pair.inviteBody':'誰かが、ふたりの星空を作るよう招待しています。','pair.expires':'招待は24時間後に失効します。','pair.invitePartnerTitle':'💌 パートナーを招待','pair.invitePartnerBody':'ふたりだけの招待を作成して相手に送ります。','pair.receivedTitle':'✨ 招待を受け取りました','pair.receivedBody':'相手から届いた招待を貼り付けてください。','pair.loadingTitle':'ペアの状態を確認しています','pair.loadingBody':'ふたりの星空を確認しています。'},
  ko: {'pair.title':'우리 페어','pair.create':'초대 만들기','pair.created':'페어 초대가 만들어졌어요','pair.copy':'초대 ID 복사','pair.input':'초대 ID 입력','pair.view':'초대 보기','pair.accept':'페어 수락','pair.later':'나중에 하기','pair.privacy':'페어링해도 개인 일기, 마음 정리 기록 등 개인 콘텐츠는 공유되지 않아요.','pair.paired':'두 사람의 별하늘이 연결되었어요.','pair.refresh':'페어 상태 새로고침','pair.identity':'먼저 계정을 보호해 주세요','pair.missing':'초대를 찾을 수 없어요','pair.expired':'이 초대는 만료되었어요','pair.unavailable':'이 초대는 더 이상 사용할 수 없어요','pair.self':'내가 만든 초대는 수락할 수 없어요','pair.already':'이미 페어가 있어 새 페어를 만들 수 없어요.','pair.login':'먼저 로그인해 주세요','pair.protect':'페어를 만들거나 수락하기 전에 본인 확인을 해주세요.','pair.error':'지금은 완료할 수 없어요. 다시 시도해 주세요.','pair.inviteBody':'누군가 함께 별하늘을 만들자고 초대했어요.','pair.expires':'초대는 24시간 후 만료돼요.','pair.invitePartnerTitle':'💌 파트너 초대하기','pair.invitePartnerBody':'둘만의 초대를 만들어 상대에게 보내세요.','pair.receivedTitle':'✨ 초대를 받았어요','pair.receivedBody':'상대가 보낸 초대를 붙여 넣으세요.','pair.loadingTitle':'페어 상태를 확인하고 있어요','pair.loadingBody':'두 사람의 별하늘을 확인하고 있어요.'},
  es: {'pair.title':'Pareja','pair.create':'Crear invitación','pair.created':'Invitación creada','pair.copy':'Copiar ID de invitación','pair.input':'Introduce el ID de invitación','pair.view':'Ver invitación','pair.accept':'Aceptar pareja','pair.later':'Ahora no','pair.privacy':'La pareja no comparte tu diario privado, registros de claridad ni otro contenido personal.','pair.paired':'Su cielo estrellado ya está conectado.','pair.refresh':'Actualizar estado','pair.identity':'Protege tu cuenta primero','pair.missing':'No se encontró la invitación','pair.expired':'Esta invitación ha caducado','pair.unavailable':'Esta invitación ya no está disponible','pair.self':'No puedes aceptar tu propia invitación','pair.already':'Ya tienes una pareja y no puedes crear otra.','pair.login':'Inicia sesión primero','pair.protect':'Confirma tu identidad antes de crear o aceptar una pareja.','pair.error':'No pudimos completar esto ahora. Inténtalo de nuevo.','pair.inviteBody':'Alguien te ha invitado a crear un cielo estrellado compartido.','pair.expires':'Esta invitación caduca en 24 horas.','pair.invitePartnerTitle':'💌 Invita a tu pareja','pair.invitePartnerBody':'Crea una invitación personal para enviársela.','pair.receivedTitle':'✨ Recibí una invitación','pair.receivedBody':'Pega la invitación que te envió tu pareja.','pair.loadingTitle':'Cargando el estado de la pareja','pair.loadingBody':'Estamos confirmando su cielo estrellado compartido.'},
  fr: {'pair.title':'Duo','pair.create':'Créer une invitation','pair.created':'Invitation créée','pair.copy':'Copier l’identifiant','pair.input':'Saisissez l’identifiant','pair.view':'Voir l’invitation','pair.accept':'Accepter le duo','pair.later':'Pas maintenant','pair.privacy':'Le duo ne partage pas votre journal privé, vos notes de clarté ou tout autre contenu personnel.','pair.paired':'Votre ciel étoilé est maintenant relié.','pair.refresh':'Actualiser le statut','pair.identity':'Protégez d’abord votre compte','pair.missing':'Invitation introuvable','pair.expired':'Cette invitation a expiré','pair.unavailable':'Cette invitation n’est plus disponible','pair.self':'Vous ne pouvez pas accepter votre propre invitation','pair.already':'Vous avez déjà un duo et ne pouvez pas en créer un autre.','pair.login':'Connectez-vous d’abord','pair.protect':'Confirmez votre identité avant de créer ou accepter un duo.','pair.error':'Nous ne pouvons pas terminer cela maintenant. Réessayez.','pair.inviteBody':'Quelqu’un vous invite à créer un ciel étoilé partagé.','pair.expires':'Cette invitation expire dans 24 heures.','pair.invitePartnerTitle':'💌 Invitez votre partenaire','pair.invitePartnerBody':'Créez une invitation personnelle à lui envoyer.','pair.receivedTitle':'✨ J’ai reçu une invitation','pair.receivedBody':'Collez l’invitation envoyée par votre partenaire.','pair.loadingTitle':'Chargement du statut du duo','pair.loadingBody':'Nous confirmons votre ciel étoilé partagé.'},
}

const pairEndMessages: Record<Locale, Record<`pair.${Extract<Key, 'end' | 'endConfirmTitle' | 'endConfirmBody' | 'endCancel' | 'endConfirm' | 'ending'>}`, string>> = {
  'zh-TW': { 'pair.end':'解除專屬配對', 'pair.endConfirmTitle':'確定要解除專屬配對嗎？', 'pair.endConfirmBody':'解除後，你們將無法繼續使用目前這段配對的雙人功能。\n\n你的日記、星星瓶、足跡、清醒紀錄與其他個人內容都不會被刪除。\n\n如果未來想再次配對，需要重新建立新的邀請。', 'pair.endCancel':'取消', 'pair.endConfirm':'解除配對', 'pair.ending':'正在解除配對…' },
  en: { 'pair.end':'End Pair', 'pair.endConfirmTitle':'End this Pair?', 'pair.endConfirmBody':'After ending it, you can no longer use the paired features for this relationship.\n\nYour diary, Star Bottle, Footprints, Clear records, and other personal content will not be deleted.\n\nTo pair again later, create a new invitation.', 'pair.endCancel':'Cancel', 'pair.endConfirm':'End Pair', 'pair.ending':'Ending Pair…' },
  ja: { 'pair.end':'ペアを解除', 'pair.endConfirmTitle':'このペアを解除しますか？', 'pair.endConfirmBody':'解除すると、この関係で現在利用しているふたりの機能は使えなくなります。\n\n日記、星のボトル、足あと、心を整える記録などの個人データは削除されません。\n\n再びペアになるには、新しい招待を作成してください。', 'pair.endCancel':'キャンセル', 'pair.endConfirm':'ペアを解除', 'pair.ending':'ペアを解除しています…' },
  ko: { 'pair.end':'페어 해제', 'pair.endConfirmTitle':'페어를 해제할까요?', 'pair.endConfirmBody':'해제하면 현재 관계의 커플 기능을 계속 사용할 수 없어요.\n\n일기, 별 병, 발자국, 마음 정리 기록 등 개인 콘텐츠는 삭제되지 않아요.\n\n나중에 다시 페어가 되려면 새 초대를 만들어야 해요.', 'pair.endCancel':'취소', 'pair.endConfirm':'페어 해제', 'pair.ending':'페어를 해제하는 중…' },
  es: { 'pair.end':'Terminar pareja', 'pair.endConfirmTitle':'¿Terminar esta pareja?', 'pair.endConfirmBody':'Al terminarla, ya no podrán usar las funciones de pareja de esta relación.\n\nTu diario, Botella de Estrellas, Huellas, registros de claridad y otro contenido personal no se eliminarán.\n\nPara volver a formar pareja en el futuro, crea una nueva invitación.', 'pair.endCancel':'Cancelar', 'pair.endConfirm':'Terminar pareja', 'pair.ending':'Terminando pareja…' },
  fr: { 'pair.end':'Mettre fin au duo', 'pair.endConfirmTitle':'Mettre fin à ce duo ?', 'pair.endConfirmBody':'Après cela, vous ne pourrez plus utiliser les fonctions à deux de cette relation.\n\nVotre journal, Bouteille d’étoiles, Empreintes, notes de clarté et autres contenus personnels ne seront pas supprimés.\n\nPour former un duo à nouveau, créez une nouvelle invitation.', 'pair.endCancel':'Annuler', 'pair.endConfirm':'Mettre fin au duo', 'pair.ending':'Fin du duo…' },
}

export const pairMessages = Object.fromEntries(
  (Object.keys(basePairMessages) as Locale[]).map((locale) => [locale, { ...pairShareMessages[locale], ...basePairMessages[locale], ...pairEndMessages[locale] }]),
) as Record<Locale, Record<`pair.${Key}`, string>>
