import type { Locale } from './messages'

const keys = ['title','create','created','copy','input','view','accept','later','privacy','paired','refresh','identity','missing','expired','unavailable','self','already','login','protect','error','inviteBody','expires'] as const
type Key = typeof keys[number]
export const pairMessages: Record<Locale, Record<`pair.${Key}`, string>> = {
  'zh-TW': {'pair.title':'專屬配對','pair.create':'建立配對','pair.created':'配對邀請已建立','pair.copy':'複製邀請識別碼','pair.input':'輸入配對邀請識別碼','pair.view':'查看邀請','pair.accept':'接受配對','pair.later':'暫時不要','pair.privacy':'配對不會分享你的私人日記、清醒紀錄或其他個人內容。','pair.paired':'你們的專屬星空已經連在一起。','pair.refresh':'重新整理配對狀態','pair.identity':'請先完成帳號保護','pair.missing':'找不到這份邀請','pair.expired':'這份邀請已經過期','pair.unavailable':'這份邀請已經無法使用','pair.self':'不能接受自己建立的邀請','pair.already':'目前已經有一個配對，無法再建立新的配對。','pair.login':'請先完成登入','pair.protect':'建立或接受配對前，請先確認你的身分。','pair.error':'現在無法完成操作，請稍後再試。','pair.inviteBody':'有人邀請你一起建立專屬星空。','pair.expires':'邀請將在 24 小時後失效。'},
  en: {'pair.title':'Your Pair','pair.create':'Create Pair','pair.created':'Pair invitation created','pair.copy':'Copy invitation ID','pair.input':'Enter invitation ID','pair.view':'View invitation','pair.accept':'Accept Pair','pair.later':'Not now','pair.privacy':'Pairing does not share your private diary, Clear records, or other personal content.','pair.paired':'Your shared starry sky is now connected.','pair.refresh':'Refresh pair status','pair.identity':'Protect your account first','pair.missing':'Invitation not found','pair.expired':'This invitation has expired','pair.unavailable':'This invitation is no longer available','pair.self':'You cannot accept your own invitation','pair.already':'You already have a Pair and cannot create another one.','pair.login':'Please sign in first','pair.protect':'Confirm your identity before creating or accepting a Pair.','pair.error':'We could not complete this right now. Please try again.','pair.inviteBody':'Someone has invited you to create a shared starry sky.','pair.expires':'This invitation expires in 24 hours.'},
  ja: {'pair.title':'ふたりのペア','pair.create':'ペアを作成','pair.created':'ペア招待を作成しました','pair.copy':'招待IDをコピー','pair.input':'招待IDを入力','pair.view':'招待を見る','pair.accept':'ペアを承諾','pair.later':'今はしない','pair.privacy':'ペアリングで、個人の日記や心を整える記録などの個人内容が共有されることはありません。','pair.paired':'ふたりの星空がつながりました。','pair.refresh':'ペアの状態を更新','pair.identity':'先にアカウントを保護してください','pair.missing':'招待が見つかりません','pair.expired':'この招待は期限切れです','pair.unavailable':'この招待は利用できません','pair.self':'自分の招待は承諾できません','pair.already':'すでにペアがあるため、新しいペアは作成できません。','pair.login':'先にログインしてください','pair.protect':'ペアを作成または承諾する前に本人確認をしてください。','pair.error':'今は完了できません。もう一度お試しください。','pair.inviteBody':'誰かが、ふたりの星空を作るよう招待しています。','pair.expires':'招待は24時間後に失効します。'},
  ko: {'pair.title':'우리 페어','pair.create':'페어 만들기','pair.created':'페어 초대가 만들어졌어요','pair.copy':'초대 ID 복사','pair.input':'초대 ID 입력','pair.view':'초대 보기','pair.accept':'페어 수락','pair.later':'나중에 하기','pair.privacy':'페어링해도 개인 일기, 마음 정리 기록 등 개인 콘텐츠는 공유되지 않아요.','pair.paired':'두 사람의 별하늘이 연결되었어요.','pair.refresh':'페어 상태 새로고침','pair.identity':'먼저 계정을 보호해 주세요','pair.missing':'초대를 찾을 수 없어요','pair.expired':'이 초대는 만료되었어요','pair.unavailable':'이 초대는 더 이상 사용할 수 없어요','pair.self':'내가 만든 초대는 수락할 수 없어요','pair.already':'이미 페어가 있어 새 페어를 만들 수 없어요.','pair.login':'먼저 로그인해 주세요','pair.protect':'페어를 만들거나 수락하기 전에 본인 확인을 해주세요.','pair.error':'지금은 완료할 수 없어요. 다시 시도해 주세요.','pair.inviteBody':'누군가 함께 별하늘을 만들자고 초대했어요.','pair.expires':'초대는 24시간 후 만료돼요.'},
  es: {'pair.title':'Pareja','pair.create':'Crear pareja','pair.created':'Invitación creada','pair.copy':'Copiar ID de invitación','pair.input':'Introduce el ID de invitación','pair.view':'Ver invitación','pair.accept':'Aceptar pareja','pair.later':'Ahora no','pair.privacy':'La pareja no comparte tu diario privado, registros de claridad ni otro contenido personal.','pair.paired':'Su cielo estrellado ya está conectado.','pair.refresh':'Actualizar estado','pair.identity':'Protege tu cuenta primero','pair.missing':'No se encontró la invitación','pair.expired':'Esta invitación ha caducado','pair.unavailable':'Esta invitación ya no está disponible','pair.self':'No puedes aceptar tu propia invitación','pair.already':'Ya tienes una pareja y no puedes crear otra.','pair.login':'Inicia sesión primero','pair.protect':'Confirma tu identidad antes de crear o aceptar una pareja.','pair.error':'No pudimos completar esto ahora. Inténtalo de nuevo.','pair.inviteBody':'Alguien te ha invitado a crear un cielo estrellado compartido.','pair.expires':'Esta invitación caduca en 24 horas.'},
  fr: {'pair.title':'Duo','pair.create':'Créer un duo','pair.created':'Invitation créée','pair.copy':'Copier l’identifiant','pair.input':'Saisissez l’identifiant','pair.view':'Voir l’invitation','pair.accept':'Accepter le duo','pair.later':'Pas maintenant','pair.privacy':'Le duo ne partage pas votre journal privé, vos notes de clarté ou tout autre contenu personnel.','pair.paired':'Votre ciel étoilé est maintenant relié.','pair.refresh':'Actualiser le statut','pair.identity':'Protégez d’abord votre compte','pair.missing':'Invitation introuvable','pair.expired':'Cette invitation a expiré','pair.unavailable':'Cette invitation n’est plus disponible','pair.self':'Vous ne pouvez pas accepter votre propre invitation','pair.already':'Vous avez déjà un duo et ne pouvez pas en créer un autre.','pair.login':'Connectez-vous d’abord','pair.protect':'Confirmez votre identité avant de créer ou accepter un duo.','pair.error':'Nous ne pouvons pas terminer cela maintenant. Réessayez.','pair.inviteBody':'Quelqu’un vous invite à créer un ciel étoilé partagé.','pair.expires':'Cette invitation expire dans 24 heures.'},
}
