import type { Locale } from './messages'

type StarrySkyPhase2MessageMap = Record<
  'our.starrySky.title'|'our.starrySky.heroCopy'|'our.starrySky.count'|'our.starrySky.libraryTitle'|'our.starrySky.librarySubtitle'|'our.starrySky.browse'|'our.starrySky.share'|'our.starrySky.choose'|'our.starrySky.custom'|'our.starrySky.chooseUnpaired'|'our.starrySky.customUnpaired'|'our.starrySky.invite'|'our.starrySky.code'|'our.starrySky.copied'|'our.starrySky.shareError'|'our.starrySky.choosePaired'|'our.starrySky.tonightTitle'|'our.starrySky.pairingTitle'|'our.starrySky.featuredTitle'|'our.starrySky.category.A'|'our.starrySky.category.B'|'our.starrySky.category.C'|'our.starrySky.category.D'|'our.starrySky.category.E'|'our.starrySky.category.F'|'our.starrySky.category.G'|'our.starrySky.category.H'|'our.starrySky.category.I'|'our.starrySky.category.J'|'our.starrySky.category.K'|'our.starrySky.category.L',
  string
>

const categories = {
  'zh-TW': ['我在你心裡・關於我們','被愛・被關心・被理解','你眼中的我','家庭・親情・家的感覺','長輩・童年・成長','朋友・友情・人際世界','日常生活・真正的你','工作・學習・努力的自己','關於現在的自己','夢想・未來・想去的地方','旅行・體驗・好玩的世界','心情・支持・彼此靠近'],
  en: ['Us, in your heart','Love, care, and understanding','How you see me','Family and home','Elders, childhood, growth','Friends and connection','Everyday, real you','Work, learning, effort','Who you are now','Dreams and the future','Travel and experiences','Feelings, support, closeness'],
  ja: ['あなたの心の中の私たち','愛されること・気づかい・理解','あなたから見た私','家族・親しさ・家の感覚','年長者・子ども時代・成長','友人・友情・人とのつながり','日常・ありのままのあなた','仕事・学び・がんばる自分','今の自分について','夢・未来・行きたい場所','旅・体験・楽しい世界','気持ち・支え・寄り添い'],
  ko: ['당신의 마음속 우리','사랑받음·돌봄·이해','당신이 보는 나','가족·정·집의 감각','어른·어린 시절·성장','친구·우정·관계','일상·있는 그대로의 나','일·배움·노력하는 나','지금의 나','꿈·미래·가고 싶은 곳','여행·경험·즐거운 세상','마음·지지·가까워짐'],
  es: ['Nosotros en tu corazón','Amor, cuidado y comprensión','Cómo me ves','Familia y hogar','Mayores, infancia y crecimiento','Amistad y vínculos','Vida diaria, tu yo real','Trabajo, aprendizaje y esfuerzo','Tu yo actual','Sueños y futuro','Viajes y experiencias','Ánimo, apoyo y cercanía'],
  fr: ['Nous dans ton cœur','Amour, attention et compréhension','Ton regard sur moi','Famille et sentiment de foyer','Aînés, enfance et évolution','Amitiés et liens','Quotidien, le vrai toi','Travail, apprentissage et effort','La personne que tu es aujourd’hui','Rêves et avenir','Voyages et expériences','Émotions, soutien et proximité'],
} as const

const shells = {
  'zh-TW': ['💕 我們的星空','有些話，\n不需要留下答案。\n只需要找一個時間，\n好好聊聊。✨','⭐ 我們已一起點亮 {count} 次心話','心話題庫','挑一題，找一個適合的時間好好聊聊。','瀏覽全部題庫','分享','選這題','✨ 自己出一題','先完成配對，就可以用這題邀請對方一起聊聊。','配對後，可用自己的題目邀請對方一起聊聊。','邀請另一半','輸入配對碼','已複製題目','分享暫時無法使用','這題將可在下一階段建立心話邀請。','今晚，想聊聊什麼？','💕 想和另一半一起聊？','⭐ 精選心話題目'],
  en: ['💕 Our Starry Sky','Some words\ndo not need an answer kept.\nThey only need a time\nto be shared well. ✨','⭐ Together, we have lit {count} heart talks','Heart Talk Library','Choose a prompt and make time to talk well.','Browse all prompts','Share','Choose this prompt','✨ Write your own prompt','Pair first, then you can invite your partner to talk with this prompt.','After pairing, you can use your own prompt to invite a heart talk.','Invite partner','Enter pairing code','Prompt copied','Sharing is unavailable right now','This prompt can create a Heart Talk invitation in the next phase.','What would you like to talk about tonight?','💕 Want to talk with your partner?','⭐ Featured heart-talk prompt'],
  ja: ['💕 ふたりの星空','答えを残さなくていい言葉もあります。\nただ時間をつくって、\nゆっくり話せばいい。✨','⭐ ふたりで灯した心話 {count} 回','心話題庫','一つ選んで、ゆっくり話す時間をつくりましょう。','題庫を見る','共有','この題を選ぶ','✨ 自分で題をつくる','先にペアになると、この題で相手を誘えます。','ペアになったら、自分の題で心話に誘えます。','パートナーを招待','ペアリングコードを入力','題をコピーしました','今は共有できません','この題は次の段階で心話の招待に使えます。','今夜、何を話したい？','💕 パートナーと話してみる？','⭐ おすすめ心話テーマ'],
  ko: ['💕 우리만의 별빛 하늘','답을 남길 필요 없는 말도 있어요.\n시간을 내서\n잘 이야기하면 돼요. ✨','⭐ 함께 밝힌 마음 대화 {count}회','마음 이야기 주제집','하나를 골라 천천히 이야기할 시간을 만들어 보세요.','모든 주제 보기','공유','이 주제 선택','✨ 직접 주제 만들기','먼저 짝을 이루면 이 주제로 함께 이야기하자고 초대할 수 있어요.','짝을 이룬 뒤에는 직접 만든 주제로 마음 대화를 초대할 수 있어요.','상대 초대','페어링 코드 입력','주제를 복사했어요','지금은 공유할 수 없어요','이 주제는 다음 단계에서 마음 대화 초대에 쓸 수 있어요.','오늘 밤, 무엇을 이야기할까요?','💕 상대와 함께 이야기할까요?','⭐ 추천 마음 대화 주제'],
  es: ['💕 Nuestro cielo estrellado','Hay palabras\nque no necesitan una respuesta guardada.\nSolo necesitan un momento\npara hablarlas bien. ✨','⭐ Hemos encendido juntos {count} conversaciones del corazón','Biblioteca de conversaciones','Elige una pregunta y reserva un momento para hablar bien.','Ver todas las preguntas','Compartir','Elegir esta pregunta','✨ Crear tu propia pregunta','Primero completen el vínculo; entonces podrán invitar a conversar con esta pregunta.','Después de vincularse, podrán usar su propia pregunta para una conversación del corazón.','Invitar a tu pareja','Introducir código de pareja','Pregunta copiada','No se puede compartir ahora','Esta pregunta podrá crear una invitación en la próxima fase.','¿De qué quieren hablar esta noche?','💕 ¿Quieren hablar en pareja?','⭐ Tema destacado'],
  fr: ['💕 Notre ciel étoilé','Certaines paroles\nn’ont pas besoin de laisser une réponse.\nElles ont seulement besoin d’un moment\npour être vraiment partagées. ✨','⭐ Nous avons illuminé ensemble {count} conversations du cœur','Bibliothèque de sujets','Choisissez une question et prenez le temps d’en parler.','Voir tous les sujets','Partager','Choisir ce sujet','✨ Créer votre propre question','Associez-vous d’abord, puis vous pourrez inviter l’autre à parler avec ce sujet.','Après l’association, vous pourrez utiliser votre propre question pour une conversation du cœur.','Inviter votre partenaire','Saisir un code de duo','Sujet copié','Le partage est indisponible','Ce sujet pourra créer une invitation lors de la prochaine phase.','De quoi aimeriez-vous parler ce soir ?','💕 Envie de parler avec votre partenaire ?','⭐ Sujet du cœur sélectionné'],
} as const

const keys = ['title','heroCopy','count','libraryTitle','librarySubtitle','browse','share','choose','custom','chooseUnpaired','customUnpaired','invite','code','copied','shareError','choosePaired','tonightTitle','pairingTitle','featuredTitle'] as const
export const starrySkyPhase2Messages: Record<Locale, StarrySkyPhase2MessageMap> = Object.fromEntries((Object.keys(shells) as Locale[]).map((locale) => {
  const message: Record<string, string> = {}
  keys.forEach((key, index) => { message[`our.starrySky.${key}`] = shells[locale][index] })
  categories[locale].forEach((label, index) => { message[`our.starrySky.category.${String.fromCharCode(65 + index)}`] = label })
  return [locale, message]
})) as Record<Locale, StarrySkyPhase2MessageMap>
