import type { Locale } from './messages'

const keys = ['historyTitle', 'historyHeroCopy', 'historyEntry', 'historyHeading', 'historyEmptyTitle', 'historyEmptyBody', 'historyCustomLabel', 'historyDate', 'historyTime', 'historyDeleteOne', 'historyClearAll', 'historyDeleteTitle', 'historyDeleteBody', 'historyDeleteConfirm', 'historyClearTitle', 'historyClearBody', 'historyClearConfirm'] as const
type HistoryKey = typeof keys[number]

const values: Record<Locale, readonly string[]> = {
  'zh-TW': ['💕 心話歷史', '我們沒有留下答案，\n只留下曾經為彼此留過的時間。✨', '查看心話歷史', '曾一起點亮的心話', '還沒有心話紀錄', '當你們完成一次心話時，這裡會留下曾經為彼此留過的時間。', '✨ 自訂題目', '日期', '時間', '刪除此紀錄', '清除全部紀錄', '刪除這筆心話紀錄？', '刪除後，這次心話將不再出現在歷史紀錄中，也會從一起點亮的心話次數中扣除。此動作無法復原。', '刪除紀錄', '清除全部心話紀錄？', '所有心話歷史都會從這台裝置刪除，「一起點亮的心話」次數也會回到 0。此動作無法復原。', '全部清除'],
  en: ['💕 Heart Talk History', 'We did not keep the answers,\nonly the time you set aside for each other. ✨', 'View Heart Talk history', 'Heart Talks you lit together', 'No Heart Talk records yet', 'When you complete a Heart Talk, the time you set aside for each other will leave a trace here.', '✨ Custom prompt', 'Date', 'Time', 'Delete this record', 'Clear all records', 'Delete this Heart Talk record?', 'After deletion, this Heart Talk will no longer appear in history and will be removed from the count of Heart Talks you lit together. This cannot be undone.', 'Delete record', 'Clear all Heart Talk records?', 'All Heart Talk history will be deleted from this device, and the count of Heart Talks you lit together will return to 0. This cannot be undone.', 'Clear all'],
  ja: ['💕 心話の履歴', '答えは残さず、\nお互いのために作った時間だけを残します。✨', '心話の履歴を見る', 'ふたりで灯した心話', '心話の記録はまだありません', '心話を終えたら、お互いのために作った時間の足跡がここに残ります。', '✨ 自分で作ったテーマ', '日付', '時間', 'この記録を削除', 'すべての記録を消去', 'この心話の記録を削除しますか？', '削除すると、この心話は履歴に表示されなくなり、ふたりで灯した心話の回数からも減ります。この操作は元に戻せません。', '記録を削除', 'すべての心話の記録を消去しますか？', 'この端末のすべての心話履歴が削除され、ふたりで灯した心話の回数は0に戻ります。この操作は元に戻せません。', 'すべて消去'],
  ko: ['💕 마음 대화 기록', '답은 남기지 않고,\n서로를 위해 남긴 시간만 기억해요. ✨', '마음 대화 기록 보기', '함께 밝힌 마음 대화', '아직 마음 대화 기록이 없어요', '마음 대화를 마치면 서로를 위해 남긴 시간이 이곳에 남아요.', '✨ 직접 만든 주제', '날짜', '시간', '이 기록 삭제', '모든 기록 지우기', '이 마음 대화 기록을 삭제할까요?', '삭제하면 이 마음 대화는 기록에서 사라지고 함께 밝힌 마음 대화 횟수에서도 제외됩니다. 이 작업은 되돌릴 수 없어요.', '기록 삭제', '모든 마음 대화 기록을 지울까요?', '이 기기의 모든 마음 대화 기록이 삭제되고 함께 밝힌 마음 대화 횟수는 0으로 돌아갑니다. 이 작업은 되돌릴 수 없어요.', '모두 지우기'],
  es: ['💕 Historial de conversaciones', 'No guardamos las respuestas,\nsolo el tiempo que reservaron el uno para el otro. ✨', 'Ver historial de conversaciones', 'Conversaciones que encendieron juntos', 'Aún no hay registros de conversaciones', 'Cuando completen una conversación, el tiempo que reservaron el uno para el otro quedará aquí.', '✨ Pregunta personalizada', 'Fecha', 'Hora', 'Eliminar este registro', 'Borrar todos los registros', '¿Eliminar este registro de conversación?', 'Tras eliminarlo, esta conversación dejará de aparecer en el historial y se descontará del número de conversaciones encendidas juntos. Esta acción no se puede deshacer.', 'Eliminar registro', '¿Borrar todos los registros de conversaciones?', 'Todo el historial de conversaciones se eliminará de este dispositivo y el número de conversaciones encendidas juntos volverá a 0. Esta acción no se puede deshacer.', 'Borrar todo'],
  fr: ['💕 Historique des conversations', 'Nous ne gardons pas les réponses,\nseulement le temps que vous avez gardé l’un pour l’autre. ✨', 'Voir l’historique des conversations', 'Conversations illuminées ensemble', 'Aucun historique de conversation pour le moment', 'Lorsque vous terminez une conversation, le temps gardé l’un pour l’autre laisse une trace ici.', '✨ Sujet personnalisé', 'Date', 'Heure', 'Supprimer cette entrée', 'Effacer toutes les entrées', 'Supprimer cette entrée de conversation ?', 'Après suppression, cette conversation n’apparaîtra plus dans l’historique et sera retirée du nombre de conversations illuminées ensemble. Cette action est irréversible.', 'Supprimer l’entrée', 'Effacer tous les historiques de conversations ?', 'Tout l’historique des conversations sera supprimé de cet appareil et le nombre de conversations illuminées ensemble reviendra à 0. Cette action est irréversible.', 'Tout effacer'],
}

export const starrySkyPhase2eMessages: Record<Locale, Record<`our.starrySky.${HistoryKey}`, string>> = Object.fromEntries((Object.keys(values) as Locale[]).map((locale) => [locale, Object.fromEntries(keys.map((key, index) => [`our.starrySky.${key}`, values[locale][index]]))])) as Record<Locale, Record<`our.starrySky.${HistoryKey}`, string>>
