import type { Locale } from './messages'

const keys = ['inviteTitle','inviteHeroCopy','inviteStepTopic','inviteChangeTopic','inviteStepDate','inviteOtherDate','inviteDateLabel','inviteStepTime','inviteStartTime','inviteEndTime','inviteStepSend','inviteNotice','inviteExpiry','inviteSubmit','invitePreviewTitle','invitePreviewBody','invitePreviewTopic','invitePreviewDate','invitePreviewTime','inviteClose','inviteInvalidTopicTitle','inviteInvalidTopicBody','inviteBackToLibrary','inviteInvalidTime','invitePastDate','inviteTimePickerTitle','inviteHour','inviteMinute','invitePickerCancel','invitePickerConfirm','inviteExternalConversation','inviteReviewIncoming'] as const
type InviteKey = typeof keys[number]

const values: Record<Locale, readonly string[]> = {
  'zh-TW': ['💕 發起心話邀約','選一個時間，\n給彼此一段專屬的心話時光，\n讓這個問題，\n成為我們更靠近的一顆星。✨','⭐ 1. 確認這題心話','更換題目','⭐ 2. 選擇日期','選擇其他日期','選擇日期','⭐ 3. 選擇時間','開始時間','結束時間','⭐ 4. 發出邀約','正式配對功能上線後，另一半會收到心話邀約通知。','目前為介面測試，不會真正送出邀約。','發出心話邀約','心話邀約預覽完成','目前為介面測試，尚未真正送出邀約。','題目','日期','時間','關閉','尚未選擇有效題目','請從心話題庫選擇一題後，再發起本機邀約預覽。','返回心話題庫','結束時間必須晚於開始時間。','不能選擇過去日期。','選擇時間','時','分','取消','確認','心話邀約只是幫你們約好話題與時間。\n到了約定時間，可以用 LINE、電話、FaceTime、其他通訊方式，或直接見面聊聊。','查看收到的心話邀約（介面預覽）'],
  en: ['💕 Create a Heart Talk Invitation','Choose a time,\ngive each other a moment just for this heart talk,\nand let this question\nbecome a star that brings you closer. ✨','⭐ 1. Confirm this prompt','Change prompt','⭐ 2. Choose a date','Choose another date','Choose date','⭐ 3. Choose a time','Start time','End time','⭐ 4. Send invitation','When pairing is available, your partner will receive a Heart Talk invitation notification.','This is a UI test; no invitation will actually be sent.','Send Heart Talk Invitation','Heart Talk invitation preview complete','This is a UI preview only; no invitation has been sent.','Prompt','Date','Time','Close','No valid prompt selected','Choose a prompt from the Heart Talk Library before starting a local invitation preview.','Back to Heart Talk Library','The end time must be after the start time.','Past dates cannot be selected.','Choose a time','Hour','Minute','Cancel','Confirm','A Heart Talk invitation only agrees on a prompt and time.\nWhen the time arrives, use the way you normally connect, or meet in person.','View received Heart Talk (UI preview)'],
  ja: ['💕 心話の招待を作成','時間を選んで、\nふたりだけの心話の時間をつくり、\nこのテーマを\nもっと近づくための星にしよう。✨','⭐ 1. このテーマを確認','テーマを変更','⭐ 2. 日付を選択','別の日付を選ぶ','日付を選択','⭐ 3. 時間を選択','開始時間','終了時間','⭐ 4. 招待を送る','正式なペア機能の開始後、相手に心話の招待通知が届きます。','現在はUIテストで、招待は実際には送信されません。','心話の招待を送る','心話の招待プレビューが完成しました','これはUIプレビューです。招待は実際には送信されていません。','テーマ','日付','時間','閉じる','有効なテーマが選ばれていません','心話題庫からテーマを選んで、本機プレビューを始めてください。','心話題庫に戻る','終了時間は開始時間より後にしてください。','過去の日付は選べません。','時間を選択','時','分','キャンセル','確認','心話の招待は、テーマと時間を約束するためのものです。\n時間になったら、いつもの連絡方法を使うか、直接会って話してみましょう。'],
  ko: ['💕 마음 대화 초대 만들기','시간을 골라,\n둘만의 마음 대화 시간을 만들고,\n이 주제가\n더 가까워지는 별이 되게 해요. ✨','⭐ 1. 이 주제 확인','주제 바꾸기','⭐ 2. 날짜 선택','다른 날짜 선택','날짜 선택','⭐ 3. 시간 선택','시작 시간','종료 시간','⭐ 4. 초대 보내기','정식 페어링 기능이 시작되면 상대에게 마음 대화 초대 알림이 전달돼요.','현재는 UI 테스트이며 실제 초대는 보내지지 않아요.','마음 대화 초대 보내기','마음 대화 초대 미리보기가 완료되었어요','현재는 UI 미리보기이며, 실제 초대는 보내지지 않았어요.','주제','날짜','시간','닫기','유효한 주제가 선택되지 않았어요','마음 대화 주제집에서 주제를 선택한 뒤 로컬 초대 미리보기를 시작하세요.','마음 대화 주제집으로 돌아가기','종료 시간은 시작 시간보다 늦어야 해요.','지난 날짜는 선택할 수 없어요.','시간 선택','시','분','취소','확인','마음 대화 초대는 주제와 시간을 약속하는 기능이에요.\n시간이 되면 평소에 사용하는 방법으로 연락하거나 직접 만나 이야기해요.'],
  es: ['💕 Crear una invitación de conversación','Elijan un momento,\ndense un espacio solo para esta conversación,\ny dejen que esta pregunta\nsea una estrella que los acerque. ✨','⭐ 1. Confirmar esta pregunta','Cambiar pregunta','⭐ 2. Elegir fecha','Elegir otra fecha','Elegir fecha','⭐ 3. Elegir hora','Hora de inicio','Hora de fin','⭐ 4. Enviar invitación','Cuando esté disponible la función de pareja, tu pareja recibirá una notificación.','Esto es una prueba de interfaz; no se enviará ninguna invitación real.','Enviar invitación','Vista previa de invitación completada','Esto es solo una vista previa de la interfaz; no se ha enviado ninguna invitación.','Pregunta','Fecha','Hora','Cerrar','No hay una pregunta válida seleccionada','Elige una pregunta de la Biblioteca de conversaciones antes de iniciar la vista previa local.','Volver a la Biblioteca','La hora de fin debe ser posterior a la hora de inicio.','No se pueden elegir fechas pasadas.','Elegir hora','Hora','Minuto','Cancelar','Confirmar','Una invitación solo acuerda una pregunta y una hora.\nCuando llegue el momento, usen la forma en que suelen comunicarse o hablen en persona.'],
  fr: ['💕 Créer une invitation de conversation','Choisissez un moment,\noffrez-vous un temps rien que pour cette conversation,\net laissez cette question\ndevenir une étoile qui vous rapproche. ✨','⭐ 1. Confirmer ce sujet','Changer de sujet','⭐ 2. Choisir une date','Choisir une autre date','Choisir la date','⭐ 3. Choisir l’heure','Heure de début','Heure de fin','⭐ 4. Envoyer l’invitation','Lorsque la fonction de duo sera disponible, votre partenaire recevra une notification.','Ceci est un test d’interface ; aucune invitation ne sera réellement envoyée.','Envoyer l’invitation','Aperçu de l’invitation terminé','Ceci est seulement un aperçu de l’interface ; aucune invitation n’a été envoyée.','Sujet','Date','Heure','Fermer','Aucun sujet valide sélectionné','Choisissez un sujet dans la bibliothèque avant de démarrer un aperçu local.','Retour à la bibliothèque','L’heure de fin doit être postérieure à l’heure de début.','Les dates passées ne peuvent pas être choisies.','Choisir l’heure','Heure','Minute','Annuler','Confirmer','Une invitation fixe seulement un sujet et un moment.\nLorsque le moment arrive, utilisez votre manière habituelle de vous joindre ou parlez-vous en personne.'],
}

const incomingReview: Record<Locale, string> = {
  'zh-TW': '查看收到的心話邀約（介面預覽）',
  en: 'View received Heart Talk (UI preview)',
  ja: '受け取った心話の招待を見る（UIプレビュー）',
  ko: '받은 마음 대화 초대 보기 (UI 미리보기)',
  es: 'Ver invitación recibida (vista previa)',
  fr: 'Voir l’invitation reçue (aperçu)',
}
const production: Record<Locale, Partial<Record<InviteKey, string>>> = {
  'zh-TW': { inviteNotice: '另一半可在「我們的星空」重新整理後查看這份心話邀約。', inviteExpiry: '邀約會等待回覆 24 小時。', invitePreviewTitle: '心話邀約已送出', invitePreviewBody: '邀約已安全送至你們目前的配對關係。' },
  en: { inviteNotice: 'Your partner can refresh Our Starry Sky to see this Heart Talk invitation.', inviteExpiry: 'This invitation waits up to 24 hours for a response.', invitePreviewTitle: 'Heart Talk invitation sent', invitePreviewBody: 'The invitation was sent to your current Pair.' },
  ja: { inviteNotice: '相手は「ふたりの星空」を更新して、この心話の招待を確認できます。', inviteExpiry: '招待は24時間返答を待ちます。', invitePreviewTitle: '心話の招待を送信しました', invitePreviewBody: '招待は現在のペアに送信されました。' },
  ko: { inviteNotice: '상대는 우리의 별하늘을 새로고침하여 이 마음 대화 초대를 확인할 수 있어요.', inviteExpiry: '초대는 24시간 동안 응답을 기다려요.', invitePreviewTitle: '마음 대화 초대를 보냈어요', invitePreviewBody: '초대가 현재 페어에게 전송되었어요.' },
  es: { inviteNotice: 'Tu pareja puede actualizar Nuestro cielo estrellado para ver esta invitación.', inviteExpiry: 'La invitación espera una respuesta durante 24 horas.', invitePreviewTitle: 'Invitación enviada', invitePreviewBody: 'La invitación se envió a su pareja actual.' },
  fr: { inviteNotice: 'Votre partenaire peut actualiser Notre ciel étoilé pour voir cette invitation.', inviteExpiry: 'Cette invitation attend une réponse pendant 24 heures.', invitePreviewTitle: 'Invitation envoyée', invitePreviewBody: 'L’invitation a été envoyée à votre duo actuel.' },
}

export const starrySkyPhase2bMessages: Record<Locale, Record<`our.starrySky.${InviteKey}`, string>> = Object.fromEntries((Object.keys(values) as Locale[]).map((locale) => [locale, Object.fromEntries(keys.map((key, index) => [`our.starrySky.${key}`, production[locale][key] ?? (key === 'inviteReviewIncoming' ? incomingReview[locale] : values[locale][index] ?? values.en[index])]))])) as Record<Locale, Record<`our.starrySky.${InviteKey}`, string>>
