import type { Locale } from './messages'

const keys = ['incomingTitle', 'incomingHeroCopy', 'incomingInviter', 'incomingTopic', 'incomingSchedule', 'incomingDate', 'incomingTime', 'incomingExpiry', 'incomingPrototype', 'incomingAccept', 'incomingDecline', 'incomingAcceptedTitle', 'incomingAcceptedBody', 'incomingDeclinedTitle', 'incomingDeclinedBody', 'incomingViewSession', 'incomingExternalConversation'] as const
type IncomingKey = typeof keys[number]

const values: Record<Locale, readonly string[]> = {
  'zh-TW': ['💕 收到心話邀約', '有人想邀請你，\n一起留一段時間，\n好好聊聊這個問題。✨', '💕 對方邀請你一起聊聊', '這次想聊的題目', '邀約時間', '日期', '時間', '正式邀約將在 24 小時內等待回覆。', '目前為介面測試，不會真正計時或失效。', '接受邀約', '婉拒', '已接受邀約（介面預覽）', '正式配對功能完成後，這個邀約會成為你們已約好的心話時段。', '已婉拒邀約（介面預覽）', '正式功能上線後，對方只會知道這次邀約沒有成立，不需要提供理由。', '查看已約好的心話', '這個邀約會幫你們約好話題與時間，實際聊天請使用你們平常習慣的方式。'],
  en: ['💕 Heart Talk Invitation', 'Someone would like to invite you\nto set aside a little time\nand talk through this prompt together. ✨', '💕 Your partner would like to talk', 'Prompt for this conversation', 'Invitation time', 'Date', 'Time', 'A future invitation will wait up to 24 hours for a response.', 'This is a UI preview; it does not really count down or expire.', 'Accept invitation', 'Decline', 'Invitation accepted (UI preview)', 'When pairing is available, this invitation will become a Heart Talk time you have agreed on together.', 'Invitation declined (UI preview)', 'When the full feature is available, your partner will only know that this invitation was not accepted. No reason is needed.', 'View your scheduled Heart Talk', 'This invitation agrees on a prompt and time; use the way you normally connect for the conversation.'],
  ja: ['💕 心話の招待が届きました', '誰かがあなたを誘いたいようです。\n少し時間をとって、\nこのテーマを一緒に話してみましょう。✨', '💕 相手が一緒に話したいようです', '今回話したいテーマ', '招待の時間', '日付', '時間', '正式な招待は24時間以内の返答を待ちます。', 'これはUIプレビューです。実際には計時も失効もしません。', '招待を受ける', '辞退する', '招待を受けました（UIプレビュー）', '正式なペア機能の開始後、この招待はふたりで約束した心話の時間になります。', '招待を辞退しました（UIプレビュー）', '正式機能の開始後、相手には今回の招待が成立しなかったことだけが伝わります。理由は不要です。', '約束した心話を見る', 'この招待はテーマと時間を約束するものです。実際の会話は、いつもの方法でしてください。'],
  ko: ['💕 마음 대화 초대를 받았어요', '누군가 당신을 초대하고 싶어 해요.\n잠시 시간을 내서\n이 주제를 함께 이야기해요. ✨', '💕 상대가 함께 이야기하고 싶어 해요', '이번에 이야기할 주제', '초대 시간', '날짜', '시간', '정식 초대는 24시간 동안 답변을 기다려요.', '이것은 UI 미리보기이며 실제로 시간이 흐르거나 만료되지 않아요.', '초대 수락', '정중히 거절', '초대를 수락했어요 (UI 미리보기)', '정식 페어링 기능이 시작되면 이 초대는 두 사람이 약속한 마음 대화 시간이 돼요.', '초대를 거절했어요 (UI 미리보기)', '정식 기능이 시작되면 상대는 이번 초대가 성사되지 않았다는 것만 알게 돼요. 이유는 필요하지 않아요.', '약속한 마음 대화 보기', '이 초대는 주제와 시간을 약속해요. 실제 대화는 평소에 사용하는 방식으로 해주세요.'],
  es: ['💕 Has recibido una invitación', 'Alguien quiere invitarte\na reservar un momento\npara conversar sobre esta pregunta. ✨', '💕 Tu pareja quiere conversar contigo', 'Pregunta para esta conversación', 'Hora de la invitación', 'Fecha', 'Hora', 'Una invitación real esperará una respuesta durante 24 horas.', 'Esta es una vista previa de interfaz; no cuenta el tiempo ni vence de verdad.', 'Aceptar invitación', 'Rechazar', 'Invitación aceptada (vista previa)', 'Cuando la función de pareja esté disponible, esta invitación será un momento de conversación acordado entre los dos.', 'Invitación rechazada (vista previa)', 'Cuando esté disponible la función completa, tu pareja solo sabrá que esta invitación no se concretó. No hace falta dar un motivo.', 'Ver la conversación acordada', 'Esta invitación acuerda una pregunta y una hora; para conversar, usen su forma habitual de comunicarse.'],
  fr: ['💕 Invitation de conversation reçue', 'Quelqu’un aimerait vous inviter\nà prendre un moment\npour parler ensemble de cette question. ✨', '💕 Votre partenaire aimerait échanger avec vous', 'Sujet de cette conversation', 'Heure de l’invitation', 'Date', 'Heure', 'Une invitation officielle attendra une réponse pendant 24 heures.', 'Ceci est un aperçu d’interface : aucun délai réel ni expiration ne s’applique.', 'Accepter l’invitation', 'Décliner', 'Invitation acceptée (aperçu)', 'Lorsque la fonction duo sera disponible, cette invitation deviendra un moment de conversation convenu à deux.', 'Invitation déclinée (aperçu)', 'Lorsque la fonction complète sera disponible, votre partenaire saura seulement que cette invitation n’a pas abouti. Aucune raison n’est nécessaire.', 'Voir la conversation prévue', 'Cette invitation fixe un sujet et un moment ; pour échanger, utilisez votre manière habituelle de vous joindre.'],
}
const production: Record<Locale, Partial<Record<IncomingKey, string>>> = {
  'zh-TW': { incomingExpiry: '這份邀約會在 24 小時內等待回覆。', incomingPrototype: '邀約狀態會安全同步到目前的配對關係。', incomingAcceptedTitle: '已接受邀約', incomingAcceptedBody: '你們已約好這段心話時光。', incomingDeclinedTitle: '已婉拒邀約', incomingDeclinedBody: '對方會看到這次邀約沒有成立。' },
  en: { incomingExpiry: 'This invitation waits up to 24 hours for a response.', incomingPrototype: 'Invitation status is safely synchronized to your current Pair.', incomingAcceptedTitle: 'Invitation accepted', incomingAcceptedBody: 'You have scheduled this Heart Talk together.', incomingDeclinedTitle: 'Invitation declined', incomingDeclinedBody: 'Your partner will see that this invitation did not go ahead.' },
  ja: { incomingExpiry: 'この招待は24時間返答を待ちます。', incomingPrototype: '招待の状態は現在のペアに安全に同期されます。', incomingAcceptedTitle: '招待を受けました', incomingAcceptedBody: 'ふたりで心話の時間を約束しました。', incomingDeclinedTitle: '招待を辞退しました', incomingDeclinedBody: '相手には今回の招待が成立しなかったと表示されます。' },
  ko: { incomingExpiry: '이 초대는 24시간 동안 응답을 기다려요.', incomingPrototype: '초대 상태는 현재 페어에 안전하게 동기화돼요.', incomingAcceptedTitle: '초대를 수락했어요', incomingAcceptedBody: '함께 마음 대화 시간을 약속했어요.', incomingDeclinedTitle: '초대를 거절했어요', incomingDeclinedBody: '상대는 이번 초대가 성사되지 않았음을 보게 돼요.' },
  es: { incomingExpiry: 'Esta invitación espera una respuesta durante 24 horas.', incomingPrototype: 'El estado se sincroniza de forma segura con su pareja actual.', incomingAcceptedTitle: 'Invitación aceptada', incomingAcceptedBody: 'Han acordado este momento de conversación.', incomingDeclinedTitle: 'Invitación rechazada', incomingDeclinedBody: 'Tu pareja verá que esta invitación no se concretó.' },
  fr: { incomingExpiry: 'Cette invitation attend une réponse pendant 24 heures.', incomingPrototype: 'L’état est synchronisé de façon sûre avec votre duo actuel.', incomingAcceptedTitle: 'Invitation acceptée', incomingAcceptedBody: 'Vous avez prévu ce moment de conversation.', incomingDeclinedTitle: 'Invitation déclinée', incomingDeclinedBody: 'Votre partenaire verra que cette invitation n’a pas abouti.' },
}

export const starrySkyPhase2cMessages: Record<Locale, Record<`our.starrySky.${IncomingKey}`, string>> = Object.fromEntries((Object.keys(values) as Locale[]).map((locale) => [locale, Object.fromEntries(keys.map((key, index) => [`our.starrySky.${key}`, production[locale][key] ?? values[locale][index]]))])) as Record<Locale, Record<`our.starrySky.${IncomingKey}`, string>>
