import type { ClearRecord, LikeOrHabitReflection, LoveBoatAssessment } from '../data/clearTypes'
import type { Locale, TranslationKey } from '../i18n/messages'

type T = (key: TranslationKey, values?: Record<string, string | number>) => string
const key = (value: string) => value as TranslationKey
const heading: Record<Locale, Record<string, string>> = {
  'zh-TW': { title:'《星星戀愛日記｜清醒結果》', situation:'【情境】', facts:'【我知道的事實】', interpretation:'【我現在的解讀】', unknown:'【我還不知道的事】', feelings:'【我的感受】', observations:'【我觀察到的互動】', needs:'【我現在需要的】', next:'【我想做的下一步】', investment:'【我的投入】', responses:'【我回報的可觀察互動】', result:'【目前結果】', note:'【我想補充的情況】', real:'【我看見的真實的人】', habit:'【相處形成的習慣】', loss:'【和害怕失去有關的部分】', imagined:'【我對關係的想像與期待】', reality:'【我描述的現實】', modules:'【這次結果帶出的面向】', reflection:'【留給我的問題】' },
  en: { title:'《Starry Love Diary | Clarity result》', situation:'【Situation】', facts:'【Facts I know】', interpretation:'【My interpretation】', unknown:'【What I do not know yet】', feelings:'【My feelings】', observations:'【What I observed】', needs:'【What I need now】', next:'【My next step】', investment:'【My investment】', responses:'【Observable responses I reported】', result:'【Current result】', note:'【What I want to add】', real:'【The real person I see】', habit:'【Habits formed in being together】', loss:'【What may be about fear of loss】', imagined:'【My expectations and imagination】', reality:'【How I describe reality】', modules:'【What this result brought up】', reflection:'【A question for me】' },
  ja: { title:'《星空恋愛日記｜気づきの結果》', situation:'【状況】', facts:'【分かっている事実】', interpretation:'【私の解釈】', unknown:'【まだ分からないこと】', feelings:'【私の気持ち】', observations:'【観察したやり取り】', needs:'【今必要なこと】', next:'【次にしたいこと】', investment:'【私の気持ちの向き】', responses:'【私が観察した反応】', result:'【現在の結果】', note:'【補足したいこと】', real:'【私が見ているその人】', habit:'【一緒にいてできた習慣】', loss:'【失うことへの不安】', imagined:'【関係への想像と期待】', reality:'【私が説明する現実】', modules:'【この結果が示した面】', reflection:'【自分への問い】' },
  ko: { title:'《별빛 연애 일기 | 마음 정리 결과》', situation:'【상황】', facts:'【내가 아는 사실】', interpretation:'【나의 해석】', unknown:'【아직 모르는 점】', feelings:'【내 감정】', observations:'【내가 관찰한 상호작용】', needs:'【지금 필요한 것】', next:'【다음에 하고 싶은 일】', investment:'【내가 쏟은 마음】', responses:'【내가 관찰해 말한 반응】', result:'【현재 결과】', note:'【덧붙이고 싶은 상황】', real:'【내가 보는 실제 그 사람】', habit:'【함께하며 생긴 습관】', loss:'【잃을까 봐 두려운 부분】', imagined:'【관계에 대한 상상과 기대】', reality:'【내가 설명한 현실】', modules:'【이번 결과가 보여 준 면】', reflection:'【나에게 남기는 질문】' },
  es: { title:'《Diario de Amor Estrellado | Resultado de claridad》', situation:'【Situación】', facts:'【Hechos que conozco】', interpretation:'【Mi interpretación】', unknown:'【Lo que aún no sé】', feelings:'【Mis emociones】', observations:'【Lo que observé】', needs:'【Lo que necesito ahora】', next:'【Mi siguiente paso】', investment:'【Mi implicación】', responses:'【Respuestas observables que conté】', result:'【Resultado actual】', note:'【Lo que quiero añadir】', real:'【La persona real que veo】', habit:'【Hábitos creados al convivir】', loss:'【Lo relacionado con el miedo a perder】', imagined:'【Mis expectativas e imaginación】', reality:'【Cómo describo la realidad】', modules:'【Lo que este resultado señaló】', reflection:'【Una pregunta para mí】' },
  fr: { title:'《Journal d’amour étoilé | Résultat de clarté》', situation:'【Situation】', facts:'【Les faits que je connais】', interpretation:'【Mon interprétation】', unknown:'【Ce que je ne sais pas encore】', feelings:'【Mes émotions】', observations:'【Ce que j’ai observé】', needs:'【Ce dont j’ai besoin maintenant】', next:'【Ma prochaine étape】', investment:'【Mon investissement】', responses:'【Les réponses observables que j’ai rapportées】', result:'【Résultat actuel】', note:'【Ce que je veux ajouter】', real:'【La personne réelle que je vois】', habit:'【Les habitudes créées ensemble】', loss:'【Ce qui touche à la peur de perdre】', imagined:'【Mes attentes et mon imaginaire】', reality:'【La réalité telle que je la décris】', modules:'【Ce que ce résultat a fait émerger】', reflection:'【Une question pour moi】' },
}
const guidance: Record<Locale, Record<'organize'|'boat'|'like', string>> = {
  'zh-TW': { organize:'【想請你怎麼陪我聊】\n請分開事實、我的解讀、未知、感受與需要；解讀不等於事實，觀察也不等於對方的動機。不要否定感受、猜對方心意或替我做關係決定。一次只問一個問題，我可以隨時停止；帶我回到「現在的我，需要什麼？」最後幫我整理一小段「今天的我」。', boat:'【想請你怎麼陪我聊】\n投入多不等於愛得比較深；可觀察回應不等於對方心意，未知請保留為未知。資訊不足時請承認不足，不猜心也不替我做關係決定。一次只問一個問題，我可以隨時停止；若我問他喜不喜歡我，請回到真正觀察到的行為與我的需要。', like:'【想請你怎麼陪我聊】\n不要判定我愛或不愛，也不要說我只是習慣。這些面向不是唯一答案，多種感受可以同時存在。先從留給我的問題開始，一次只問一個問題，我可以隨時停止，不替我做關係決定。最後幫我整理現在真正捨不得、珍惜或期待的是什麼。' },
  en: { organize:'【How I would like support】\nKeep facts, my interpretations, unknowns, feelings, and needs separate. An interpretation is not a fact, and observations are not another person’s motives. Do not dismiss feelings, guess their mind, or decide my relationship. Ask one question at a time; I may stop anytime. Return to: “What do I need now?” End with a short “me today.”', boat:'【How I would like support】\nMore investment does not mean deeper love; observable responses do not prove another person’s feelings, and unknowns should remain unknown. Acknowledge insufficient information. Do not mind-read or decide my relationship. Ask one question at a time; I may stop anytime. If I ask whether they like me, return to observable behavior and my own needs.', like:'【How I would like support】\nDo not decide whether I love them or say it is only habit. These dimensions are not one final answer; several feelings can coexist. Start with my reflection question, ask one question at a time, and let me stop anytime. Do not decide my relationship. End by helping me name what I am truly reluctant to lose, cherish, or hope for now.' },
  ja: { organize:'【話し方のお願い】\n事実、解釈、未知、気持ち、必要なことを分けてください。解釈は事実ではなく、観察は相手の気持ちの証明ではありません。気持ちを否定せず、相手の心を決めつけず、関係の決定もしないでください。一度に一つ質問し、私はいつでも止められます。「今の私は何が必要？」に戻り、最後に今日の私を短くまとめてください。', boat:'【話し方のお願い】\n投じた気持ちの多さは愛の深さではなく、見えた反応は相手の気持ちの証明ではありません。分からないことは分からないままにし、情報不足を認めてください。心を決めつけず、関係を決めず、一度に一つ質問してください。私はいつでも止められます。', like:'【話し方のお願い】\n愛かどうかを判定せず、「ただの習慣」とも言わないでください。複数の気持ちは同時に存在できます。問いから始め、一度に一つ質問し、私はいつでも止められます。関係を決めず、今何を惜しみ大切にし期待しているかを整理してください。' },
  ko: { organize:'【대화에서 바라는 점】\n사실, 해석, 모르는 점, 감정, 필요를 나누어 주세요. 해석은 사실이 아니고 관찰은 상대의 마음이 아닙니다. 감정을 부정하거나 상대 마음을 추측하거나 관계를 대신 결정하지 마세요. 한 번에 한 가지씩 묻고 저는 언제든 멈출 수 있어요. “지금 내게 필요한 것은?”으로 돌아와 오늘의 나를 짧게 정리해 주세요.', boat:'【대화에서 바라는 점】\n더 많이 마음을 쏟았다고 사랑이 더 깊은 것은 아니며, 관찰한 반응은 상대 마음의 증거가 아닙니다. 모르는 것은 모르는 채로 두고 정보가 부족하면 인정해 주세요. 마음을 추측하거나 관계를 대신 결정하지 말고 한 번에 한 가지씩 물어봐 주세요. 저는 언제든 멈출 수 있어요.', like:'【대화에서 바라는 점】\n내가 사랑하는지 판단하거나 그저 습관이라고 말하지 마세요. 여러 감정이 함께 있을 수 있습니다. 질문에서 시작해 한 번에 하나씩 묻고 저는 언제든 멈출 수 있어요. 관계를 대신 결정하지 말고 지금 무엇을 아쉬워하고 소중히 여기며 기대하는지 정리해 주세요.' },
  es: { organize:'【Cómo me gustaría conversar】\nSepara hechos, interpretaciones, incógnitas, emociones y necesidades. Una interpretación no es un hecho y las observaciones no prueban las motivaciones de otra persona. No invalides mis emociones, no adivines su mente ni decidas mi relación. Haz una pregunta cada vez; puedo parar cuando quiera. Vuelve a: “¿Qué necesito ahora?” y termina con un breve “yo de hoy”.', boat:'【Cómo me gustaría conversar】\nImplicarme más no significa amar más; las respuestas observables no prueban lo que siente la otra persona y lo desconocido debe seguir siéndolo. Reconoce cuando falta información. No adivines su mente ni decidas mi relación. Haz una pregunta cada vez; puedo parar cuando quiera. Si pregunto si le gusto, vuelve a las conductas observables y a mis necesidades.', like:'【Cómo me gustaría conversar】\nNo dictamines si le amo ni digas que es solo costumbre. Estas dimensiones no son una única respuesta; pueden coexistir varias emociones. Empieza con mi pregunta de reflexión, haz una pregunta cada vez y puedo parar cuando quiera. No decidas mi relación. Ayúdame a nombrar qué me cuesta soltar, qué valoro o qué espero ahora.' },
  fr: { organize:'【Comment j’aimerais être accompagnée】\nDistinguez faits, interprétations, inconnues, émotions et besoins. Une interprétation n’est pas un fait et les observations ne prouvent pas les intentions de l’autre. Ne niez pas mes émotions, ne devinez pas ses pensées et ne décidez pas de ma relation. Posez une question à la fois; je peux arrêter quand je veux. Revenez à : « De quoi ai-je besoin maintenant ? » puis résumez brièvement « moi aujourd’hui ».', boat:'【Comment j’aimerais être accompagnée】\nS’investir davantage ne veut pas dire aimer davantage; les réponses observables ne prouvent pas les sentiments de l’autre et l’inconnu doit rester inconnu. Reconnaissez le manque d’informations. Ne lisez pas dans ses pensées et ne décidez pas de ma relation. Posez une question à la fois; je peux arrêter quand je veux. Si je demande s’il m’aime, revenez aux comportements observables et à mes besoins.', like:'【Comment j’aimerais être accompagnée】\nNe décidez pas si je l’aime et ne dites pas que ce n’est qu’une habitude. Ces dimensions ne donnent pas une réponse unique; plusieurs émotions peuvent coexister. Commencez par ma question de réflexion, posez une question à la fois et je peux arrêter quand je veux. Ne décidez pas de ma relation. Aidez-moi à nommer ce que je regrette de perdre, chéris ou espère aujourd’hui.' },
}
function block(label: string, value?: string) { return value ? `${label}\n${value}` : '' }
function list<TValue extends string>(values: TValue[] | undefined, prefix: string, translate: T) { return values?.map((value) => translate(key(prefix + value))).join('、') }

export function buildOrganizeFeelingsAiHandoffText(record: ClearRecord, locale: Locale, t: T) {
  const h = heading[locale]; const observation = Object.entries(record.observations ?? {}).map(([name, answer]) => `${t(key('clear.organize.observation.' + name))}: ${t(key('clear.organize.answer.' + answer))}`).join('\n')
  const emotion = `${list(record.emotions, 'clear.organize.emotion.', t) ?? ''}${record.emotions.length ? ` · ${record.emotionIntensity} / 5` : ''}${record.bodySensations?.length ? `\n${list(record.bodySensations, 'clear.organize.body.', t)}` : ''}`
  const action = record.nextActionType ? t(key('clear.organize.action.' + record.nextActionType)) : record.nextActionText
  return [h.title, block(h.situation, [record.triggerType ? t(key('clear.organize.trigger.' + record.triggerType)) : '', record.triggerText].filter(Boolean).join('\n')), block(h.facts, record.facts), block(h.interpretation, record.interpretation), block(h.unknown, record.unknown), block(h.feelings, emotion), block(h.observations, observation), block(h.needs, list(record.needs, 'clear.organize.need.', t)), block(h.next, action), block(h.result, t('clear.organize.closing')), guidance[locale].organize].filter(Boolean).join('\n\n')
}
export function buildLoveBoatAiHandoffText(record: LoveBoatAssessment, locale: Locale, t: T) {
  const h = heading[locale]; const a = Object.entries(record.aAnswers).map(([q,a]) => `${t(key('clear.boat.q.' + q))}: ${t(key('clear.boat.answer.' + a))}`).join('\n'); const b = Object.entries(record.bAnswers).map(([q,a]) => `${t(key('clear.boat.q.' + q))}: ${t(key('clear.boat.response.' + a))}`).join('\n')
  const title = record.crossResultKey ? t(key('clear.boat.result.' + record.crossResultKey)) : record.aLevel ? t(key('clear.boat.insufficientTitle.' + record.aLevel)) : undefined
  const insufficient = { 'zh-TW':'目前可觀察資訊仍不足，因此沒有關係矩陣結論。', en:'Observable information is still insufficient, so there is no relationship-matrix conclusion.', ja:'今は観察できる情報がまだ不足しているため、関係マトリクスの結論はありません。', ko:'현재 관찰할 수 있는 정보가 아직 부족하므로 관계 매트릭스 결론은 없습니다.', es:'La información observable aún es insuficiente, por lo que no hay una conclusión de matriz de relación.', fr:'Les informations observables restent insuffisantes : il n’y a donc pas de conclusion de matrice relationnelle.' }[locale]
  const result = record.crossResultKey ? `${title}\n${t(key('clear.boat.resultBody.' + record.crossResultKey + '.' + (record.resultVariantIndex ?? 0)))}` : title ? `${title}\n${insufficient}\n${t('clear.boat.result.insufficient')}` : undefined
  const investment = [a, record.aScore === undefined ? '' : t('clear.boat.scoreA', { score: record.aScore }), record.aLevel ? t(key('clear.boat.level.' + record.aLevel)) : ''].filter(Boolean).join('\n')
  const responses = [b, record.bAnsweredItems === undefined ? '' : String(record.bAnsweredItems), record.bResponseRatio === undefined ? '' : `${Math.round(record.bResponseRatio * 100)}%`, record.bLevel ? t(key('clear.boat.level.' + record.bLevel)) : ''].filter(Boolean).join('\n')
  return [h.title, block(h.investment, investment), block(h.responses, responses), block(h.result, result), block(h.note, record.noteToSay), guidance[locale].boat].filter(Boolean).join('\n\n')
}
export function buildLikeOrHabitAiHandoffText(record: LikeOrHabitReflection, locale: Locale, t: T) {
  const h = heading[locale]; const a=record.answers; const freeTextFields = new Set(['otherText', 'imagined_relationship_reality_description']); const answer=(section: keyof typeof a) => Object.entries(a[section] ?? {}).filter(([q,v]) => !freeTextFields.has(q) && typeof v === 'string' && v.trim()).map(([q,v]) => {
    const question = t(key('clear.like.q.' + q)); const response = t(key('clear.like.answer.' + v))
    return question && response ? `${question}: ${response}` : ''
  }).filter(Boolean).join('\n'); const modules=(record.activeResultModules ?? []).map((m) => `${t(key('clear.like.module.' + m + '.title'))}\n${t(key('clear.like.module.' + m + '.body'))}`).join('\n')
  const root = record.resultVariantKey ? 'clear.like.result.' + record.resultVariantKey : undefined
  const result = root ? [t(key(root + '.title')), t(key(root + '.body'))].join('\n') : undefined
  return [h.title, block(h.real, [answer('realPerson'), record.realPersonNote].filter(Boolean).join('\n')), block(h.habit, [answer('habit'),record.habitNote].filter(Boolean).join('\n')), block(h.loss, [answer('fearOfLoss'),a.fearOfLoss?.otherText].filter(Boolean).join('\n')), block(h.imagined, answer('imaginedRelationship')), block(h.reality, a.imaginedRelationship?.imagined_relationship_reality_description), block(h.modules, modules), block(h.result, result), block(h.reflection, root ? t(key(root + '.reflection')) : undefined), guidance[locale].like].filter(Boolean).join('\n\n')
}

export function buildClearFreeTalkAiHandoffText(text: string, locale: Locale) {
  const copy = {
    'zh-TW': ['《星星戀愛日記｜我想聊聊》', '【我想說的話】', '【想請你怎麼陪我聊】', '請先理解我寫下的內容，不要急著分析或給答案。不要替我貼標籤、猜對方心意或替我做關係決定。若事實、猜測、感受混在一起，請一次問一個問題，慢慢陪我分開看；我可以隨時停止。也請溫和帶我回來問：「那我自己呢？」最後幫我整理一小段「今天的我」。'],
    en: ['《Starry Love Diary | I want to talk》', '【What I want to say】', '【How I would like support】', 'First understand what I wrote; do not rush to analyze or answer. Do not label me, guess another person’s feelings, or decide my relationship. If facts, guesses, and feelings are mixed, ask one question at a time and help me separate them. I can stop anytime. Gently return to: “What about me?” End with a short “me today.”'],
    ja: ['《星空恋愛日記｜話したいこと》', '【話したいこと】', '【話し方のお願い】', 'まず私が書いたことを理解し、急いで分析や答えを出さないでください。私にラベルを貼らず、相手の気持ちを推測せず、関係を決めないでください。一度に一つ質問し、私はいつでも止められます。最後に「今日の私」を短くまとめてください。'],
    ko: ['《별빛 연애 일기 | 이야기하고 싶어요》', '【하고 싶은 말】', '【대화에서 바라는 점】', '먼저 내가 쓴 내용을 이해해 주세요. 성급히 분석하거나 답을 내리지 말고, 나에게 꼬리표를 붙이거나 상대 마음을 추측하거나 관계를 대신 결정하지 마세요. 한 번에 한 가지씩 묻고 저는 언제든 멈출 수 있어요. 마지막에 오늘의 나를 짧게 정리해 주세요.'],
    es: ['《Diario de Amor Estrellado | Quiero hablar》', '【Lo que quiero decir】', '【Cómo me gustaría conversar】', 'Primero comprende lo que escribí; no te apresures a analizar o responder. No me etiquetes, no adivines los sentimientos de la otra persona ni decidas mi relación. Haz una pregunta cada vez; puedo parar cuando quiera. Al final ayúdame a resumir mi yo de hoy.'],
    fr: ['《Journal d’amour étoilé | J’ai envie de parler》', '【Ce que je veux dire】', '【Comment j’aimerais être accompagnée】', 'Commencez par comprendre ce que j’ai écrit, sans vous précipiter pour analyser ou répondre. Ne me collez pas d’étiquette, ne devinez pas les sentiments de l’autre et ne décidez pas de ma relation. Posez une question à la fois; je peux arrêter quand je veux. Terminez par un court résumé de moi aujourd’hui.'],
  }[locale]
  return `${copy[0]}\n\n${copy[1]}\n${text}\n\n${copy[2]}\n${copy[3]}`
}
