import { Capacitor, registerPlugin } from '@capacitor/core'
import { Directory, Filesystem } from '@capacitor/filesystem'
import { Share } from '@capacitor/share'
import { encodeTextExportUtf8 } from './exportTextData'

const STORAGE_KEY = 'starry-love-diary:qa12-diagnostics:v6', LEGACY_STORAGE_KEY = 'starry-love-diary:qa12-diagnostics:v5', MAX_EVENTS = 160, OBSERVATION_MS = 1500, BUILD = 24
type NativeQa12Diagnostics = { schemaVersion:number; nativeSessionId:string; launchTimestamp:string; counters:Record<string,number>; records:unknown[] }
const nativeQa12Diagnostics = registerPlugin<{ getDiagnostics: () => Promise<NativeQa12Diagnostics> }>('Qa12NativeDiagnostics')
export type Qa12InteractionType = 'touchstart'|'touchmove'|'touchend'|'touchcancel'|'pointerdown'|'pointermove'|'pointerup'|'pointercancel'|'click'
export type Qa12EventType = 'boot'|'visibilitychange'|'foreground-resume'|'pageshow'|'pagehide'|'focus'|'blur'|'online'|'offline'|'error'|'unhandledrejection'|'overlay-state-change'|'busy-state-change'|'manual-snapshot'|'input'|'react-handler'|'navigation-intent'|'router-location-render'|'router-observer-mount'|'router-observer-unmount'|'location-change'|'destination-commit'|'navigation-incomplete'|'interaction-summary'
export interface Qa12Event { type:Qa12EventType; timestamp:string; sessionId:string; foregroundResumeId:string; pathname:string; interactionId?:string; navAttemptId?:string; source?:string; requestedDestination?:string; sameRoute?:boolean; previousPathname?:string; destinationId?:string; routerPathname?:string; browserPathname?:string; previousRouterPathname?:string|null; pathnameChanged?:boolean; observerMountId?:string|null; observerMounted?:boolean; lastRouterPathname?:string|null; input?:Record<string,unknown>; stages?:Record<string,boolean>; durationMs?:number; visibility?:DocumentVisibilityState|'unknown'; focused?:boolean; busyElementCount?:number; busyElementTag?:string; busyElementRole?:string; busyElementAriaLabel?:string; backgroundDurationMs?:number; persisted?:boolean; errorCategory?:'error'|'unhandledrejection'; errorName?:string }
export interface Qa12DiagnosticLog { format:'starry-love-diary-qa12-diagnostics'; diagnosticSchemaVersion:6; appVersion:'1.0.0'; build:number; sessionId:string; events:Qa12Event[]; interactionTotals:Record<Qa12InteractionType,number> }
type StoredQa12DiagnosticLog = Partial<Omit<Qa12DiagnosticLog, 'diagnosticSchemaVersion'>> & { diagnosticSchemaVersion?: number }
type I = { interactionId:string; source:string; startedAt:number; x?:number; y?:number; movementDistance:number; stages:Record<string,boolean>; timer:ReturnType<typeof setTimeout> }
type P = { navAttemptId:string; source:string; requestedDestination:string; interactionId?:string; sameRoute:boolean; timer:ReturnType<typeof setTimeout> }
let active:R|undefined
type PendingObserver = { observerMountId?: string; observerMounted: boolean; lastRouterPathname?: string; sequence: number }
let pendingObserver: PendingObserver = { observerMounted: false, sequence: 0 }
const counts=():Record<Qa12InteractionType,number>=>({touchstart:0,touchmove:0,touchend:0,touchcancel:0,pointerdown:0,pointermove:0,pointerup:0,pointercancel:0,click:0})
const sid=()=>globalThis.crypto?.randomUUID?.()??'qa12-'+Date.now(), store=()=>{try{return localStorage}catch{return undefined}}, empty=():Qa12DiagnosticLog=>({format:'starry-love-diary-qa12-diagnostics',diagnosticSchemaVersion:6,appVersion:'1.0.0',build:BUILD,sessionId:sid(),events:[],interactionTotals:counts()})
function read(){try{const saved=store(), raw=saved?.getItem(STORAGE_KEY)??saved?.getItem(LEGACY_STORAGE_KEY)??'', x=JSON.parse(raw)as StoredQa12DiagnosticLog;return (x.diagnosticSchemaVersion===5||x.diagnosticSchemaVersion===6)&&(x.build===13||x.build===BUILD)&&Array.isArray(x.events)?{...empty(),sessionId:x.sessionId??sid(),events:x.events.slice(-MAX_EVENTS),interactionTotals:{...counts(),...x.interactionTotals}}:empty()}catch{return empty()}}
function write(x:Qa12DiagnosticLog){try{store()?.setItem(STORAGE_KEY,JSON.stringify(x))}catch{/* observational */}}
const source=(t:EventTarget|null)=>t instanceof Element?t.closest<HTMLElement>('[data-qa12-navigation-source]')?.dataset.qa12NavigationSource:undefined
const desc=(n:Element|null)=>n?.closest<HTMLElement>('[data-qa12-navigation-source]')?.dataset.qa12NavigationSource??(n?.closest('button')?'button':n?.closest('a')?'link':n?.tagName.toLowerCase()??'none')

class R {
  log=read(); foregroundResumeId='initial'; resume=0; hiddenAt:number|undefined; interactions=new Map<string,I>(); pending=new Map<string,P>(); lastPath:string; lastRouterPathname:string|undefined; observerMountId:string|undefined; observerMounted=false; overlayKey:string; busyCount:number
  constructor(readonly d:Document,readonly w:Window){this.log.sessionId=sid();this.lastPath=w.location.pathname;this.overlayKey=this.overlays();this.busyCount=d.querySelectorAll('[aria-busy=true]').length}
  record(type:Qa12EventType,x:Omit<Partial<Qa12Event>,'type'|'timestamp'|'sessionId'|'foregroundResumeId'|'pathname'>={}){this.log.events.push({type,timestamp:new Date().toISOString(),sessionId:this.log.sessionId,foregroundResumeId:this.foregroundResumeId,pathname:this.w.location.pathname,visibility:this.d.visibilityState??'unknown',focused:this.d.hasFocus(),busyElementCount:this.d.querySelectorAll('[aria-busy=true]').length,...x});this.log.events=this.log.events.slice(-MAX_EVENTS);write(this.log)}
  overlays(){return[...this.d.querySelectorAll<HTMLElement>('[data-qa12-overlay]')].map(n=>n.dataset.qa12Overlay).filter(Boolean).sort().join('|')}
  busyDescriptor(){const n=this.d.querySelector<HTMLElement>('[aria-busy=true]');return n?{busyElementTag:n.tagName.toLowerCase(),busyElementRole:n.getAttribute('role')??undefined,busyElementAriaLabel:n.getAttribute('aria-label')??undefined}:{}}
  observe(){const overlay=this.overlays(),busy=this.d.querySelectorAll('[aria-busy=true]').length;if(overlay!==this.overlayKey){this.overlayKey=overlay;this.record('overlay-state-change')}if(busy!==this.busyCount){this.busyCount=busy;this.record('busy-state-change',this.busyDescriptor())}}
  observerSnapshot(){return{browserPathname:this.w.location.pathname,lastRouterPathname:this.lastRouterPathname??null,observerMountId:this.observerMountId??null,observerMounted:this.observerMounted}}
  observerMount(observerMountId:string){this.observerMountId=observerMountId;this.observerMounted=true;this.record('router-observer-mount',this.observerSnapshot());return observerMountId}
  restoreObserver(observer:PendingObserver){this.lastRouterPathname=observer.lastRouterPathname;if(observer.observerMounted&&observer.observerMountId)this.observerMount(observer.observerMountId)}
  observerUnmount(observerMountId:string){if(this.observerMountId!==observerMountId)return;this.observerMounted=false;this.record('router-observer-unmount',this.observerSnapshot())}
  i(s:string){let i=this.interactions.get(s);if(i)return i;const id=this.log.sessionId+':interaction:'+Date.now()+':'+this.interactions.size;i={interactionId:id,source:s,startedAt:Date.now(),movementDistance:0,stages:{},timer:setTimeout(()=>this.summary(s),OBSERVATION_MS)};this.interactions.set(s,i);return i}
  input(e:Event,type:Qa12InteractionType){
    this.log.interactionTotals[type]++
    const s=source(e.target),move=type==='touchmove'||type==='pointermove'
    // V5 deliberately does not serialize the full log for uncorrelated move noise.
    if(!s){if(!move)write(this.log);return}
    const i=this.i(s),p=e as PointerEvent,t=e as TouchEvent,c=t.changedTouches?.[0],x=typeof p.clientX==='number'?p.clientX:c?.clientX,y=typeof p.clientY==='number'?p.clientY:c?.clientY
    if(x!==undefined&&i.x===undefined){i.x=x;i.y=y}
    const dx=x===undefined||i.x===undefined?undefined:x-i.x,dy=y===undefined||i.y===undefined?undefined:y-(i.y??0),distance=dx===undefined||dy===undefined?i.movementDistance:Math.hypot(dx,dy)
    i.movementDistance=Math.max(i.movementDistance,distance);i.stages[type]=true
    if(move&&i.stages[type+'Logged'])return
    if(move)i.stages[type+'Logged']=true
    const n=e.target instanceof Element?e.target:null,hit=x===undefined||y===undefined?null:this.d.elementFromPoint?.(x,y)??null,v=this.w.visualViewport
    this.record('input',{interactionId:i.interactionId,source:s,input:{eventType:type,pointerId:p.pointerId,pointerType:p.pointerType||undefined,isPrimary:p.isPrimary,button:p.button,buttons:p.buttons,target:desc(n),actionableAncestor:desc(n?.closest('button,a,[role=button]')??null),clientX:x,clientY:y,initialX:i.x,initialY:i.y,deltaX:dx,deltaY:dy,movementDistance:distance,touchesLength:t.touches?.length,changedTouchesLength:t.changedTouches?.length,hitTestTarget:desc(hit),scrollX:this.w.scrollX,scrollY:this.w.scrollY,elapsedMs:Date.now()-i.startedAt,visualViewport:v?{offsetLeft:v.offsetLeft,offsetTop:v.offsetTop,width:v.width,height:v.height,scale:v.scale}:undefined}})
  }
  summary(s:string){const i=this.interactions.get(s);if(!i)return;this.record('interaction-summary',{interactionId:i.interactionId,source:s,stages:i.stages,durationMs:Date.now()-i.startedAt});this.interactions.delete(s)}
  match(path:string){return[...this.pending.values()].find(x=>new URL(x.requestedDestination,this.w.location.origin).pathname===path)}
  handler(s:string,dest:string){const i=this.i(s),id=this.log.sessionId+':nav:'+Date.now()+':'+this.pending.size,sameRoute=new URL(dest,this.w.location.origin).pathname===this.w.location.pathname;i.stages.reactHandler=true;i.stages.navigationIntent=true;this.record('react-handler',{interactionId:i.interactionId,navAttemptId:id,source:s,requestedDestination:dest,sameRoute});this.record('navigation-intent',{interactionId:i.interactionId,navAttemptId:id,source:s,requestedDestination:dest,sameRoute});const timer=setTimeout(()=>{const p=this.pending.get(id);if(p){this.record('navigation-incomplete',{interactionId:p.interactionId,navAttemptId:id,source:s,requestedDestination:dest,sameRoute:p.sameRoute,stages:i.stages,...this.observerSnapshot()});this.pending.delete(id)}},OBSERVATION_MS);this.pending.set(id,{navAttemptId:id,source:s,requestedDestination:dest,interactionId:i.interactionId,sameRoute,timer});return id}
  routerLocationRendered(path:string){const previousRouterPathname=this.lastRouterPathname;this.lastRouterPathname=path;if(previousRouterPathname===path)return;const p=this.match(path);this.record('router-location-render',{routerPathname:path,previousRouterPathname:previousRouterPathname??null,pathnameChanged:previousRouterPathname!==undefined,navAttemptId:p?.navAttemptId,interactionId:p?.interactionId,source:p?.source,requestedDestination:p?.requestedDestination,sameRoute:p?.sameRoute,...this.observerSnapshot()})}
  location(path:string){const p=this.match(path),i=p&&this.interactions.get(p.source);if(i)i.stages.locationChange=true;this.record('location-change',{previousPathname:this.lastPath,navAttemptId:p?.navAttemptId,interactionId:p?.interactionId,source:p?.source,requestedDestination:p?.requestedDestination,sameRoute:p?.sameRoute});this.lastPath=path;this.commit(path,p)}
  commit(path:string,p=this.match(path)){const i=p&&this.interactions.get(p.source);if(i)i.stages.destinationCommit=true;this.record('destination-commit',{destinationId:'route:'+path,navAttemptId:p?.navAttemptId,interactionId:p?.interactionId,source:p?.source,requestedDestination:p?.requestedDestination,sameRoute:p?.sameRoute});if(p){clearTimeout(p.timer);this.pending.delete(p.navAttemptId)}}
  lifecycle(type:Qa12EventType,persisted?:boolean){if(type==='visibilitychange'&&this.d.visibilityState==='hidden')this.hiddenAt=Date.now();this.record(type,{persisted});if((type==='visibilitychange'||type==='pageshow')&&this.d.visibilityState==='visible'&&this.hiddenAt!==undefined){const backgroundDurationMs=Date.now()-this.hiddenAt;this.hiddenAt=undefined;this.foregroundResumeId='resume:'+(++this.resume);this.record('foreground-resume',{backgroundDurationMs})}}
  dispose(){this.pending.forEach(p=>clearTimeout(p.timer));this.interactions.forEach(i=>clearTimeout(i.timer))}
}

export const getQa12Diagnostics=()=>read()
export const clearQa12DiagnosticsForTest=()=>{pendingObserver={ observerMounted:false, sequence:0 };try{store()?.removeItem(LEGACY_STORAGE_KEY)}catch{/* observational */}write(empty())}
export const qa12NavigationHandler=(s:string,d:string)=>active?.handler(s,d)
export const qa12RouterLocationRendered=(p:string)=>{if(active)active.routerLocationRendered(p);else pendingObserver.lastRouterPathname=p}
export const qa12LocationCommitted=(p:string)=>active?.location(p)
export const qa12RouteObserverMounted=()=>{const observerMountId='router-observer:'+Date.now()+':'+(++pendingObserver.sequence);if(active)return active.observerMount(observerMountId);pendingObserver={...pendingObserver,observerMountId,observerMounted:true};return observerMountId}
export const qa12RouteObserverUnmounted=(observerMountId:string)=>{if(active)active.observerUnmount(observerMountId);else if(pendingObserver.observerMountId===observerMountId)pendingObserver={...pendingObserver,observerMounted:false}}
export function installQa12Diagnostics(d:Document=document,w:Window=window){const r=new R(d,w);active=r;r.restoreObserver(pendingObserver);const ls:Array<[EventTarget,string,EventListener,AddEventListenerOptions|undefined]>=[[d,'visibilitychange',(()=>r.lifecycle('visibilitychange'))as EventListener,undefined],[w,'pageshow',((e:PageTransitionEvent)=>r.lifecycle('pageshow',e.persisted))as EventListener,undefined],[w,'pagehide',((e:PageTransitionEvent)=>r.lifecycle('pagehide',e.persisted))as EventListener,undefined],[w,'focus',(()=>r.lifecycle('focus'))as EventListener,undefined],[w,'blur',(()=>r.lifecycle('blur'))as EventListener,undefined],...(['touchstart','touchmove','touchend','touchcancel','pointerdown','pointermove','pointerup','pointercancel','click']as Qa12InteractionType[]).map(t=>[d,t,((e:Event)=>r.input(e,t))as EventListener,{capture:true,passive:true}]as[EventTarget,string,EventListener,AddEventListenerOptions]),[w,'error',((e:ErrorEvent)=>r.record('error',{errorCategory:'error',errorName:e.error instanceof Error?e.error.name:undefined}))as EventListener,undefined],[w,'unhandledrejection',((e:PromiseRejectionEvent)=>r.record('unhandledrejection',{errorCategory:'unhandledrejection',errorName:e.reason instanceof Error?e.reason.name:undefined}))as EventListener,undefined]];ls.forEach(x=>x[0].addEventListener(x[1],x[2],x[3]));const observer=typeof MutationObserver==='undefined'||!d.body?undefined:new MutationObserver(()=>r.observe());observer?.observe(d.body,{subtree:true,childList:true,attributes:true,attributeFilter:['aria-busy','data-qa12-overlay','class']});r.record('boot');return{snapshot:()=>r.record('manual-snapshot'),dispose:()=>{observer?.disconnect();ls.forEach(x=>x[0].removeEventListener(x[1],x[2],x[3]));r.dispose();if(active===r)active=undefined}}}
export function createQa12DiagnosticExport(nativeDiagnostics?:NativeQa12Diagnostics){return{filename:'starry-love-diary-qa12-diagnostics.json',content:JSON.stringify(nativeDiagnostics?{...getQa12Diagnostics(),nativeDiagnostics}:getQa12Diagnostics(),null,2)}}
async function getNativeQa12Diagnostics(){if(!Capacitor.isNativePlatform()||Capacitor.getPlatform()!== 'ios')return undefined;try{return await nativeQa12Diagnostics.getDiagnostics()}catch{return undefined}}
export async function exportQa12Diagnostics(o:{isNativePlatform?:()=>boolean;canShare?:()=>Promise<{value:boolean}>;writeFile?:(x:{path:string;data:string;directory:Directory})=>Promise<{uri:string}>;share?:(x:{files:string[]})=>Promise<unknown>;deleteFile?:(x:{path:string;directory:Directory})=>Promise<unknown>;download?:(x:string,n:string)=>void}={}){const x=createQa12DiagnosticExport(await getNativeQa12Diagnostics());if(!(o.isNativePlatform??(()=>Capacitor.isNativePlatform()))()){o.download?.(x.content,x.filename);return'downloaded' as const}let written=false;try{if(!(await(o.canShare??(()=>Share.canShare()))()).value)return'unsupported' as const;const f=await(o.writeFile??(x=>Filesystem.writeFile(x)))({path:x.filename,data:encodeTextExportUtf8(x.content),directory:Directory.Cache});written=true;await(o.share??(x=>Share.share(x)))({files:[f.uri]});return'share-sheet-opened' as const}catch(e){return e instanceof Error&&/cancel/i.test(e.message)?'cancelled' as const:'error' as const}finally{if(written)await (o.deleteFile??(x=>Filesystem.deleteFile(x)))({path:x.filename,directory:Directory.Cache}).catch(()=>undefined)}}
