import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { App } from '../app/App'
import { I18nProvider } from '../i18n/I18nProvider'

const renderPreview = () => render(<I18nProvider initialLocale="zh-TW"><MemoryRouter initialEntries={['/our/love-delivery/confirmation-preview']}><App /></MemoryRouter></I18nProvider>)
afterEach(cleanup)

describe('Love Delivery limited-turn confirmation preview', () => {
  it('renders the confirmation route with exactly the three pending actions', () => {
    renderPreview()
    expect(screen.getByRole('heading', { level: 1, name: '💕 確認戀愛外送單' })).toBeInTheDocument()
    for (const label of ['接受邀約', '婉拒', '提議修改']) expect(screen.getByRole('button', { name: label })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /回覆|聊天|通話/u })).not.toBeInTheDocument()
  })

  it('uses local accepted and declined states without a proposal or reason field', () => {
    renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '接受邀約' }))
    expect(screen.getByRole('status')).toHaveTextContent('已接受戀愛外送單（介面預覽）')
    expect(screen.queryByRole('button', { name: '提議修改' })).not.toBeInTheDocument()
    cleanup(); renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '婉拒' }))
    expect(screen.getByRole('status')).toHaveTextContent('已婉拒戀愛外送單（介面預覽）')
    expect(document.querySelectorAll('textarea,input[type="tel"],input[type="email"]')).toHaveLength(0)
  })

  it('limits editing to schedule, location, and one grapheme-aware short note, and cancel discards it', () => {
    renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '提議修改' }))
    expect(screen.getByRole('heading', { level: 2, name: '提議調整邀約' })).toBeInTheDocument()
    expect(screen.getByLabelText('日期')).toHaveValue('2026-10-05')
    expect(screen.getByLabelText('開始時間')).toHaveTextContent('09:30')
    expect(screen.getByLabelText('結束時間')).toHaveTextContent('13:00')
    expect(screen.getByLabelText('地點')).toHaveValue('六堆客家文化村')
    const note = screen.getByLabelText('想補充一句')
    fireEvent.change(note, { target: { value: `${'💗'.repeat(200)}多` } })
    expect(note).toHaveValue('💗'.repeat(200))
    expect(screen.getByText('200 / 200')).toBeInTheDocument()
    expect(screen.queryByLabelText('我想和你……')).not.toBeInTheDocument()
    fireEvent.click(screen.getAllByRole('button', { name: '取消' }).at(-1)!)
    expect(screen.getByRole('button', { name: '提議修改' })).toBeInTheDocument()
    expect(screen.queryByRole('heading', { level: 2, name: '提議調整邀約' })).not.toBeInTheDocument()
  })

  it('validates time ordering and submits one structured proposal without a second turn', () => {
    renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '提議修改' }))
    fireEvent.click(screen.getByLabelText('結束時間'))
    fireEvent.change(screen.getByLabelText('小時'), { target: { value: '09' } })
    fireEvent.change(screen.getByLabelText('分鐘'), { target: { value: '30' } })
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: '確認' }))
    fireEvent.click(screen.getByRole('button', { name: '送出修改提議' }))
    expect(screen.getByRole('alert')).toHaveTextContent('結束時間需要晚於開始時間。')
    fireEvent.click(screen.getByLabelText('結束時間'))
    fireEvent.change(screen.getByLabelText('小時'), { target: { value: '14' } })
    fireEvent.change(screen.getByLabelText('分鐘'), { target: { value: '00' } })
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: '確認' }))
    fireEvent.change(screen.getByLabelText('想補充一句'), { target: { value: '我晚一點到，可以嗎？' } })
    fireEvent.click(screen.getByRole('button', { name: '送出修改提議' }))
    expect(screen.getByRole('heading', { level: 2, name: '對方提議這樣調整' })).toBeInTheDocument()
    expect(screen.getByText('原本邀約')).toBeInTheDocument()
    expect(screen.getByText('對方提議')).toBeInTheDocument()
    expect(screen.getByRole('status')).toHaveTextContent('修改提議已送出（介面預覽）')
    expect(screen.getByText('我晚一點到，可以嗎？')).toBeInTheDocument()
    for (const label of ['接受修改', '放棄這次邀約', '重新發一張戀愛外送單']) expect(screen.getByRole('button', { name: label })).toBeInTheDocument()
    for (const forbidden of ['提議修改', '再改一次', '回覆']) expect(screen.queryByRole('button', { name: forbidden })).not.toBeInTheDocument()
    expect(document.querySelectorAll('textarea')).toHaveLength(0)
  })

  it('uses proposed schedule values for the terminal accepted-modified result', () => {
    renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '提議修改' }))
    fireEvent.change(screen.getByLabelText('日期'), { target: { value: '2026-11-06' } })
    fireEvent.change(screen.getByLabelText('地點'), { target: { value: '新的集合地點' } })
    fireEvent.change(screen.getByLabelText('想補充一句'), { target: { value: '改成這個時間出發。' } })
    fireEvent.click(screen.getByRole('button', { name: '送出修改提議' }))
    fireEvent.click(screen.getByRole('button', { name: '接受修改' }))
    const status = screen.getByRole('status')
    expect(status).toHaveTextContent('💕 修改後的戀愛外送單已成立')
    for (const text of ['一起去餵魚', '明天想一起去湖邊走走。', '一包魚飼料', '最近有件事想跟你聊聊。', '新的集合地點', '09:30–13:00', '改成這個時間出發。']) expect(status).toHaveTextContent(text)
    expect(status).toHaveTextContent('2026年11月6日')
    expect(status).toHaveTextContent('這裡不會開啟聊天室或通話。')
    expect(status).not.toHaveTextContent(/AM|PM|上午|下午/u)
    expect(within(status).queryByRole('button')).not.toBeInTheDocument()
  })

  it('ends with cancellation or starts a fresh composer without retaining the proposal', () => {
    renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '提議修改' }))
    fireEvent.click(screen.getByRole('button', { name: '送出修改提議' }))
    fireEvent.click(screen.getByRole('button', { name: '放棄這次邀約' }))
    const cancelled = screen.getByRole('status')
    expect(cancelled).toHaveTextContent('這次戀愛外送單沒有成立')
    expect(document.querySelectorAll('textarea,input[type="tel"],input[type="email"]')).toHaveLength(0)
    expect(within(cancelled).queryByRole('button')).not.toBeInTheDocument()
    cleanup(); renderPreview()
    fireEvent.click(screen.getByRole('button', { name: '提議修改' }))
    fireEvent.click(screen.getByRole('button', { name: '送出修改提議' }))
    fireEvent.click(screen.getByRole('button', { name: '重新發一張戀愛外送單' }))
    expect(screen.getByRole('heading', { level: 1, name: '💕 戀愛外送單' })).toBeInTheDocument()
    expect(document.querySelector('.love-delivery-form textarea')).toHaveValue('')
  })
})
