import { useState } from 'react'
import { PageHeader, PrimaryButton, SecondaryButton, SoftCard } from '../components'
import { useI18n } from '../i18n/I18nContext'
import '../features/our/our.css'

const demo = { activity: '一起去餵魚', content: '明天想一起去湖邊走走。', item: '一包魚飼料', topic: '最近有件事想跟你聊聊。', date: '2026-10-05', start: '09:30', end: '13:00', location: '六堆客家文化村', note: '不見不散喔。' }
export function LoveDeliverySessionPreviewPage({ initialState = 'accepted' }: { initialState?: 'accepted' | 'completed' }) {
  const { locale, t } = useI18n(); const [state, setState] = useState<'accepted' | 'cancelled' | 'completed'>(initialState); const [confirming, setConfirming] = useState(false)
  const date = new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(`${demo.date}T00:00:00`))
  const rows: readonly [string, string][] = [[t('our.loveDelivery.typeLabel'), demo.activity], [t('our.loveDelivery.contentLabel'), demo.content], [t('our.loveDelivery.itemLabel'), demo.item], [t('our.loveDelivery.topicLabel'), demo.topic], [t('our.loveDelivery.dateLabel'), date], [t('our.loveDelivery.previewTime'), `${demo.start}–${demo.end}`], [t('our.loveDelivery.locationLabel'), demo.location], [t('our.loveDelivery.noteLabel'), demo.note]]
  const statusKey = state === 'accepted' ? 'sessionAccepted' : state === 'cancelled' ? 'sessionCancelled' : 'sessionCompleted'
  const bodyKey = state === 'accepted' ? 'sessionAcceptedBody' : state === 'cancelled' ? 'sessionCancelledBody' : 'sessionCompletedBody'
  return <div className="page our-page love-delivery-page"><PageHeader titleKey="our.loveDelivery.sessionTitle" variant="secondary" backFallback="/our/love-delivery/incoming-preview" /><main className="our-page__content love-delivery-page__content"><section className="love-delivery-hero"><img className="love-delivery-hero__art" src="/assets/love-delivery/love-delivery-hero-cat.png" alt={t('our.loveDelivery.sessionHeroAlt')} /><div className="love-delivery-hero__copy"><h2>{t('our.loveDelivery.sessionHeroTitle')}</h2><p>{t('our.loveDelivery.sessionHeroBody')}</p></div></section><SoftCard className="love-delivery-preview"><section className="love-delivery-incoming-result" role="status"><h2>{t(`our.loveDelivery.${statusKey}` as never)}</h2><p>{t(`our.loveDelivery.${bodyKey}` as never)}</p></section><dl>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{state === 'accepted' ? <PrimaryButton onClick={() => setConfirming(true)}>{t('our.loveDelivery.cancelSession')}</PrimaryButton> : null}</SoftCard></main>{confirming ? <div className="love-delivery-time-picker-backdrop" role="presentation"><section className="love-delivery-time-picker" role="dialog" aria-modal="true" aria-labelledby="love-delivery-cancel-title"><h2 id="love-delivery-cancel-title">{t('our.loveDelivery.cancelTitle')}</h2><p>{t('our.loveDelivery.cancelBody')}</p><footer><SecondaryButton onClick={() => setConfirming(false)}>{t('our.loveDelivery.cancelDismiss')}</SecondaryButton><PrimaryButton onClick={() => { setState('cancelled'); setConfirming(false) }}>{t('our.loveDelivery.cancelConfirm')}</PrimaryButton></footer></section></div> : null}</div>
}
