import { useEffect, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { PageHeader, PrimaryButton, SecondaryButton, SoftCard } from '../components'
import { starrySkyTopicById } from '../features/our/starrySkyTopics'
import { useI18n } from '../i18n/I18nContext'
import { usePersistence } from '../data/PersistenceStateContext'
import { cancelHeartTalkInvitation, completeHeartTalkInvitation, getHeartTalkState, type HeartTalkInvitation } from '../lib/firebase/heartTalkClient'
import '../features/our/our.css'

export function StarrySkySessionPreviewPage(_legacyPreviewProps: { initialStatus?: 'accepted' | 'cancelled' | 'completed'; now?: Date } = {}) {
  const { locale, t } = useI18n(); const navigate = useNavigate(); const [params] = useSearchParams()
  const persistence = usePersistence()
  const [invitation, setInvitation] = useState<HeartTalkInvitation>(); const [terminal, setTerminal] = useState<'cancelled' | 'completed'>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [confirmingCancel, setConfirmingCancel] = useState(false)
  const refresh = async () => { setBusy(true); setError(''); try { const state = await getHeartTalkState(); const id = params.get('invitation'); setInvitation(state.invitations.find((item) => item.status === 'accepted' && (!id || item.invitationId === id))) } catch { setError(t('our.starrySky.invitePreviewBody')) } finally { setBusy(false) } }
  useEffect(() => { void refresh() }, [])
  const mutate = async (action: 'cancel' | 'complete') => { if (!invitation) return; setBusy(true); try { if (action === 'cancel') await cancelHeartTalkInvitation(invitation.invitationId); else { await completeHeartTalkInvitation(invitation.invitationId); await persistence?.repositories.completedHeartTalks.addCompletedHeartTalk(invitation.topicType === 'official' && invitation.officialTopicId ? { sourceInvitationId: invitation.invitationId, topicType: 'official', questionId: invitation.officialTopicId, localDate: invitation.scheduledLocalDate, startTime: invitation.startTime, endTime: invitation.endTime } : { sourceInvitationId: invitation.invitationId, topicType: 'custom', localDate: invitation.scheduledLocalDate, startTime: invitation.startTime, endTime: invitation.endTime }); await persistence?.refreshHeartTalkCount() } setTerminal(action === 'cancel' ? 'cancelled' : 'completed'); await refresh() } catch { setError(t('our.starrySky.invitePreviewBody')); setBusy(false) } }
  const topic = invitation?.topicType === 'official' ? starrySkyTopicById(invitation.officialTopicId) : undefined
  const title = terminal === 'cancelled' ? t('our.starrySky.sessionCancelledTitle') : terminal === 'completed' ? t('our.starrySky.sessionCompletedTitle') : t('our.starrySky.sessionAcceptedTitle')
  const body = terminal === 'cancelled' ? t('our.starrySky.sessionCancelledBody') : terminal === 'completed' ? t('our.starrySky.sessionCompletedBody') : t('our.starrySky.sessionAcceptedBody')
  const prompt = invitation?.topicType === 'custom' ? invitation.customTopicText : topic ? `${topic.id} ${topic.text}` : terminal ? '✨ 自訂題目' : ''
  return <div className="page our-page starry-sky-page starry-sky-session-page"><PageHeader titleKey="our.starrySky.sessionTitle" variant="secondary" backFallback="/our/starry-sky" /><main className="our-page__content starry-sky-page__content"><section className="starry-sky-session-hero"><img src="/assets/starry-sky/starry-sky-hero-bg.png" alt="" /><div><h2>{t('our.starrySky.sessionTitle')}</h2><p>{t('our.starrySky.sessionHeroCopy')}</p></div></section><SoftCard className="starry-sky-session-card" tone="cream"><h2>{title}</h2><p>{body}</p></SoftCard>{invitation ? <><SoftCard className="starry-sky-session-card"><h2>{t('our.starrySky.sessionTopic')}</h2><p>{prompt}</p></SoftCard><SoftCard className="starry-sky-session-card"><h2>{t('our.starrySky.sessionSchedule')}</h2><p>{new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(`${invitation.scheduledLocalDate}T00:00:00`))} · {invitation.startTime}–{invitation.endTime}</p></SoftCard></> : null}<SoftCard className="starry-sky-session-card starry-sky-session-reminder" tone="cream"><p>{t('our.starrySky.sessionExternalConversation')}</p></SoftCard>{invitation && !terminal ? <section className="starry-sky-session-actions"><SecondaryButton disabled={busy} onClick={() => setConfirmingCancel(true)}>{t('our.starrySky.sessionCancel')}</SecondaryButton><PrimaryButton disabled={busy} onClick={() => void mutate('complete')}>{t('our.starrySky.sessionCompletedTitle')}</PrimaryButton></section> : null}{terminal === 'completed' ? <SecondaryButton onClick={() => navigate('/our/starry-sky/history')}>{t('our.starrySky.sessionViewHistory')}</SecondaryButton> : null}{error ? <p role="alert">{error}</p> : null}{confirmingCancel ? <div className="starry-sky-session-dialog-backdrop"><section className="starry-sky-session-dialog" role="dialog" aria-modal="true"><h2>{t('our.starrySky.sessionCancelDialogTitle')}</h2><p>{t('our.starrySky.sessionCancelDialogBody')}</p><footer><SecondaryButton onClick={() => setConfirmingCancel(false)}>{t('our.starrySky.sessionCancelKeep')}</SecondaryButton><PrimaryButton disabled={busy} onClick={() => { setConfirmingCancel(false); void mutate('cancel') }}>{t('our.starrySky.sessionCancelConfirm')}</PrimaryButton></footer></section></div> : null}</main></div>
}
