import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it } from 'vitest'
import { PersistenceProvider } from '../../data/PersistenceContext'
import { initializePersistence } from '../../data/persistence'
import { MemoryStorageAdapter } from '../../data/storage/MemoryStorageAdapter'
import { I18nProvider } from '../../i18n/I18nProvider'
import { ClearHistoryDetail } from './ClearHistoryDetail'

afterEach(cleanup)
async function setup() {
  const adapter = new MemoryStorageAdapter(); const runtime = await initializePersistence({ adapter, defaultLocale: 'zh-TW', localDate: '2026-09-28' }); const stamp = '2026-09-28T00:00:00.000Z'
  await adapter.put('clearRecords', { id: 'clear', triggerType: 'no_reply', triggerText: '他還沒回', facts: '昨天沒有訊息', interpretation: '是不是不在乎', unknown: '他是否很忙', emotions: ['anxious'], emotionIntensity: 4, bodySensations: ['chest_tight'], observations: { listens: 'yes' }, needs: ['clarity'], nextActionType: 'take_a_walk', localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp, completedAt: stamp })
  await adapter.put('loveBoatAssessments', { id: 'boat', status: 'completed', currentSection: 'result', currentQuestionIndex: 21, aAnswers: { a01: 3 }, bAnswers: { b01: 'unknown' }, aScore: 3, aLevel: 'investment_low', bAnsweredItems: 1, bEarnedScore: 0, bMaxPossibleScore: 2, bLevel: 'response_insufficient_observation', crossResultKey: 'low_low', resultVariantIndex: 0, noteToSay: '我想慢一點', localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp, completedAt: stamp })
  await adapter.put('loveBrainAssessments', { id: 'brain', status: 'completed', quizVersion: 2, currentQuestionIndex: 24, answers: { rumination_01: 2 }, v2Scores: { rumination: 2, messagePull: 0, overInterpretation: 0, checking: 0, selfNeglect: 0, totalScore: 2 }, isLowOverall: false, primaryPatterns: [], resultVariantKey: 'tie.v1', localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp, completedAt: stamp })
  await adapter.put('loveBrainAssessments', { id: 'brain-v1', status: 'completed', currentQuestionIndex: 24, answers: { rumination_01: 2 }, isLowOverall: true, resultVariantKey: 'low_overall.v1', localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp, completedAt: stamp })
  await adapter.put('likeOrHabitReflections', { id: 'like', status: 'completed', currentSection: 'result', answers: { realPerson: { real_person_three_real_traits: 'yes' }, fearOfLoss: { fear_of_loss_hardest_part: ['be_alone'] }, imaginedRelationship: { imagined_relationship_reality_description: '目前只是朋友' } }, realPersonNote: '我喜歡他的真誠', activeResultModules: ['real_person'], resultCombinationKey: 'like_only', resultVariantKey: 'like_only.v1', localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp, completedAt: stamp })
  return runtime
}
function show(runtime: Awaited<ReturnType<typeof setup>>, sourceType: 'clear_record' | 'love_boat_code' | 'love_brain_assessment' | 'like_or_habit', recordId: string) { return render(<PersistenceProvider runtime={runtime}><I18nProvider initialLocale="zh-TW"><ClearHistoryDetail sourceType={sourceType} recordId={recordId} /></I18nProvider></PersistenceProvider>) }

describe('Clear history detail', () => {
  it('keeps organize original input collapsed while showing the result and AI handoff', async () => { const runtime = await setup(); show(runtime, 'clear_record', 'clear'); const detail = (await screen.findByText('查看當時作答')).closest('details') as HTMLDetailsElement; expect(screen.getByRole('heading', { name: '這次，我看見了什麼？' })).toBeInTheDocument(); expect(screen.getByText('你現在不需要立刻知道這段關係的答案，只要先照顧此刻的自己。')).toBeInTheDocument(); expect(detail.open).toBe(false); const handoff = screen.getByRole('heading', { name: '✨ 和 AI 聊聊這份結果' }).closest('.clear-ai-handoff'); expect(handoff?.closest('details')).toBeNull(); expect(screen.getByRole('button', { name: '複製結果與內容' })).toBeInTheDocument(); fireEvent.click(screen.getByText('查看當時作答')); expect(detail.open).toBe(true); expect((await screen.findAllByText('昨天沒有訊息')).length).toBeGreaterThan(0); expect(screen.getByText('胸口緊')).toBeInTheDocument(); expect(screen.queryByText('undefined')).not.toBeInTheDocument() })
  it('keeps boat original answers and note collapsed until opened while leaving AI handoff outside', async () => { const runtime = await setup(); show(runtime, 'love_boat_code', 'boat'); expect(await screen.findByRole('heading', { name: '當時結果' })).toBeInTheDocument(); const detail = screen.getByText('查看當時作答').closest('details') as HTMLDetailsElement; expect(detail.open).toBe(false); expect(screen.getByRole('heading', { name: '✨ 和 AI 聊聊這份結果' }).closest('.clear-ai-handoff')?.closest('details')).toBeNull(); fireEvent.click(screen.getByText('查看當時作答')); expect(screen.getByText('我想慢一點')).toBeInTheDocument(); expect(screen.getByText('我會反覆查看他有沒有回我的訊息。')).toBeInTheDocument() })
  it('keeps V2 dimensions and its answers available', async () => { const runtime = await setup(); show(runtime, 'love_brain_assessment', 'brain'); expect((await screen.findAllByText('反芻')).length).toBeGreaterThan(0); fireEvent.click(screen.getByText('查看當時作答')); expect(screen.getByText('一次聊天結束後，我常會在腦中重新想好幾遍我們說過的話。')).toBeInTheDocument(); expect(screen.queryByText('undefined')).not.toBeInTheDocument() })
  it('keeps an unversioned legacy Love Brain record on the V1 result path', async () => { const runtime = await setup(); show(runtime, 'love_brain_assessment', 'brain-v1'); expect(await screen.findByText('你還保留著自己的節奏')).toBeInTheDocument(); expect(screen.queryAllByRole('progress')).toHaveLength(0) })
  it('keeps like-or-habit original answers and free text collapsed while leaving the result and AI handoff visible', async () => { const runtime = await setup(); const view = show(runtime, 'like_or_habit', 'like'); expect(await screen.findByText('我喜歡的是真實的他')).toBeInTheDocument(); expect(view.container.querySelectorAll('.clear-like-result__module')).toHaveLength(1); const detail = screen.getByText('查看當時作答').closest('details') as HTMLDetailsElement; expect(detail.open).toBe(false); expect(screen.getByRole('heading', { name: '✨ 和 AI 聊聊這份結果' }).closest('.clear-ai-handoff')?.closest('details')).toBeNull(); fireEvent.click(screen.getByText('查看當時作答')); expect(screen.getByText('我喜歡他的真誠')).toBeInTheDocument(); expect(screen.getByText('目前只是朋友')).toBeInTheDocument(); expect(screen.getByText('害怕又變成一個人')).toBeInTheDocument(); expect(screen.queryByText('undefined')).not.toBeInTheDocument() })

  it('omits absent legacy boat result and metric fields and suppresses AI handoff rather than inventing zeroes', async () => { const runtime = await setup(); const stamp = '2026-09-28T00:00:00.000Z'; await runtime.adapter.put('loveBoatAssessments', { id: 'boat-incomplete', status: 'completed', currentSection: 'result', currentQuestionIndex: 0, aAnswers: { a01: 1 }, bAnswers: {}, localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp }); show(runtime, 'love_boat_code', 'boat-incomplete'); expect(await screen.findByText('查看當時作答')).toBeInTheDocument(); expect(screen.queryByText('分數：0')).not.toBeInTheDocument(); expect(screen.queryByText('目前可觀察的互動仍不足')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: '複製結果與內容' })).not.toBeInTheDocument() })
  it('suppresses Like or Habit AI handoff when a legacy record has no persisted result key', async () => { const runtime = await setup(); const stamp = '2026-09-28T00:00:00.000Z'; await runtime.adapter.put('likeOrHabitReflections', { id: 'like-incomplete', status: 'completed', currentSection: 'result', answers: { realPerson: { real_person_three_real_traits: 'yes' } }, localDate: '2026-09-28', timezone: 'Asia/Taipei', createdAt: stamp, updatedAt: stamp }); show(runtime, 'like_or_habit', 'like-incomplete'); expect(await screen.findByText('我能說出至少三個真實發生過、不是想像出來的欣賞點嗎？')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: '複製結果與內容' })).not.toBeInTheDocument(); expect(screen.queryByText('unclear.v1')).not.toBeInTheDocument() })
})
